SELECT DISTINCT
    d.DEFAULT_VALOR_TEXT         AS rms_item_code,
    CASE
        WHEN UPPER(ws.WS_KEY) LIKE '%.CASHOUT' THEN 'CASH_OUT'
        ELSE 'CASH_IN'
    END AS movement_type
FROM IN_OMNI_PROVEEDOR_WS_DEFS d
JOIN IN_OMNI_PROVEEDOR_WS ws
    ON ws.ID_WS   = d.ID_WS
   AND ws.ENABLED = 'S'
WHERE d.TIPO_DEF = 'CONFIG'
  AND (d.DEFAULT_CLAVE = 'item' OR d.DEFAULT_CLAVE LIKE 'item.%')
  AND d.DEFAULT_VALOR_TEXT IS NOT NULL
ORDER BY d.DEFAULT_VALOR_TEXT, movement_type
