SELECT CATEGORY_CODE, CATEGORY_NAME, SUBCATEGORY_CODE, SUBCATEGORY_NAME, IS_ACTIVE
FROM AD_CATEGORIA_SUBCATEGORIA
WHERE CHANNEL_POS = :channel_pos
ORDER BY TO_NUMBER(CATEGORY_CODE), TO_NUMBER(SUBCATEGORY_CODE)
