SELECT CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
       INPUT_FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY_CODE, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR
FROM AD_ITEM_SERVICIO_TMP
WHERE CHANNEL_POS = :channel_pos
ORDER BY TO_NUMBER(CATEGORY_CODE), TO_NUMBER(SUBCATEGORY_CODE), TO_NUMBER(SERVICE_PROVIDER_CODE), RMS_ITEM_CODE,
    CASE
        WHEN SERVICE_PROVIDER_CODE = '1' AND RMS_ITEM_CODE = '100708846' AND INPUT_FIELD_ID = 'withdrawId' THEN 1
        WHEN SERVICE_PROVIDER_CODE = '1' AND RMS_ITEM_CODE = '100708846' AND INPUT_FIELD_ID = 'password'   THEN 2
        WHEN SERVICE_PROVIDER_CODE = '1' AND RMS_ITEM_CODE = '100708846' AND INPUT_FIELD_ID = 'amount'     THEN 3
        WHEN SERVICE_PROVIDER_CODE = '2' AND RMS_ITEM_CODE = '100708848' AND INPUT_FIELD_ID = 'document'   THEN 1
        WHEN SERVICE_PROVIDER_CODE = '2' AND RMS_ITEM_CODE = '100708848' AND INPUT_FIELD_ID = 'withdrawId' THEN 2
        WHEN SERVICE_PROVIDER_CODE = '2' AND RMS_ITEM_CODE = '100708848' AND INPUT_FIELD_ID = 'amount'     THEN 3
        ELSE 99
    END,
    INPUT_FIELD_ID
