SELECT CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
       SERVICE_PAYMENT_METHOD_ID, PAYMENT_METHOD_CODE, IS_ACTIVE
FROM AD_COM_FORMPAG_SERVICIO_TMP
WHERE CHANNEL_POS = :channel_pos
ORDER BY TO_NUMBER(CATEGORY_CODE), TO_NUMBER(SUBCATEGORY_CODE), TO_NUMBER(SERVICE_PROVIDER_CODE), RMS_ITEM_CODE, SERVICE_PAYMENT_METHOD_ID
