select category_code, subcategory_code, service_provider_code, rms_item_code, description, is_active, jde_code, movement_type, is_mixed_payment, flg_item, is_refund, min_amount, max_amount, requires_consent, consent_text
from (
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '1' as category_code, '1' as subcategory_code, '1' as service_provider_code, '10001565826' as rms_item_code, 'ECUABET CASH IN' as description, 1 as is_active, 'ABC1234' as jde_code, 'CASH_IN' as movement_type, 1 as is_mixed_payment, 'RECA' as flg_item, 1 as is_refund, '1' as min_amount, '200' as max_amount, 1 as requires_consent, q'[<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Lorem Ipsum</title></head><body><h1>Lorem Ipsum</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p></body></html>]' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '1' as category_code, '1' as subcategory_code, '1' as service_provider_code, '10001565827' as rms_item_code, 'ECUABET CASH OUT' as description, 1 as is_active, 'ABC1235' as jde_code, 'CASH_OUT' as movement_type, 0 as is_mixed_payment, 'RECA' as flg_item, 1 as is_refund, '1' as min_amount, '200' as max_amount, 1 as requires_consent, q'[<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Lorem Ipsum</title></head><body><h1>Lorem Ipsum</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p></body></html>]' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '1' as category_code, '1' as subcategory_code, '2' as service_provider_code, '10001565828' as rms_item_code, 'BET 593 CASH IN' as description, 1 as is_active, 'ABC1236' as jde_code, 'CASH_IN' as movement_type, 1 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 1 as requires_consent, q'[<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Lorem Ipsum</title></head><body><h1>Lorem Ipsum</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p></body></html>]' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '1' as category_code, '1' as subcategory_code, '2' as service_provider_code, '10001565829' as rms_item_code, 'BET 593 CASH OUT' as description, 1 as is_active, 'ABC1237' as jde_code, 'CASH_OUT' as movement_type, 0 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 1 as requires_consent, q'[<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Lorem Ipsum</title></head><body><h1>Lorem Ipsum</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p></body></html>]' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '1' as category_code, '2' as subcategory_code, '2' as service_provider_code, '10001565830' as rms_item_code, 'LOTERIA CASH IN' as description, 1 as is_active, 'ABC1238' as jde_code, 'CASH_IN' as movement_type, 1 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 0 as requires_consent, '' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '1' as category_code, '2' as subcategory_code, '2' as service_provider_code, '20001565830' as rms_item_code, 'PEGA 3 CASH IN' as description, 1 as is_active, 'ZBC1238' as jde_code, 'CASH_IN' as movement_type, 1 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 0 as requires_consent, '' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '1' as category_code, '2' as subcategory_code, '2' as service_provider_code, '10001565831' as rms_item_code, 'LOTERIA CASH OUT' as description, 1 as is_active, 'ABC1239' as jde_code, 'CASH_OUT' as movement_type, 0 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 0 as requires_consent, '' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '1' as category_code, '2' as subcategory_code, '2' as service_provider_code, '10001565832' as rms_item_code, 'LOTTO CASH IN' as description, 1 as is_active, 'ABC1240' as jde_code, 'CASH_IN' as movement_type, 1 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 0 as requires_consent, '' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '1' as category_code, '2' as subcategory_code, '2' as service_provider_code, '10001565833' as rms_item_code, 'LOTTO CASH OUT' as description, 1 as is_active, 'ABC1241' as jde_code, 'CASH_OUT' as movement_type, 0 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 0 as requires_consent, '' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '5' as category_code, '9' as subcategory_code, '7' as service_provider_code, '12004565834' as rms_item_code, 'RECARGAS CLARORECARGA X DOLARES' as description, 1 as is_active, 'ABD65234' as jde_code, 'CASH_IN' as movement_type, 0 as is_mixed_payment, 'FACT' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 0 as requires_consent, '' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '5' as category_code, '9' as subcategory_code, '7' as service_provider_code, '12001565829' as rms_item_code, 'RECARGAS CLARO DATOS$5,15 CLARO PAQ 15DIAS 5GB LLAMA ILIMI WHATSAPP' as description, 1 as is_active, 'ABD61237' as jde_code, 'CASH_IN' as movement_type, 0 as is_mixed_payment, 'FACT' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 0 as requires_consent, '' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '2' as category_code, '3' as subcategory_code, '4' as service_provider_code, '10001565834' as rms_item_code, 'PAGO LUZ RECAUDO' as description, 1 as is_active, 'ABC2234' as jde_code, 'CASH_IN' as movement_type, 1 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 1 as requires_consent, q'[<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Lorem Ipsum</title></head><body><h1>Lorem Ipsum</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p></body></html>]' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '2' as category_code, '4' as subcategory_code, '4' as service_provider_code, '10004565834' as rms_item_code, 'SUPA RECAUDO' as description, 1 as is_active, 'ABC5234' as jde_code, 'CASH_IN' as movement_type, 1 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 1 as requires_consent, q'[<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Lorem Ipsum</title></head><body><h1>Lorem Ipsum</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p></body></html>]' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '2' as category_code, '5' as subcategory_code, '4' as service_provider_code, '10005565834' as rms_item_code, 'MATRICULA RECAUDO' as description, 1 as is_active, 'ABC0234' as jde_code, 'CASH_IN' as movement_type, 1 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 1 as requires_consent, q'[<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Lorem Ipsum</title></head><body><h1>Lorem Ipsum</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p></body></html>]' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '3' as category_code, '6' as subcategory_code, '6' as service_provider_code, '10014565834' as rms_item_code, 'SEGUROS DEL SUR RECAUDO' as description, 1 as is_active, 'ABC55234' as jde_code, 'CASH_IN' as movement_type, 1 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 1 as requires_consent, q'[<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Lorem Ipsum</title></head><body><h1>Lorem Ipsum</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p></body></html>]' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '3' as category_code, '7' as subcategory_code, '5' as service_provider_code, '10024565834' as rms_item_code, 'OTTOCARE MASCOTAS RECAUDO' as description, 1 as is_active, 'ABC65234' as jde_code, 'CASH_IN' as movement_type, 1 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 1 as requires_consent, q'[<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Lorem Ipsum</title></head><body><h1>Lorem Ipsum</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p></body></html>]' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '4' as category_code, '8' as subcategory_code, '5' as service_provider_code, '10204565834' as rms_item_code, 'WESTERN UNION ENVIO' as description, 1 as is_active, 'ABC65234' as jde_code, 'CASH_IN' as movement_type, 0 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 1 as requires_consent, q'[<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Lorem Ipsum</title></head><body><h1>Lorem Ipsum</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p></body></html>]' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '4' as category_code, '8' as subcategory_code, '5' as service_provider_code, '10201565829' as rms_item_code, 'WESTERN UNION RETIRO' as description, 1 as is_active, 'ABC61237' as jde_code, 'CASH_OUT' as movement_type, 0 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 1 as requires_consent, q'[<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Lorem Ipsum</title></head><body><h1>Lorem Ipsum</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p></body></html>]' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '4' as category_code, '8' as subcategory_code, '6' as service_provider_code, '12004565834' as rms_item_code, 'MONEYGRAM ENVIO' as description, 1 as is_active, 'ABD65234' as jde_code, 'CASH_IN' as movement_type, 0 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 1 as requires_consent, q'[<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Lorem Ipsum</title></head><body><h1>Lorem Ipsum</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p></body></html>]' as consent_text from dual
union all
select '1' as chain, '148' as store, 'FYBECA AMAZONAS' as store_name, '1' as pos, 'POS' as channel_pos, '4' as category_code, '8' as subcategory_code, '6' as service_provider_code, '12001565829' as rms_item_code, 'MONEYGRAM RETIRO' as description, 1 as is_active, 'ABD61237' as jde_code, 'CASH_OUT' as movement_type, 0 as is_mixed_payment, 'RECA' as flg_item, 0 as is_refund, '1' as min_amount, '200' as max_amount, 1 as requires_consent, q'[<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Lorem Ipsum</title></head><body><h1>Lorem Ipsum</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p></body></html>]' as consent_text from dual
) catalog
where chain = :chain
  and store = :store
  and store_name = :store_name
  and pos = :pos
  and channel_pos = :channel_pos
order by to_number(category_code), to_number(subcategory_code), to_number(service_provider_code), rms_item_code
