SELECT CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
       DESCRIPTION, IS_ACTIVE, JDE_CODE, MOVEMENT_TYPE, IS_MIXED_PAYMENT, FLG_ITEM,
       IS_REFUND, MIN_AMOUNT, MAX_AMOUNT, TIMEOUT_WS_MAX, RETRIES_WS_MAX,
       NUM_TICKETS, REQUIRES_CONSENT, CONSENT_TEXT
FROM AD_SERVICIO_PARAMETROS
WHERE CHANNEL_POS = :channel_pos
ORDER BY TO_NUMBER(CATEGORY_CODE), TO_NUMBER(SUBCATEGORY_CODE), TO_NUMBER(SERVICE_PROVIDER_CODE), RMS_ITEM_CODE

