SELECT CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RUC_PROVIDER, PROVIDER_NAME, IS_ACTIVE
FROM AD_PROVEEDOR_SERVICIO
WHERE CHANNEL_POS = :channel_pos
ORDER BY TO_NUMBER(CATEGORY_CODE), TO_NUMBER(SUBCATEGORY_CODE), TO_NUMBER(SERVICE_PROVIDER_CODE)
