server.port=8085
logging.level.com.omnistack.backend=DEBUG
app.integrations.mock-enabled=false

# Catalogo business-lines — TUKUNAFUNC en Docker local (XEPDB1)
app.business-lines.oracle.datasource1.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
app.business-lines.oracle.datasource1.username=TUKUNAFUNC
app.business-lines.oracle.datasource1.password=tvkvn4tst
app.business-lines.oracle.datasource1.driver-class-name=oracle.jdbc.OracleDriver

# Transaccional IN_OMNI_* — GPF_OMNISTACK en Docker local (XEPDB1)
app.datasource.hprod.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
app.datasource.hprod.username=GPF_OMNISTACK
app.datasource.hprod.password=F4P_xmtyT_C1MpT
app.datasource.hprod.driver-class-name=oracle.jdbc.OracleDriver
