/* =========================================================
   TABLA: TUKUNAFUNC.IN_WS_PAGOS_DIG
   - PK: CODIGO (se llena por trigger + secuencia)
   - Índices: búsqueda por id_ws, ws_key, enabled, metodo_http, interno
   - Comentarios: se documentan reglas/observaciones
   ========================================================= */

-- 1) TABLA
CREATE TABLE TUKUNAFUNC.IN_WS_PAGOS_DIG
(
  CODIGO           NUMBER(18)   NOT NULL, -- se llena por trigger por medio de una secuencia
  ID_WS            NUMBER(12)   NOT NULL,
  WS_KEY           VARCHAR2(120) NOT NULL,
  ENABLED          CHAR(1)      DEFAULT 'S' NOT NULL, -- N si está desactivado
  METODO_HTTP      VARCHAR2(10) NOT NULL,
  TIPO_REQUEST     VARCHAR2(30) NOT NULL,
  TIPO_RESPONSE    VARCHAR2(30) NOT NULL,

  USR_CREACION     VARCHAR2(100) DEFAULT USER    NOT NULL,
  FEC_CREACION     DATE          DEFAULT SYSDATE NOT NULL,

  INTERNO          CHAR(1)      DEFAULT 'S' NOT NULL, -- N si ejecuta servicios externos
  USR_MODIFICACION VARCHAR2(100),
  FEC_MODIFICACION DATE,

  CP_VAR1          VARCHAR2(1500),
  CP_VAR2          VARCHAR2(1500),
  CP_VAR3          VARCHAR2(1500),
  CP_NUMBER1       NUMBER,
  CP_NUMBER2       NUMBER,
  CP_NUMBER3       NUMBER,
  CP_DATE1         DATE,
  CP_DATE2         DATE,
  CP_DATE3         DATE,

  CONSTRAINT PK_IN_WS_PAGOS_DIG PRIMARY KEY (CODIGO),

  -- Validaciones (observaciones):
  CONSTRAINT CHK_IN_WS_PD_ENABLED
    CHECK (ENABLED IN ('S','N')),

  CONSTRAINT CHK_IN_WS_PD_INTERNO
    CHECK (INTERNO IN ('S','N')),

  CONSTRAINT CHK_IN_WS_PD_MET_HTTP
    CHECK (UPPER(METODO_HTTP) IN ('GET','POST','PUT','PATCH','DELETE')),

  CONSTRAINT CHK_IN_WS_PD_FEC_MOD
    CHECK (FEC_MODIFICACION IS NULL OR FEC_MODIFICACION >= FEC_CREACION)
);

-- 2) SECUENCIA
CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_WS_PAGOS_DIG
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  CACHE 20;
  
--ALTER SEQUENCE TUKUNAFUNC.SEQ_IN_WS_PAGOS_DIG CACHE 20;

-- 3) TRIGGER AUTOINCREMENTAL
CREATE OR REPLACE TRIGGER TUKUNAFUNC.TRG_IN_WS_PAGOS_DIG_BI
BEFORE INSERT ON TUKUNAFUNC.IN_WS_PAGOS_DIG
FOR EACH ROW
BEGIN
  IF :NEW.CODIGO IS NULL THEN
    SELECT TUKUNAFUNC.SEQ_IN_WS_PAGOS_DIG.NEXTVAL
      INTO :NEW.CODIGO
      FROM DUAL;
  END IF;

  -- Defaults defensivos por si insertan NULL explícito
  IF :NEW.USR_CREACION IS NULL THEN
    :NEW.USR_CREACION := USER;
  END IF;

  IF :NEW.FEC_CREACION IS NULL THEN
    :NEW.FEC_CREACION := SYSDATE;
  END IF;
END;
/

-- 4) ÍNDICES
-- (a) Búsqueda por catálogo/relación
CREATE INDEX TUKUNAFUNC.IDX_IWSPD_ID_WS
  ON TUKUNAFUNC.IN_WS_PAGOS_DIG (ID_WS);

-- (b) Búsqueda por clave de servicio (probable lookup principal)
CREATE INDEX TUKUNAFUNC.IDX_IWSPD_WS_KEY
  ON TUKUNAFUNC.IN_WS_PAGOS_DIG (WS_KEY);

-- (c) Filtros operativos comunes (habilitado + interno)
CREATE INDEX TUKUNAFUNC.IDX_IWSPD_ENABLED_INTERNO
  ON TUKUNAFUNC.IN_WS_PAGOS_DIG (ENABLED, INTERNO);

-- (d) Para búsquedas por método
CREATE INDEX TUKUNAFUNC.IDX_IWSPD_METODO_HTTP
  ON TUKUNAFUNC.IN_WS_PAGOS_DIG (METODO_HTTP);

-- (e) Compuesto típico para resolver endpoint activo rápidamente
CREATE INDEX TUKUNAFUNC.IDX_IWSPD_KEY_ENA_INT
  ON TUKUNAFUNC.IN_WS_PAGOS_DIG (WS_KEY, ENABLED, INTERNO);

-- 5) COMENTARIOS (observaciones y documentación)
COMMENT ON TABLE TUKUNAFUNC.IN_WS_PAGOS_DIG IS 'Catálogo de WS para pagos digitales (configuración/metadata).';

COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.CODIGO IS 'PK técnica. Se llena por trigger usando secuencia TUKUNAFUNC.SEQ_IN_WS_PAGOS_DIG.';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.ID_WS IS 'Identificador del WS (catálogo interno / referencia).';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.WS_KEY IS 'Clave funcional del WS (ej: direct-online-payment-requests). Recomendado usar como lookup.';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.ENABLED IS 'S=habilitado, N=deshabilitado.';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.METODO_HTTP IS 'Método HTTP permitido: GET/POST/PUT/PATCH/DELETE.';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.TIPO_REQUEST IS 'Tipo de request (ej: JSON, XML).';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.TIPO_RESPONSE IS 'Tipo de response (ej: JSON, XML).';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.USR_CREACION IS 'Usuario de creación (DEFAULT USER).';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.FEC_CREACION IS 'Fecha de creación (DEFAULT SYSDATE).';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.INTERNO IS 'S=Servicio interno, N=ejecuta servicios externos.';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.USR_MODIFICACION IS 'Usuario que modifica el registro.';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.FEC_MODIFICACION IS 'Fecha de modificación (>= FEC_CREACION).';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.CP_VAR1 IS 'Campo parametrizable 1 (VARCHAR2).';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.CP_VAR2 IS 'Campo parametrizable 2 (VARCHAR2).';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.CP_VAR3 IS 'Campo parametrizable 3 (VARCHAR2).';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.CP_NUMBER1 IS 'Campo parametrizable 1 (NUMBER).';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.CP_NUMBER2 IS 'Campo parametrizable 2 (NUMBER).';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.CP_NUMBER3 IS 'Campo parametrizable 3 (NUMBER).';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.CP_DATE1 IS 'Campo parametrizable 1 (DATE).';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.CP_DATE2 IS 'Campo parametrizable 2 (DATE).';
COMMENT ON COLUMN TUKUNAFUNC.IN_WS_PAGOS_DIG.CP_DATE3 IS 'Campo parametrizable 3 (DATE).';

--INSERTS

INSERT INTO TUKUNAFUNC.IN_WS_PAGOS_DIG
(ID_WS, WS_KEY, ENABLED, METODO_HTTP, TIPO_REQUEST, TIPO_RESPONSE, INTERNO)
VALUES
(1,'banks','S','POST','JSON','JSON','S');

INSERT INTO TUKUNAFUNC.IN_WS_PAGOS_DIG
(ID_WS, WS_KEY, ENABLED, METODO_HTTP, TIPO_REQUEST, TIPO_RESPONSE, INTERNO)
VALUES
(2,'direct-online-payment-requests','S','POST','JSON','JSON','S');

INSERT INTO TUKUNAFUNC.IN_WS_PAGOS_DIG
(ID_WS, WS_KEY, ENABLED, METODO_HTTP, TIPO_REQUEST, TIPO_RESPONSE, INTERNO)
VALUES
(3,'payments-notifications-merchant-events','S','POST','JSON','JSON','N');

INSERT INTO TUKUNAFUNC.IN_WS_PAGOS_DIG
(ID_WS, WS_KEY, ENABLED, METODO_HTTP, TIPO_REQUEST, TIPO_RESPONSE, INTERNO)
VALUES
(4,'payments','S','POST','JSON','JSON','S');

INSERT INTO TUKUNAFUNC.IN_WS_PAGOS_DIG
(ID_WS, WS_KEY, ENABLED, METODO_HTTP, TIPO_REQUEST, TIPO_RESPONSE, INTERNO)
VALUES
(5,'safetypay-confirmation','S','POST','FORM-URLENCODED','JSON','N');

INSERT INTO TUKUNAFUNC.IN_WS_PAGOS_DIG
(ID_WS, WS_KEY, ENABLED, METODO_HTTP, TIPO_REQUEST, TIPO_RESPONSE, INTERNO)
VALUES
(6,'health-check','S','GET','NONE','JSON','S');

COMMIT;
