
CREATE TABLE TUKUNAFUNC.AD_MAPEO_ERRORES (
    HTTP_STATUS NUMBER(3,0) NULL,
    ERROR_CATEGORY VARCHAR2(100 CHAR) NULL,
    INNER_DETAILS_FIELD_MESSAGE VARCHAR2(1000 CHAR) NULL,
    INNER_DETAILS_FIELD_MESSAGE_ES VARCHAR2(1000 CHAR) NULL,
    CURRENT_ERROR_CODE NUMBER(10,0) NOT NULL,
    CURRENT_ERROR_MESSAGE VARCHAR2(1000 CHAR) NULL,
    CURRENT_ERROR_MESSAGE_ES VARCHAR2(1000 CHAR) NULL,
    CONSTRAINT PK_AD_MAPEO_ERRORES PRIMARY KEY (CURRENT_ERROR_CODE)
);

-- Indices recomendados para busqueda por tipo/mensaje
CREATE INDEX TUKUNAFUNC.IX_AD_MAPEO_ERR_CAT_MSG
    ON TUKUNAFUNC.AD_MAPEO_ERRORES (ERROR_CATEGORY, CURRENT_ERROR_MESSAGE);

CREATE INDEX TUKUNAFUNC.IX_AD_MAPEO_ERR_CAT_INNER
    ON TUKUNAFUNC.AD_MAPEO_ERRORES (ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE);

CREATE INDEX TUKUNAFUNC.IX_AD_MAPEO_ERR_HTTP_CAT
    ON TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY);

--TRUNCATE TABLE TUKUNAFUNC.AD_MAPEO_ERRORES;

---------------------------------------
INSERT ALL
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (400, 'INVALID_REQUEST_ERROR', 'The email address is mandatory to Email Sending process.', 'La direccion de correo es obligatoria para el envio de Email.', 21303, 'Email recipient is invalid.', 'El destinatario del correo no es valido.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (400, 'INVALID_REQUEST_ERROR', 'Amount must be different than zero.', 'El monto debe ser diferente de cero.', 21515, 'The email address is mandatory to Email Sending process.', 'La direccion de correo es obligatoria para el envio de Email.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (400, 'INVALID_REQUEST_ERROR', 'Transaction amount is required.', 'El monto de la transaccion es requerido.', 21516, 'Amount must be different than zero.', 'El monto debe ser diferente de cero.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (400, 'INVALID_REQUEST_ERROR', 'The country code is required.', 'El codigo de pais es requerido.', 21517, 'Transaction amount is required.', 'El monto de la transaccion es requerido.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (400, 'INVALID_REQUEST_ERROR', 'Invalid amount. Amount must be greater than zero.', 'Monto invalido. Debe ser mayor que cero.', 21519, 'The country code is required.', 'El codigo de pais es requerido.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (400, 'INVALID_REQUEST_ERROR', 'Invalid amount. Amount must be greater than zero.', 'Monto invalido. Debe ser mayor que cero.', 21520, 'Invalid amount. Amount must be greater than zero.', 'Monto invalido. Debe ser mayor que cero.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (400, 'INVALID_REQUEST_ERROR', 'The BankID code is required.', 'El codigo BankID es requerido.', 21523, 'The BankID code is required.', 'El codigo BankID es requerido.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (422, 'VALIDATION_ERROR', 'The amount of the transaction is less than the minimum allowed in all payment methods.', 'El monto de la transaccion es menor que el minimo permitido en todos los metodos de pago.', 1004, 'The API cannot complete the request or failed business rules validations.', 'El API no puede completar la solicitud o fallaron las validaciones de las reglas comerciales.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (422, 'VALIDATION_ERROR', 'The amount of the transaction exceeded the maximum allowed in all payment methods.', 'El monto de la transaccion excedio el maximo permitido en todos los metodos de pago.', 1005, 'The API cannot complete the request or failed business rules validations.', 'El API no puede completar la solicitud o fallaron las validaciones de las reglas comerciales.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (422, 'VALIDATION_ERROR', 'Transactions does not exist', 'La transaccion no existe.', 20101, 'Transactions does not exist', 'La transaccion no existe.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (422, 'VALIDATION_ERROR', 'Refund amount not allowed', 'El monto de reembolso no esta permitido.', 20103, 'Refund amount not allowed', 'El monto de reembolso no esta permitido.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (422, 'VALIDATION_ERROR', 'OneStepToken not found for this Transaction.', 'OneStepToken no encontrado para esta transaccion.', 21601, 'OneStepToken not found for this Transaction.', 'OneStepToken no encontrado para esta transaccion.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (422, 'VALIDATION_ERROR', 'Some errors have occurred when processing transaction references on Bank Partner Services.', 'Se produjeron errores al procesar referencias de transaccion en los servicios de banco asociado.', 21602, 'Some errors have occurred when processing transaction references on Bank Partner Services.', 'Se produjeron errores al procesar referencias de transaccion en los servicios de banco asociado.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (422, 'VALIDATION_ERROR', 'Token Expired', 'Token expirado.', 21603, 'Token Expired', 'Token expirado.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (422, 'VALIDATION_ERROR', 'Transaction Expired', 'Transaccion expirada.', 21604, 'Transaction Expired', 'Transaccion expirada.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An unhandled error ocurred in Merchant Payment API - HealthChecks Operation.', 'Error no controlado en Merchant Payment API  HealthChecks Operation.', 21500, 'An unhandled error ocurred in Direct Service - CommunicationTest Operation.', 'Error no controlado en Direct Service  CommunicationTest Operation.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An unhandled error ocurred in Merchant Payment API - OnlinePaymentRequest Operation.', 'Error no controlado en Merchant Payment API  OnlinePaymentRequest Operation.', 21501, 'An unhandled error ocurred in Direct Service - OnlinePaymentRequest Operation.', 'Error no controlado en Direct Service  OnlinePaymentRequest Operation.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An unhandled error ocurred in Merchant Payment API - CashPaymentRequest Operation.', 'Error no controlado en Merchant Payment API  CashPaymentRequest Operation.', 21502, 'An unhandled error ocurred in Direct Service - CashPaymentRequest Operation.', 'Error no controlado en Direct Service  CashPaymentRequest Operation.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An unhandled error ocurred in Merchant Payment API - DirectCashPayment Operation.', 'Error no controlado en Merchant Payment API  DirectCashPayment Operation.', 21503, 'An unhandled error ocurred in Direct Service - CreateCustomCashPayment Operation.', 'Error no controlado en Direct Service  CreateCustomCashPayment Operation.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'Generic Error in [OperationName] operation.', 'Error generico en la operacion [OperationName].', 21512, 'Generic Error in [OperationName] operation.', 'Error generico en la operacion [OperationName].')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An error occurred when performing a CreateRefund.', 'Error al ejecutar CreateRefund.', 21507, 'An error occurred when performing a CreateRefund.', 'Error al ejecutar CreateRefund.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An error occurred when performing a Create Express Token.', 'Error al ejecutar Create Express Token.', 21508, 'An error occurred when performing a Create Express Token.', 'Error al ejecutar Create Express Token.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An error occurred when performing a GetNewOperationActivity.', 'Error al ejecutar GetNewOperationActivity.', 21509, 'An error occurred when performing a GetNewOperationActivity.', 'Error al ejecutar GetNewOperationActivity.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An error occurred when performing a ConfirmNewOperationActivity.', 'Error al ejecutar ConfirmNewOperationActivity.', 21510, 'An error occurred when performing a ConfirmNewOperationActivity.', 'Error al ejecutar ConfirmNewOperationActivity.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An error occurred when performing a SendEmail.', 'Error al ejecutar SendEmail.', 21514, 'An error occurred when performing a SendEmail.', 'Error al ejecutar SendEmail.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An unhandled error ocurred in Merchant Payment API - GetBanks Operation.', 'Error no controlado en Merchant Payment API  GetBanks Operation.', 21521, 'An unhandled error ocurred in Direct Service - GetBanks Operation.', 'Error no controlado en Direct Service  GetBanks Operation.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An unhandled error ocurred in Merchant Payment API - DirectOnlinePayment Operation.', 'Error no controlado en Merchant Payment API  DirectOnlinePayment Operation.', 21522, 'An unhandled error ocurred in Direct Service - CreateCustomOnlinePayment Operation.', 'Error no controlado en Direct Service  CreateCustomOnlinePayment Operation.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An error occurred when performing a GetOperation', 'Error al ejecutar GetOperation.', 21532, 'An error occurred when performing a GetOperation', 'Error al ejecutar GetOperation.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An error occurred when try getting Steps and Instructions payment', 'Error al intentar obtener Steps and Instructions de pago.', 21533, 'An error occurred when try getting Steps and Instructions payment', 'Error al intentar obtener Steps and Instructions de pago.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An unhandled error ocurred in BanksPartner Service - GeneratePartnersInfo Operation', 'Error no controlado en BanksPartner Service  GeneratePartnersInfo Operation.', 21600, 'An unhandled error ocurred in BanksPartner Service - GeneratePartnersInfo Operation', 'Error no controlado en BanksPartner Service  GeneratePartnersInfo Operation.')
    INTO TUKUNAFUNC.AD_MAPEO_ERRORES (HTTP_STATUS, ERROR_CATEGORY, INNER_DETAILS_FIELD_MESSAGE, INNER_DETAILS_FIELD_MESSAGE_ES, CURRENT_ERROR_CODE, CURRENT_ERROR_MESSAGE, CURRENT_ERROR_MESSAGE_ES) VALUES (500, 'API_ERROR', 'An Error occurred generating a payment reference', 'Error al generar una referencia de pago.', 21605, 'An Error occurred generating a payment reference', 'Error al generar una referencia de pago.')
SELECT 1 FROM DUAL;

COMMIT;


