/* ============================================================
   Tabla de configuracion interna: SafetyPay Confirmation
   Esquema: TUKUNAFUNC
   ============================================================ */

CREATE TABLE TUKUNAFUNC.IN_SAFETYPAY_CFG (
    ID_CFG               NUMBER(19,0) NOT NULL,
    CODIGO_BILLETERA     NUMBER(10,0) NOT NULL,
    NOMBRE_PROVEEDOR     VARCHAR2(100 CHAR) NOT NULL,
    ENABLED              CHAR(1) DEFAULT 'S' NOT NULL,
    API_KEY              VARCHAR2(200 CHAR) NOT NULL,
    SECRET               VARCHAR2(500 CHAR) NOT NULL,
    SIGNATURE_MODE       VARCHAR2(30 CHAR) DEFAULT 'SHA256' NOT NULL,
    ALLOWED_IPS          CLOB,
    ACTIVO               CHAR(1) DEFAULT 'S' NOT NULL,
    USUARIO_CREACION     VARCHAR2(50 CHAR) DEFAULT USER NOT NULL,
    FECHA_CREACION       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    USUARIO_MODIFICACION VARCHAR2(50 CHAR),
    FECHA_MODIFICACION   TIMESTAMP,
    OBSERVACION          VARCHAR2(500 CHAR),

    CONSTRAINT PK_IN_SAFETYPAY_CFG PRIMARY KEY (ID_CFG),
    CONSTRAINT FK_IN_SAFETYPAY_CFG_BILL FOREIGN KEY (CODIGO_BILLETERA)
        REFERENCES TUKUNAFUNC.AD_BILLETERAS_DIGITALES (CODIGO),
    CONSTRAINT CK_IN_SAFETYPAY_CFG_ENABLED CHECK (ENABLED IN ('S','N')),
    CONSTRAINT CK_IN_SAFETYPAY_CFG_ACTIVO CHECK (ACTIVO IN ('S','N'))
);

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_SAFETYPAY_CFG
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER TUKUNAFUNC.TRG_BI_IN_SAFETYPAY_CFG
BEFORE INSERT ON TUKUNAFUNC.IN_SAFETYPAY_CFG
FOR EACH ROW
WHEN (NEW.ID_CFG IS NULL)
BEGIN
    :NEW.ID_CFG := TUKUNAFUNC.SEQ_IN_SAFETYPAY_CFG.NEXTVAL;
END;
/

CREATE UNIQUE INDEX TUKUNAFUNC.UIX_IN_SAFETYPAY_CFG_01
ON TUKUNAFUNC.IN_SAFETYPAY_CFG (CODIGO_BILLETERA);

CREATE INDEX TUKUNAFUNC.IX_IN_SAFETYPAY_CFG_01
ON TUKUNAFUNC.IN_SAFETYPAY_CFG (ACTIVO, ENABLED);

----------------------------------------------------------
/* SOLO PAYSAFE: requiere que CODIGO=235689 exista en AD_BILLETERAS_DIGITALES */

INSERT INTO TUKUNAFUNC.IN_SAFETYPAY_CFG (
    ID_CFG,
    CODIGO_BILLETERA,
    NOMBRE_PROVEEDOR,
    ENABLED,
    API_KEY,
    SECRET,
    SIGNATURE_MODE,
    ALLOWED_IPS,
    ACTIVO,
    USUARIO_CREACION,
    FECHA_CREACION
)
SELECT
    TUKUNAFUNC.SEQ_IN_SAFETYPAY_CFG.NEXTVAL,
    235689,
    'PAYSAFE',
    'S',
    'c14e0ba4e1845e09ba08a4be0fba95e5',
    'a8fed296d6a4e4d877c1abbe8de938a2',
    'SHA256',
    '',
    'S',
    USER,
    SYSTIMESTAMP
FROM DUAL
WHERE EXISTS (
    SELECT 1
    FROM TUKUNAFUNC.AD_BILLETERAS_DIGITALES
    WHERE CODIGO = 235689
)
AND NOT EXISTS (
    SELECT 1
    FROM TUKUNAFUNC.IN_SAFETYPAY_CFG
    WHERE CODIGO_BILLETERA = 235689
);

COMMIT;

