/* ============================================================
   ESQUEMA: TUKUNAFUNC
   OBJETIVO:
   Parametrizar atributos de conexión por PASARELA (AD_BILLETERAS_DIGITALES.CODIGO)
   y por WS, considerando:
   - Por cada CODIGO (billetera/pasarela) existen N WS.
   - Para cada CODIGO, los HEADERS son los mismos para todos sus WS.
   - Los DEFS pueden variar por WS.

   NOTA:
   - Se usan SECUENCIAS + TRIGGERS (sin IDENTITY).
   - Ajusta TABLESPACE / STORAGE si tu estándar lo requiere.
   ============================================================ */

---------------------------------------------------------------
-- 1) TABLA: WS POR PASARELA
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_PASARELA_WS (
  ID_WS            NUMBER(12)        NOT NULL,
  CODIGO_BILLETERA       NUMBER(12)        NOT NULL,  -- FK a AD_BILLETERAS_DIGITALES(CODIGO)

  WS_KEY           VARCHAR2(120)     NOT NULL,  -- ej: direct-online-payment-requests, merchant-events, payments, getbanks
  ENABLED                CHAR(1) DEFAULT 'S' NOT NULL, -- S/N
  TIPO_CONEXION          VARCHAR2(30)      NOT NULL,  -- ej: REST
  METODO_HTTP            VARCHAR2(10)      NOT NULL,  -- GET/POST/PUT/DELETE...
  TIPO_REQUEST           VARCHAR2(30)      NOT NULL,  -- JSON / PARAMETROS / etc
  URL                    VARCHAR2(500)     NOT NULL,

  -- Auditoría básica
  USR_CREACION           VARCHAR2(100)     DEFAULT USER NOT NULL,
  FEC_CREACION           DATE              DEFAULT SYSDATE NOT NULL,
  USR_MODIFICACION       VARCHAR2(100),
  FEC_MODIFICACION       DATE,

  CONSTRAINT PK_IN_PASARELA_WS
    PRIMARY KEY (ID_WS),

  CONSTRAINT FK_IN_PASARELA_WS_BIL
    FOREIGN KEY (CODIGO_BILLETERA)
    REFERENCES TUKUNAFUNC.AD_BILLETERAS_DIGITALES (CODIGO),

  CONSTRAINT CK_IN_PASARELA_WS_ENA
    CHECK (ENABLED IN ('S','N'))
);

-- Un WS_key no se debe repetir dentro de la misma pasarela
CREATE UNIQUE INDEX TUKUNAFUNC.UX_IN_PASARELA_WS_01
  ON TUKUNAFUNC.IN_PASARELA_WS (CODIGO_BILLETERA, WS_KEY);

-- Índice para acelerar joins por FK
CREATE INDEX TUKUNAFUNC.IX_IN_PASARELA_WS_01
  ON TUKUNAFUNC.IN_PASARELA_WS (CODIGO_BILLETERA);

-- (Opcional) Índices por filtro operativo
CREATE INDEX TUKUNAFUNC.IX_IN_PASARELA_WS_02
  ON TUKUNAFUNC.IN_PASARELA_WS (ENABLED, METODO_HTTP);

COMMENT ON TABLE  TUKUNAFUNC.IN_PASARELA_WS IS 'Catálogo de WS por pasarela (billetera digital) para consumo REST.';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS.ID_WS       IS 'PK técnica del WS.';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS.CODIGO_BILLETERA  IS 'FK a AD_BILLETERAS_DIGITALES.CODIGO.';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS.WS_KEY      IS 'Clave del WS (ej: direct-online-payment-requests, merchant-events, payments, getbanks).';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS.ENABLED           IS 'S=habilitado, N=deshabilitado.';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS.TIPO_CONEXION     IS 'Tipo de conexión (ej: REST).';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS.METODO_HTTP       IS 'Método HTTP (GET/POST/etc).';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS.TIPO_REQUEST      IS 'Tipo de request (JSON, PARAMETROS, etc).';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS.URL               IS 'URL completa del WS.';

---------------------------------------------------------------
-- 2) TABLA: HEADERS POR PASARELA (MISMO HEADER PARA SUS WS)
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_PASARELA_HEADERS (
  ID_HEADER              NUMBER(12)        NOT NULL,
  CODIGO_BILLETERA       NUMBER(12)        NOT NULL, -- FK a AD_BILLETERAS_DIGITALES(CODIGO)

  HEADER_NOMBRE          VARCHAR2(200)     NOT NULL, -- ej: X-Api-Key, X-Version, Content-Type
  HEADER_VALOR           VARCHAR2(2000)    NOT NULL, -- valor del header (puede ser largo)

  -- Auditoría básica
  USR_CREACION           VARCHAR2(100)     DEFAULT USER NOT NULL,
  FEC_CREACION           DATE              DEFAULT SYSDATE NOT NULL,
  USR_MODIFICACION       VARCHAR2(100),
  FEC_MODIFICACION       DATE,

  CONSTRAINT PK_IN_PASARELA_HEADERS
    PRIMARY KEY (ID_HEADER),

  CONSTRAINT FK_IN_PASARELA_HEADERS_BIL
    FOREIGN KEY (CODIGO_BILLETERA)
    REFERENCES TUKUNAFUNC.AD_BILLETERAS_DIGITALES (CODIGO)
);

-- Un header no se debe repetir dentro de una pasarela
CREATE UNIQUE INDEX TUKUNAFUNC.UX_IN_PASARELA_HEADERS_01
  ON TUKUNAFUNC.IN_PASARELA_HEADERS (CODIGO_BILLETERA, HEADER_NOMBRE);

CREATE INDEX TUKUNAFUNC.IX_IN_PASARELA_HEADERS_01
  ON TUKUNAFUNC.IN_PASARELA_HEADERS (CODIGO_BILLETERA);

COMMENT ON TABLE  TUKUNAFUNC.IN_PASARELA_HEADERS IS 'Headers HTTP por pasarela (aplican a todos los WS de su CODIGO).';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_HEADERS.ID_HEADER       IS 'PK técnica del header.';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_HEADERS.CODIGO_BILLETERA IS 'FK a AD_BILLETERAS_DIGITALES.CODIGO.';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_HEADERS.HEADER_NOMBRE   IS 'Nombre del header HTTP (case-insensitive a nivel app).';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_HEADERS.HEADER_VALOR    IS 'Valor del header HTTP.';

---------------------------------------------------------------
-- 3) TABLA: DEFS POR WS (VARÍAN POR WS)
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_PASARELA_WS_DEFS (
  ID_DEFAULT             NUMBER(12)        NOT NULL,
  ID_WS            NUMBER(12)        NOT NULL, -- FK a IN_PASARELA_WS.ID_WS
  
  TIPO_DEF               VARCHAR2(100),
 
  DEFAULT_CLAVE          VARCHAR2(200)     NOT NULL, -- ej: payment_ok_url, payment_error_url, application_id
  DEFAULT_VALOR_TEXTO    VARCHAR2(4000),              -- valor como texto
  DEFAULT_VALOR_NUM      NUMBER(18,6),                -- si aplica (ej: application_id)
  DEFAULT_VALOR_FECHA    DATE,                        -- si aplica
  DEFAULT_VALOR_SISTEMA  VARCHAR2(4000),
  -- Auditoría básica
  USR_CREACION           VARCHAR2(100)     DEFAULT USER NOT NULL,
  FEC_CREACION           DATE              DEFAULT SYSDATE NOT NULL,
  USR_MODIFICACION       VARCHAR2(100),
  FEC_MODIFICACION       DATE,

  CONSTRAINT PK_IN_PASARELA_WS_DEFS
    PRIMARY KEY (ID_DEFAULT),

  CONSTRAINT FK_IN_PASARELA_WS_DEFS_EP
    FOREIGN KEY (ID_WS)
    REFERENCES TUKUNAFUNC.IN_PASARELA_WS (ID_WS)
);

-- Una clave default no se debe repetir dentro del mismo WS
CREATE UNIQUE INDEX TUKUNAFUNC.UX_IN_PASARELA_WS_DEFS_01
  ON TUKUNAFUNC.IN_PASARELA_WS_DEFS (ID_WS, DEFAULT_CLAVE);

CREATE INDEX TUKUNAFUNC.IX_IN_PASARELA_WS_DEFS_01
  ON TUKUNAFUNC.IN_PASARELA_WS_DEFS (ID_WS);

COMMENT ON TABLE  TUKUNAFUNC.IN_PASARELA_WS_DEFS IS 'DEFS/valores por defecto configurables por WS.';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS_DEFS.ID_DEFAULT          IS 'PK técnica del default.';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS_DEFS.ID_WS         IS 'FK a IN_PASARELA_WS.ID_WS.';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS_DEFS.DEFAULT_CLAVE       IS 'Nombre de parámetro por defecto (ej: payment_ok_url).';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS_DEFS.DEFAULT_VALOR_TEXTO IS 'Valor por defecto en texto.';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS_DEFS.DEFAULT_VALOR_NUM   IS 'Valor por defecto numérico (si aplica).';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS_DEFS.DEFAULT_VALOR_FECHA IS 'Valor por defecto fecha (si aplica).';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS_DEFS.DEFAULT_VALOR_SISTEMA IS 'Valor por defecto sistema (si aplica).';
COMMENT ON COLUMN TUKUNAFUNC.IN_PASARELA_WS_DEFS.TIPO_DEF IS 'Tipo a Variable a Utilizar';

---------------------------------------------------------------
-- 4) SECUENCIAS
---------------------------------------------------------------
CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_PASARELA_WS
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_PASARELA_HEADERS
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_PASARELA_WS_DEFS
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

---------------------------------------------------------------
-- 5) TRIGGERS (AUTOINCREMENT)
---------------------------------------------------------------
CREATE OR REPLACE TRIGGER TUKUNAFUNC.TRG_IN_PAS_WS_BI
BEFORE INSERT ON TUKUNAFUNC.IN_PASARELA_WS
FOR EACH ROW
BEGIN
  IF :NEW.ID_WS IS NULL THEN
    SELECT TUKUNAFUNC.SEQ_IN_PASARELA_WS.NEXTVAL
      INTO :NEW.ID_WS
      FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TUKUNAFUNC.TRG_IN_PAS_HEADERS_BI
BEFORE INSERT ON TUKUNAFUNC.IN_PASARELA_HEADERS
FOR EACH ROW
BEGIN
  IF :NEW.ID_HEADER IS NULL THEN
    SELECT TUKUNAFUNC.SEQ_IN_PASARELA_HEADERS.NEXTVAL
      INTO :NEW.ID_HEADER
      FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TUKUNAFUNC.TRG_IN_PAS_EP_DEFS_BI
BEFORE INSERT ON TUKUNAFUNC.IN_PASARELA_WS_DEFS
FOR EACH ROW
BEGIN
  IF :NEW.ID_DEFAULT IS NULL THEN
    SELECT TUKUNAFUNC.SEQ_IN_PASARELA_WS_DEFS.NEXTVAL
      INTO :NEW.ID_DEFAULT
      FROM DUAL;
  END IF;
END;
/

