-- ============================================================
-- Ejecutar como: RMS
-- docker exec -it oracle-oracle-1 sqlplus rms/rms123@XEPDB1
-- Simula tablas Oracle Retail usadas por el endpoint /business-lines
-- ============================================================
SET SQLBLANKLINES ON

CREATE TABLE CLASS (
    CLASS       NUMBER(4,0)    NOT NULL,
    CLASS_NAME  VARCHAR2(120)  NOT NULL,
    CONSTRAINT CLASS_PK PRIMARY KEY (CLASS)
);

CREATE TABLE SUBCLASS (
    CLASS        NUMBER(4,0)   NOT NULL,
    SUBCLASS_ID  NUMBER(4,0)   NOT NULL,
    SUB_NAME     VARCHAR2(120) NOT NULL,
    CONSTRAINT SUBCLASS_PK PRIMARY KEY (CLASS, SUBCLASS_ID)
);

CREATE TABLE ITEM_MASTER (
    ITEM        NUMBER(25,0)   NOT NULL,
    ITEM_DESC   VARCHAR2(250),
    SHORT_DESC  VARCHAR2(120),
    CLASS       NUMBER(4,0),
    SUBCLASS    NUMBER(4,0),
    CONSTRAINT ITEM_MASTER_PK PRIMARY KEY (ITEM)
);

CREATE TABLE SUPS (
    SUPPLIER             NUMBER(10,0)  NOT NULL,
    SUP_NAME             VARCHAR2(240),
    SUP_NAME_SECONDARY   VARCHAR2(240),
    CONSTRAINT SUPS_PK PRIMARY KEY (SUPPLIER)
);

CREATE TABLE ITEM_SUPPLIER (
    ITEM        NUMBER(25,0)  NOT NULL,
    SUPPLIER    NUMBER(10,0)  NOT NULL,
    CONSTRAINT ITEM_SUPPLIER_PK PRIMARY KEY (ITEM, SUPPLIER)
);

CREATE TABLE UDA (
    UDA_ID      NUMBER(5,0)   NOT NULL,
    UDA_DESC    VARCHAR2(120),
    CONSTRAINT UDA_PK PRIMARY KEY (UDA_ID)
);

CREATE TABLE UDA_ITEM_LOV (
    UDA_ID      NUMBER(5,0)   NOT NULL,
    ITEM        NUMBER(25,0)  NOT NULL,
    UDA_VALUE   NUMBER(5,0)   NOT NULL,
    CONSTRAINT UDA_ITEM_LOV_PK PRIMARY KEY (UDA_ID, ITEM)
);

CREATE TABLE UDA_VALUES (
    UDA_ID          NUMBER(5,0)   NOT NULL,
    UDA_VALUE       NUMBER(5,0)   NOT NULL,
    UDA_VALUE_DESC  VARCHAR2(250) NOT NULL,
    CONSTRAINT UDA_VALUES_PK PRIMARY KEY (UDA_ID, UDA_VALUE)
);

COMMIT;
