-- ============================================================
-- Ejecutar como: GPF_OMNISTACK
-- docker exec -it oracle-oracle-1 sqlplus GPF_OMNISTACK/F4P_xmtyT_C1MpT@XEPDB1
-- Crea las tablas DBA que existen en QA/prod pero no en el Docker local.
-- El script es re-ejecutable: hace DROP silencioso antes de cada CREATE.
-- ============================================================
SET SQLBLANKLINES ON

BEGIN EXECUTE IMMEDIATE 'DROP TABLE AD_CANAL_SERVICIO';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AD_COM_FORMPAG_SERVICIO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AD_ITEM_SERVICIO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AD_SERVICIO_PARAMETROS';  EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE AD_SERVICIO_PARAMETROS (
    ID_CONFIG                NUMBER          NOT NULL,
    CODIGO_ITEM_RMS          VARCHAR2(25)    NOT NULL,
    TERCERO                  NUMBER          NOT NULL,
    FLG_PAGO_MIXTO           CHAR(1)         DEFAULT 'N' NOT NULL,
    FLG_ITEM                 VARCHAR2(10)    NOT NULL,
    FLG_DEVOLUCION           CHAR(1)         DEFAULT 'N' NOT NULL,
    MONTO_MIN                NUMBER          NOT NULL,
    MONTO_MAX                NUMBER          NOT NULL,
    REQUIERE_CONSENTIMIENTO  CHAR(1)         DEFAULT 'N' NOT NULL,
    TEXTO_CONSENTIMIENTO     CLOB,
    TIMEOUT_WS_MAX           VARCHAR2(10),
    RETRIES_WS_MAX           VARCHAR2(10),
    NUM_TICKETS              VARCHAR2(10),
    USUARIO_REGISTRO         VARCHAR2(30)    DEFAULT USER NOT NULL,
    FECHA_REGISTRO           DATE            DEFAULT SYSDATE NOT NULL,
    USUARIO_MODIFICACION     VARCHAR2(30),
    FECHA_MODIFICACION       DATE,
    ID_HOMOLGADO             VARCHAR2(1),
    CONSTRAINT AD_SERV_PARAM_PK PRIMARY KEY (ID_CONFIG),
    CONSTRAINT AD_SERV_PARAM_FLG_PAG_CK CHECK (FLG_PAGO_MIXTO IN ('S','N')),
    CONSTRAINT AD_SERV_PARAM_FLG_DEV_CK CHECK (FLG_DEVOLUCION IN ('S','N')),
    CONSTRAINT AD_SERV_PARAM_REQ_CON_CK CHECK (REQUIERE_CONSENTIMIENTO IN ('S','N'))
);

CREATE TABLE AD_ITEM_SERVICIO (
    COD_ITEM_SERV        NUMBER          NOT NULL,
    ID_CONFIG            NUMBER          NOT NULL,
    TAG                  VARCHAR2(4000),
    VALOR_TAG            VARCHAR2(4000),
    USUARIO_MODIFICACION VARCHAR2(30),
    FECHA_MODIFICACION   DATE,
    USUARIO_REGISTRO     VARCHAR2(30)    DEFAULT USER NOT NULL,
    FECHA_REGISTRO       DATE            DEFAULT SYSDATE NOT NULL,
    ACTIVO               CHAR(1)         DEFAULT 'S' NOT NULL,
    CONSTRAINT AD_ITEM_SERV_PK PRIMARY KEY (COD_ITEM_SERV),
    CONSTRAINT AD_ITEM_SERV_ACTIVO_CK CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE AD_COM_FORMPAG_SERVICIO (
    COD_COM_FORMPAG_SERV NUMBER          NOT NULL,
    ID_CONFIG            NUMBER          NOT NULL,
    COMISION             NUMBER          DEFAULT 0 NOT NULL,
    COD_FORMA_PAGO       NUMBER          NOT NULL,
    USUARIO_REGISTRO     VARCHAR2(30)    DEFAULT USER NOT NULL,
    FECHA_REGISTRO       DATE            DEFAULT SYSDATE NOT NULL,
    USUARIO_MODIFICACION VARCHAR2(30),
    FECHA_MODIFICACION   DATE,
    ACTIVO               CHAR(1)         DEFAULT 'S' NOT NULL,
    CONSTRAINT AD_COM_FORMPAG_PK PRIMARY KEY (COD_COM_FORMPAG_SERV),
    CONSTRAINT AD_COM_FORMPAG_ACTIVO_CK CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE AD_CANAL_SERVICIO (
    COD_CAN_SERV         NUMBER          NOT NULL,
    CODIGO_CANAL         NUMBER          NOT NULL,
    ID_CONFIG            NUMBER          NOT NULL,
    FECHA_REGISTRO       DATE            DEFAULT SYSDATE NOT NULL,
    USUARIO_REGISTRO     VARCHAR2(30)    DEFAULT USER NOT NULL,
    USUARIO_MODIFICACION VARCHAR2(30),
    FECHA_MODIFICACION   DATE,
    ACTIVO               CHAR(1)         DEFAULT 'S' NOT NULL,
    CONSTRAINT AD_CANAL_SERV_PK PRIMARY KEY (COD_CAN_SERV),
    CONSTRAINT AD_CANAL_SERV_ACTIVO_CK CHECK (ACTIVO IN ('S','N'))
);

COMMIT;
