-- ============================================================
-- Ejecutar como: GPF_OMNISTACK
-- docker exec -it oracle-oracle-1 sqlplus GPF_OMNISTACK/F4P_xmtyT_C1MpT@XEPDB1
-- TERCERO = service_provider_code del properties:
--   1 = Ecuabet        (items 100713841 CASH_IN, 100708846 CASH_OUT, subcategory=1)
--   2 = Loteria BET593 (items 100708850 CASH_IN, 100708848 CASH_OUT, subcategory=1)
--   2 = PEGA3          (item 20001565830 CASH_IN, subcategory=2)
--   2 = Tradicionales  (item 10001565830 CASH_IN, subcategory=2)
-- CODIGO_CANAL = 1 representa el canal POS (TUKUNAFUNC.AD_CANAL CODIGO='POS')
-- ============================================================
SET SQLBLANKLINES ON

-- --------------------------------------------------------
-- AD_SERVICIO_PARAMETROS
-- --------------------------------------------------------
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
VALUES (1, '100713841', 1, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de manera expresa el registro y uso de mis datos personales para la creacion de mi cuenta en ECUA BET.',
    '10', '3', '2', 'GPF_OMNISTACK', SYSDATE);

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
VALUES (2, '100708846', 1, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de manera expresa el registro y uso de mis datos personales para la creacion de mi cuenta en ECUA BET.',
    '10', '3', '3', 'GPF_OMNISTACK', SYSDATE);

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
VALUES (3, '100708850', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '3', 'GPF_OMNISTACK', SYSDATE);

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
VALUES (4, '100708848', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '3', 'GPF_OMNISTACK', SYSDATE);

-- --------------------------------------------------------
-- AD_CANAL_SERVICIO — asocia cada config con canal POS (CODIGO_CANAL=1)
-- --------------------------------------------------------
INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (1, 1, 1, 'GPF_OMNISTACK', SYSDATE, 'S');

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (2, 1, 2, 'GPF_OMNISTACK', SYSDATE, 'S');

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (3, 1, 3, 'GPF_OMNISTACK', SYSDATE, 'S');

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (4, 1, 4, 'GPF_OMNISTACK', SYSDATE, 'S');

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (5, 1, 5, 'GPF_OMNISTACK', SYSDATE, 'S');

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (6, 1, 6, 'GPF_OMNISTACK', SYSDATE, 'S');

-- --------------------------------------------------------
-- AD_COM_FORMPAG_SERVICIO — forma de pago por servicio
-- --------------------------------------------------------
INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (1, 1, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S');

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (2, 2, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S');

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (3, 3, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S');

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (4, 4, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S');

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (5, 5, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S');

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (6, 6, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S');

-- --------------------------------------------------------
-- AD_ITEM_SERVICIO — parametros internos del WS (no son campos de UI)
-- --------------------------------------------------------
INSERT INTO AD_ITEM_SERVICIO
    (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (1, 1, 'numero_tarjeta', '7777771111111110', 'GPF_OMNISTACK', SYSDATE, 'S');

INSERT INTO AD_ITEM_SERVICIO
    (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (2, 1, 'tipo_servicio', '02', 'GPF_OMNISTACK', SYSDATE, 'S');

INSERT INTO AD_ITEM_SERVICIO
    (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (3, 2, 'numero_tarjeta', '7777771111111110', 'GPF_OMNISTACK', SYSDATE, 'S');

INSERT INTO AD_ITEM_SERVICIO
    (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
VALUES (4, 3, 'numero_tarjeta', '7777771111111110', 'GPF_OMNISTACK', SYSDATE, 'S');

-- --------------------------------------------------------
-- AD_SERVICIO_PARAMETROS — PEGA3 (ID_CONFIG=5) y Tradicionales (ID_CONFIG=6)
-- --------------------------------------------------------
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
VALUES (5, '20001565830', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE);

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
VALUES (6, '10001565830', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE);

COMMIT;
