-- ============================================================
-- Ejecutar como: GPF_OMNISTACK
-- docker exec -it oracle-oracle-1 sqlplus GPF_OMNISTACK/F4P_xmtyT_C1MpT@XEPDB1
--
-- Items alineados con QA (MOMDEV) — 16 items reales de rms.ITEM_MASTER.
-- TERCERO = supplier real de QA (rms.SUPS.SUPPLIER):
--   407925 = CONCECEL - Sin División  → ECUABET (100713841 CI, 100708846 CO)
--                                        BET593  (100708850 CI, 100708848 CO)
--   407827 = BROADNET S.A. - Sin División → PEGA3  (100713848, 100713850, 100708852, 100708858, 100708860, 100708862)
--                                            TRAD   (100713842, 100713844, 100713846, 100708854, 100708855, 100708856)
-- CODIGO_CANAL = 1 → canal POS (TUKUNAFUNC.AD_CANAL CODIGO='POS')
-- IDs generados con secuencias (SEQ_AD_SERVICIO_PARAMETROS, SEQ_AD_CANAL_SERVICIO,
-- SEQ_AD_COM_FORMPAG_SERVICIO, SEQ_AD_ITEM_SERVICIO). Creadas en 03_GPF_OMNISTACK_CAMBIOS.sql.
-- Script re-ejecutable: NOT EXISTS en cada INSERT.
-- ============================================================
SET SQLBLANKLINES ON

-- ============================================================
-- AD_SERVICIO_PARAMETROS
-- ============================================================

-- ECUABET CASH IN
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100713841', 407925, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de manera expresa el registro y uso de mis datos personales para la creacion de mi cuenta en ECUA BET.',
    '10', '3', '2', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713841');

-- ECUABET CASH OUT
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100708846', 407925, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de manera expresa el registro y uso de mis datos personales para la creacion de mi cuenta en ECUA BET.',
    '10', '3', '3', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708846');

-- BET593 CASH IN
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100708850', 407925, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '3', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708850');

-- BET593 CASH OUT
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100708848', 407925, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '3', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708848');

-- PEGA3 — CASH IN
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100713848', 407827, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713848');

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100713850', 407827, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713850');

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100708852', 407827, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708852');

-- PEGA3 — PREMIOS (CASH IN)
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100708858', 407827, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708858');

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100708860', 407827, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708860');

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100708862', 407827, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708862');

-- TRADICIONALES — CASH IN
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100713842', 407827, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713842');

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100713844', 407827, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713844');

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100713846', 407827, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713846');

-- TRADICIONALES — PREMIOS (CASH IN)
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100708854', 407827, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708854');

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100708855', 407827, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708855');

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT SEQ_AD_SERVICIO_PARAMETROS.NEXTVAL, '100708856', 407827, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708856');

-- ============================================================
-- AD_CANAL_SERVICIO — asocia cada config con canal POS (CODIGO_CANAL=1)
-- MIN(ID_CONFIG) garantiza una sola fila aunque existan duplicados.
-- ============================================================

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713841') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708846') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708850') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708848') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713848') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713850') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708852') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708858') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708860') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708862') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713842') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713844') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713846') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708854') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708855') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_CANAL_SERVICIO.NEXTVAL FROM DUAL),
       1, sp.ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708856') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_CANAL_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND CODIGO_CANAL = 1);

-- ============================================================
-- AD_COM_FORMPAG_SERVICIO — forma de pago por servicio
-- COD_FORMA_PAGO = 1 (EFECTIVO) para todos
-- ============================================================

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713841') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708846') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708850') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708848') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713848') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713850') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708852') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708858') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708860') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708862') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713842') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713844') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713846') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708854') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708855') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_COM_FORMPAG_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708856') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_COM_FORMPAG_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND COD_FORMA_PAGO = 1);

-- ============================================================
-- AD_ITEM_SERVICIO — parámetros internos del WS (no son campos de UI)
-- Solo ECUABET CI requiere numero_tarjeta y tipo_servicio.
-- ECUABET CO y BET593 CI llevan solo numero_tarjeta.
-- ============================================================

INSERT INTO AD_ITEM_SERVICIO
    (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_ITEM_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 'numero_tarjeta', '7777771111111110', 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713841') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_ITEM_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND TAG = 'numero_tarjeta');

INSERT INTO AD_ITEM_SERVICIO
    (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_ITEM_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 'tipo_servicio', '02', 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713841') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_ITEM_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND TAG = 'tipo_servicio');

INSERT INTO AD_ITEM_SERVICIO
    (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_ITEM_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 'numero_tarjeta', '7777771111111110', 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708846') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_ITEM_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND TAG = 'numero_tarjeta');

INSERT INTO AD_ITEM_SERVICIO
    (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT SEQ_AD_ITEM_SERVICIO.NEXTVAL FROM DUAL),
       sp.ID_CONFIG, 'numero_tarjeta', '7777771111111110', 'GPF_OMNISTACK', SYSDATE, 'S'
FROM (SELECT MIN(ID_CONFIG) AS ID_CONFIG FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708850') sp
WHERE sp.ID_CONFIG IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM AD_ITEM_SERVICIO WHERE ID_CONFIG = sp.ID_CONFIG AND TAG = 'numero_tarjeta');

COMMIT;
