-- ============================================================
-- Ejecutar como: GPF_OMNISTACK
-- docker exec -it oracle-oracle-1 sqlplus GPF_OMNISTACK/F4P_xmtyT_C1MpT@XEPDB1
-- TERCERO = service_provider_code:
--   1 = Ecuabet        (items 100713841 CASH_IN, 100708846 CASH_OUT, subcategory=1)
--   2 = Loteria BET593 (items 100708850 CASH_IN, 100708848 CASH_OUT, subcategory=1)
-- NOTA: Pega3 (20001565830) y Tradicionales (10001565830) excluidos — no existen en ITEM_MASTER de QA
-- CODIGO_CANAL = 1 representa el canal POS (TUKUNAFUNC.AD_CANAL CODIGO='POS')
-- IDs generados con MAX(PK)+1 para no colisionar con registros existentes
-- ============================================================
SET SQLBLANKLINES ON

-- --------------------------------------------------------
-- AD_SERVICIO_PARAMETROS
-- --------------------------------------------------------
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100713841', 1, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de manera expresa el registro y uso de mis datos personales para la creacion de mi cuenta en ECUA BET.',
    '10', '3', '2', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100708846', 1, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de manera expresa el registro y uso de mis datos personales para la creacion de mi cuenta en ECUA BET.',
    '10', '3', '3', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100708850', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '3', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100708848', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '3', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

-- BOLETOS LN — CASH_IN (Tradicionales: Loteria, Lotto, Pozzo)
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100713842', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100713844', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100713846', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

-- BOLETOS LN — CASH_IN (Pega3: Pega4, Pega2, Pega3)
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100713848', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100713850', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100708852', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

-- BOLETOS LN — CASH_OUT / PREMIOS (Tradicionales: Loteria, Lotto, Pozzo)
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100708854', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100708855', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100708856', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

-- BOLETOS LN — CASH_OUT / PREMIOS (Pega3: Pega4, Pega2, Pega3)
INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100708858', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100708860', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

INSERT INTO AD_SERVICIO_PARAMETROS
    (ID_CONFIG, CODIGO_ITEM_RMS, TERCERO, FLG_PAGO_MIXTO, FLG_ITEM, FLG_DEVOLUCION,
     MONTO_MIN, MONTO_MAX, REQUIERE_CONSENTIMIENTO, TEXTO_CONSENTIMIENTO,
     TIMEOUT_WS_MAX, RETRIES_WS_MAX, NUM_TICKETS, USUARIO_REGISTRO, FECHA_REGISTRO)
SELECT NVL(MAX(ID_CONFIG),0)+1, '100708862', 2, 'N', 'RECA', 'N', 1, 200, 'S',
    'Autorizo de forma expresa el uso de mis datos para acceder a los servicios digitales de Loteria Nacional.',
    '10', '3', '1', 'GPF_OMNISTACK', SYSDATE
FROM AD_SERVICIO_PARAMETROS;

-- --------------------------------------------------------
-- AD_CANAL_SERVICIO — asocia cada config con canal POS (CODIGO_CANAL=1)
-- ID_CONFIG resuelto por CODIGO_ITEM_RMS para no depender de valores hardcodeados
-- --------------------------------------------------------
INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713841';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708846';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708850';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708848';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713842';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713844';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713846';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713848';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713850';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708852';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708854';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708855';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708856';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708858';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708860';

INSERT INTO AD_CANAL_SERVICIO
    (COD_CAN_SERV, CODIGO_CANAL, ID_CONFIG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_CAN_SERV),0)+1 FROM AD_CANAL_SERVICIO),
       1, ID_CONFIG, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708862';

-- --------------------------------------------------------
-- AD_COM_FORMPAG_SERVICIO — forma de pago por servicio
-- --------------------------------------------------------
INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713841';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708846';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708850';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708848';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713842';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713844';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713846';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713848';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713850';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708852';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708854';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708855';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708856';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708858';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708860';

INSERT INTO AD_COM_FORMPAG_SERVICIO
    (COD_COM_FORMPAG_SERV, ID_CONFIG, COMISION, COD_FORMA_PAGO, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_COM_FORMPAG_SERV),0)+1 FROM AD_COM_FORMPAG_SERVICIO),
       ID_CONFIG, 0, 1, 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708862';

-- --------------------------------------------------------
-- AD_ITEM_SERVICIO — parametros internos del WS (no son campos de UI)
-- --------------------------------------------------------
INSERT INTO AD_ITEM_SERVICIO
    (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_ITEM_SERV),0)+1 FROM AD_ITEM_SERVICIO),
       ID_CONFIG, 'numero_tarjeta', '7777771111111110', 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713841';

INSERT INTO AD_ITEM_SERVICIO
    (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_ITEM_SERV),0)+1 FROM AD_ITEM_SERVICIO),
       ID_CONFIG, 'tipo_servicio', '02', 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100713841';

INSERT INTO AD_ITEM_SERVICIO
    (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_ITEM_SERV),0)+1 FROM AD_ITEM_SERVICIO),
       ID_CONFIG, 'numero_tarjeta', '7777771111111110', 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708846';

INSERT INTO AD_ITEM_SERVICIO
    (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG, USUARIO_REGISTRO, FECHA_REGISTRO, ACTIVO)
SELECT (SELECT NVL(MAX(COD_ITEM_SERV),0)+1 FROM AD_ITEM_SERVICIO),
       ID_CONFIG, 'numero_tarjeta', '7777771111111110', 'GPF_OMNISTACK', SYSDATE, 'S'
FROM AD_SERVICIO_PARAMETROS WHERE CODIGO_ITEM_RMS = '100708850';

COMMIT;
