-- ============================================================
-- Migración IN_OMNI_* de GPF_OMNISTACK → TUKUNAFUNC
-- (ejecutado y completado en Docker local XEPDB1)
--
-- PASO 1 (GPF_OMNISTACK): GRANT SELECT ON IN_OMNI_* TO TUKUNAFUNC
-- PASO 2 (TUKUNAFUNC):    CREATE TABLE + secuencias + INSERT...SELECT
-- PASO 3 (GPF_OMNISTACK): DROP TABLE + DROP SEQUENCE
-- ============================================================

-- == PASO 1 — como GPF_OMNISTACK ==
-- GRANT SELECT ON IN_OMNI_PROVEEDOR_CONFIG  TO TUKUNAFUNC;
-- GRANT SELECT ON IN_OMNI_PROVEEDOR_HEADERS TO TUKUNAFUNC;
-- GRANT SELECT ON IN_OMNI_PROVEEDOR_WS      TO TUKUNAFUNC;
-- GRANT SELECT ON IN_OMNI_PROVEEDOR_WS_DEFS TO TUKUNAFUNC;
-- GRANT SELECT ON IN_OMNI_LOGS_APP          TO TUKUNAFUNC;
-- GRANT SELECT ON IN_OMNI_LOGS_WS_EXT       TO TUKUNAFUNC;
-- GRANT SELECT ON IN_OMNI_REGISTRO_TRX      TO TUKUNAFUNC;

-- == PASO 2 — como TUKUNAFUNC (tablas) ==

CREATE TABLE IN_OMNI_PROVEEDOR_CONFIG (
    ID_CONFIG         NUMBER(12,0)   NOT NULL,
    PROVEEDOR_KEY     VARCHAR2(50)   NOT NULL,
    CONFIG_KEY        VARCHAR2(200)  NOT NULL,
    TIPO_CONFIG       VARCHAR2(50),
    CONFIG_VALOR      VARCHAR2(4000),
    USR_CREACION      VARCHAR2(100)  DEFAULT USER NOT NULL,
    FEC_CREACION      DATE           DEFAULT SYSDATE NOT NULL,
    USR_MODIFICACION  VARCHAR2(100),
    FEC_MODIFICACION  DATE,
    CONSTRAINT PK_IN_OMNI_PROVEEDOR_CONFIG    PRIMARY KEY (ID_CONFIG),
    CONSTRAINT UX_IN_OMNI_PROVEEDOR_CONFIG_01 UNIQUE (PROVEEDOR_KEY, CONFIG_KEY)
);

CREATE TABLE IN_OMNI_PROVEEDOR_HEADERS (
    ID_HEADER         NUMBER(12,0)   NOT NULL,
    PROVEEDOR_KEY     VARCHAR2(50)   NOT NULL,
    HEADER_NOMBRE     VARCHAR2(200)  NOT NULL,
    HEADER_VALOR      VARCHAR2(2000) NOT NULL,
    USR_CREACION      VARCHAR2(100)  DEFAULT USER NOT NULL,
    FEC_CREACION      DATE           DEFAULT SYSDATE NOT NULL,
    USR_MODIFICACION  VARCHAR2(100),
    FEC_MODIFICACION  DATE,
    CONSTRAINT PK_IN_OMNI_PROVEEDOR_HEADERS PRIMARY KEY (ID_HEADER)
);

CREATE TABLE IN_OMNI_PROVEEDOR_WS (
    ID_WS             NUMBER(12,0)  NOT NULL,
    PROVEEDOR_KEY     VARCHAR2(50)  NOT NULL,
    WS_KEY            VARCHAR2(120) NOT NULL,
    ENABLED           CHAR(1)       DEFAULT 'S' NOT NULL,
    TIPO_CONEXION     VARCHAR2(30)  NOT NULL,
    METODO_HTTP       VARCHAR2(10)  NOT NULL,
    TIPO_REQUEST      VARCHAR2(30)  NOT NULL,
    URL               VARCHAR2(500) NOT NULL,
    NOMBRE_OPERACION  VARCHAR2(200),
    USR_CREACION      VARCHAR2(100) DEFAULT USER NOT NULL,
    FEC_CREACION      DATE          DEFAULT SYSDATE NOT NULL,
    USR_MODIFICACION  VARCHAR2(100),
    FEC_MODIFICACION  DATE,
    CONSTRAINT CK_IN_OMNI_PROVEEDOR_WS_ENA CHECK (ENABLED IN ('S','N')),
    CONSTRAINT CK_IN_OMNI_PROVEEDOR_WS_MET CHECK (UPPER(METODO_HTTP) IN ('GET','POST','PUT','PATCH','DELETE')),
    CONSTRAINT PK_IN_OMNI_PROVEEDOR_WS PRIMARY KEY (ID_WS)
);

CREATE TABLE IN_OMNI_PROVEEDOR_WS_DEFS (
    ID_DEFAULT          NUMBER(12,0)   NOT NULL,
    ID_WS               NUMBER(12,0)   NOT NULL,
    TIPO_DEF            VARCHAR2(100),
    DEFAULT_CLAVE       VARCHAR2(200)  NOT NULL,
    DEFAULT_VALOR_TEXT  VARCHAR2(4000),
    DEFAULT_VALOR_NUM   NUMBER(18,6),
    DEFAULT_VALOR_DATE  DATE,
    USR_CREACION        VARCHAR2(100)  DEFAULT USER NOT NULL,
    FEC_CREACION        DATE           DEFAULT SYSDATE NOT NULL,
    USR_MODIFICACION    VARCHAR2(100),
    FEC_MODIFICACION    DATE,
    CONSTRAINT PK_IN_OMNI_PROVEEDOR_WS_DEFS PRIMARY KEY (ID_DEFAULT),
    CONSTRAINT FK_IN_OMNI_WS_DEFS_WS FOREIGN KEY (ID_WS)
        REFERENCES IN_OMNI_PROVEEDOR_WS(ID_WS)
);

CREATE TABLE IN_OMNI_LOGS_APP (
    CODIGO          NUMBER(18,0)   NOT NULL,
    UUID            VARCHAR2(200),
    REQUEST         CLOB,
    RESPONSE        CLOB,
    USUARIO         VARCHAR2(100),
    FECHA_REGISTRO  DATE,
    MENSAJE         VARCHAR2(2000),
    PROVEEDOR       VARCHAR2(100),
    CAPABILITY      VARCHAR2(50),
    CANAL           VARCHAR2(50),
    CADENA          NUMBER(10,0),
    FARMACIA        NUMBER(10,0),
    NOMBRE_FARMACIA VARCHAR2(200),
    POS             VARCHAR2(20),
    URL             VARCHAR2(500),
    METODO          VARCHAR2(20),
    HTTP_STATUS     NUMBER(5,0),
    ES_ERROR        CHAR(1),
    COD_ERROR       VARCHAR2(200),
    MSG_ERROR       VARCHAR2(2000),
    CP_VAR1         VARCHAR2(1500),
    CP_VAR2         VARCHAR2(1500),
    CP_VAR3         VARCHAR2(1500),
    CP_NUMBER1      NUMBER,
    CP_NUMBER2      NUMBER,
    CP_DATE1        DATE,
    CP_DATE2        DATE,
    CONSTRAINT CK_IN_OMNI_LOGS_APP_ERR CHECK (ES_ERROR IN ('S','N')),
    CONSTRAINT PK_IN_OMNI_LOGS_APP PRIMARY KEY (CODIGO)
);

CREATE TABLE IN_OMNI_LOGS_WS_EXT (
    CODIGO          NUMBER(18,0)   NOT NULL,
    UUID            VARCHAR2(200),
    REQUEST         CLOB,
    RESPONSE        CLOB,
    USUARIO         VARCHAR2(100),
    FECHA_REGISTRO  DATE,
    MENSAJE         VARCHAR2(2000),
    PROVEEDOR       VARCHAR2(100),
    WS_KEY          VARCHAR2(120),
    CANAL           VARCHAR2(50),
    CADENA          NUMBER(10,0),
    FARMACIA        NUMBER(10,0),
    POS             VARCHAR2(20),
    URL             VARCHAR2(500),
    METODO          VARCHAR2(20),
    HTTP_STATUS     NUMBER(5,0),
    DURACION_MS     NUMBER(10,0),
    ES_ERROR        CHAR(1),
    CP_VAR1         VARCHAR2(1500),
    CP_VAR2         VARCHAR2(1500),
    CP_DATE1        DATE,
    CONSTRAINT CK_IN_OMNI_LOGS_WS_EXT_ERR CHECK (ES_ERROR IN ('S','N')),
    CONSTRAINT PK_IN_OMNI_LOGS_WS_EXT PRIMARY KEY (CODIGO)
);

CREATE TABLE IN_OMNI_REGISTRO_TRX (
    CODIGO                  NUMBER(18,0)   NOT NULL,
    UUID                    VARCHAR2(200),
    CADENA                  NUMBER(10,0),
    FARMACIA                NUMBER(10,0),
    NOMBRE_FARMACIA         VARCHAR2(200),
    POS                     VARCHAR2(20),
    FECHA_REGISTRO          DATE,
    FECHA_AUTORIZACION_PROV DATE,
    CANAL                   VARCHAR2(50),
    PROVEEDOR               VARCHAR2(100),
    CATEGORY_CODE           VARCHAR2(20),
    SUBCATEGORY_CODE        VARCHAR2(20),
    SERVICE_PROVIDER_CODE   VARCHAR2(20),
    RMS_ITEM_CODE           VARCHAR2(100),
    CAPABILITY              VARCHAR2(50),
    ID_EXTERNO              VARCHAR2(200),
    AUTHORIZATION           VARCHAR2(200),
    MONTO                   NUMBER(18,2),
    MONEDA                  VARCHAR2(10)   DEFAULT 'USD',
    COD_ESTADO              VARCHAR2(20),
    ES_ERROR                CHAR(1),
    COD_ERROR               VARCHAR2(200),
    MSG_ERROR               VARCHAR2(2000),
    CP_VAR1                 VARCHAR2(1500),
    CP_VAR2                 VARCHAR2(1500),
    CP_VAR3                 VARCHAR2(1500),
    CP_NUMBER1              NUMBER,
    CP_DATE1                DATE,
    CONSTRAINT CK_IN_OMNI_REGISTRO_TRX_ERR CHECK (ES_ERROR IN ('S','N')),
    CONSTRAINT CK_IN_OMNI_REGISTRO_TRX_MON CHECK (MONEDA IS NULL OR LENGTH(MONEDA) <= 10),
    CONSTRAINT PK_IN_OMNI_REGISTRO_TRX PRIMARY KEY (CODIGO)
);

-- Migrar datos
INSERT INTO IN_OMNI_PROVEEDOR_CONFIG  SELECT * FROM GPF_OMNISTACK.IN_OMNI_PROVEEDOR_CONFIG;
INSERT INTO IN_OMNI_PROVEEDOR_HEADERS SELECT * FROM GPF_OMNISTACK.IN_OMNI_PROVEEDOR_HEADERS;
INSERT INTO IN_OMNI_PROVEEDOR_WS      SELECT * FROM GPF_OMNISTACK.IN_OMNI_PROVEEDOR_WS;
INSERT INTO IN_OMNI_PROVEEDOR_WS_DEFS SELECT * FROM GPF_OMNISTACK.IN_OMNI_PROVEEDOR_WS_DEFS;
INSERT INTO IN_OMNI_LOGS_APP          SELECT * FROM GPF_OMNISTACK.IN_OMNI_LOGS_APP;
INSERT INTO IN_OMNI_LOGS_WS_EXT       SELECT * FROM GPF_OMNISTACK.IN_OMNI_LOGS_WS_EXT;
INSERT INTO IN_OMNI_REGISTRO_TRX      SELECT * FROM GPF_OMNISTACK.IN_OMNI_REGISTRO_TRX;
COMMIT;

-- Secuencias (START WITH = LAST_NUMBER original en GPF_OMNISTACK)
CREATE SEQUENCE SEQ_IN_OMNI_PROVEEDOR_CONFIG  START WITH 70   INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_IN_OMNI_PROVEEDOR_HEADERS START WITH 11   INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_IN_OMNI_PROVEEDOR_WS      START WITH 33   INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_IN_OMNI_PROVEEDOR_WS_DEFS START WITH 56   INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_IN_OMNI_LOGS_APP          START WITH 2001 INCREMENT BY 1 MINVALUE 1 CACHE 500 NOCYCLE;
CREATE SEQUENCE SEQ_IN_OMNI_LOGS_WS_EXT       START WITH 2501 INCREMENT BY 1 MINVALUE 1 CACHE 500 NOCYCLE;
CREATE SEQUENCE SEQ_IN_OMNI_REGISTRO_TRX      START WITH 21   INCREMENT BY 1 MINVALUE 1 CACHE 20  NOCYCLE;

-- == PASO 3 — como GPF_OMNISTACK (eliminar) ==
-- DROP TABLE IN_OMNI_PROVEEDOR_WS_DEFS;
-- DROP TABLE IN_OMNI_PROVEEDOR_WS;
-- DROP TABLE IN_OMNI_PROVEEDOR_CONFIG;
-- DROP TABLE IN_OMNI_PROVEEDOR_HEADERS;
-- DROP TABLE IN_OMNI_LOGS_APP;
-- DROP TABLE IN_OMNI_LOGS_WS_EXT;
-- DROP TABLE IN_OMNI_REGISTRO_TRX;
-- DROP SEQUENCE SEQ_IN_OMNI_PROVEEDOR_CONFIG;
-- DROP SEQUENCE SEQ_IN_OMNI_PROVEEDOR_HEADERS;
-- DROP SEQUENCE SEQ_IN_OMNI_PROVEEDOR_WS;
-- DROP SEQUENCE SEQ_IN_OMNI_PROVEEDOR_WS_DEFS;
-- DROP SEQUENCE SEQ_IN_OMNI_LOGS_APP;
-- DROP SEQUENCE SEQ_IN_OMNI_LOGS_WS_EXT;
-- DROP SEQUENCE SEQ_IN_OMNI_REGISTRO_TRX;
