UPDATE ${schema}.IN_OMNI_CASHOUT_CUPO_DIARIO
SET ESTADO = 'CONFIRMADO',
    FECHA_CONFIRMACION = SYSTIMESTAMP,
    USR_MODIFICACION = USER,
    FEC_MODIFICACION = SYSDATE
WHERE UUID = :uuid
  AND ESTADO = 'RESERVADO'
