UPDATE ${schema}.IN_OMNI_CASHOUT_CUPO_DIARIO
SET ESTADO = 'EXPIRADO',
    FECHA_EXPIRACION = SYSTIMESTAMP,
    USR_MODIFICACION = USER,
    FEC_MODIFICACION = SYSDATE
WHERE ESTADO = 'RESERVADO'
  AND FECHA_RESERVA < :cutoffTimestamp
