SELECT ID_CUPO, UUID, CADENA, FARMACIA, POS, RMS_ITEM_CODE, SERVICE_PROVIDER_CODE,
       MONTO, ESTADO, FECHA_OPERACION, FECHA_RESERVA, FECHA_CONFIRMACION,
       FECHA_EXPIRACION, FECHA_REVERSION
FROM ${schema}.IN_OMNI_CASHOUT_CUPO_DIARIO
WHERE UUID = :uuid
