SELECT NVL(SUM(MONTO), 0) AS consumed
FROM ${schema}.IN_OMNI_CASHOUT_CUPO_DIARIO
WHERE CADENA = :cadena
  AND FARMACIA = :farmacia
  AND RMS_ITEM_CODE = :rmsItemCode
  AND FECHA_OPERACION = :fechaOperacion
  AND ESTADO IN ('RESERVADO', 'CONFIRMADO')
