UPDATE ${schema}.IN_OMNI_CASHOUT_CUPO_DIARIO
SET ESTADO = 'REVERTIDO',
    FECHA_REVERSION = SYSTIMESTAMP,
    USR_MODIFICACION = USER,
    FEC_MODIFICACION = SYSDATE
WHERE UUID = :uuid
  AND ESTADO IN ('RESERVADO', 'CONFIRMADO')
  AND FECHA_OPERACION = :fechaOperacion
