-- ============================================================
-- DDL: Tablas catálogo OmniStack en schema TUKUNAFUNC
-- Target: Oracle XEPDB1 (local dev) / PRS6 (prod)
-- Ejecutar como: TUKUNAFUNC (o sysdba con ALTER SESSION SET CONTAINER=XEPDB1)
-- ============================================================
SET SQLBLANKLINES ON
SET DEFINE OFF

-- ============================================================
-- AD_CANAL
-- ============================================================
CREATE TABLE AD_CANAL (
  CODIGO     VARCHAR2(20)  NOT NULL,
  DESCRIPCION VARCHAR2(100),
  ACTIVO     NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT AD_CANAL_PK PRIMARY KEY (CODIGO)
);

-- ============================================================
-- AD_CATEGORIA_SUBCATEGORIA
-- Alimenta: sql/business-lines/oracle/category-subcategory.sql
-- ============================================================
CREATE SEQUENCE SEQ_AD_CAT_SUBCAT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE AD_CATEGORIA_SUBCATEGORIA (
  ID               NUMBER        NOT NULL,
  CHAIN            VARCHAR2(10),
  STORE            VARCHAR2(10),
  STORE_NAME       VARCHAR2(100),
  POS              VARCHAR2(10),
  CHANNEL_POS      VARCHAR2(20)  NOT NULL,
  CATEGORY_CODE    VARCHAR2(10)  NOT NULL,
  CATEGORY_NAME    VARCHAR2(100),
  SUBCATEGORY_CODE VARCHAR2(10)  NOT NULL,
  SUBCATEGORY_NAME VARCHAR2(100),
  IS_ACTIVE        NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT AD_CAT_SUBCAT_PK PRIMARY KEY (ID),
  CONSTRAINT AD_CAT_SUBCAT_UK UNIQUE (CHANNEL_POS, CATEGORY_CODE, SUBCATEGORY_CODE)
);

CREATE OR REPLACE TRIGGER TRG_AD_CAT_SUBCAT_BI
  BEFORE INSERT ON AD_CATEGORIA_SUBCATEGORIA
  FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := SEQ_AD_CAT_SUBCAT.NEXTVAL;
END;
/

-- ============================================================
-- AD_PROVEEDOR_SERVICIO
-- Alimenta: sql/business-lines/oracle/service-providers.sql
-- ============================================================
CREATE SEQUENCE SEQ_AD_PROV_SERV START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE AD_PROVEEDOR_SERVICIO (
  ID                   NUMBER        NOT NULL,
  CHAIN                VARCHAR2(10),
  STORE                VARCHAR2(10),
  STORE_NAME           VARCHAR2(100),
  POS                  VARCHAR2(10),
  CHANNEL_POS          VARCHAR2(20)  NOT NULL,
  CATEGORY_CODE        VARCHAR2(10)  NOT NULL,
  SUBCATEGORY_CODE     VARCHAR2(10)  NOT NULL,
  SERVICE_PROVIDER_CODE VARCHAR2(10) NOT NULL,
  RUC_PROVIDER         VARCHAR2(20),
  PROVIDER_NAME        VARCHAR2(100),
  IS_ACTIVE            NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT AD_PROV_SERV_PK PRIMARY KEY (ID),
  CONSTRAINT AD_PROV_SERV_UK UNIQUE (CHANNEL_POS, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE)
);

CREATE OR REPLACE TRIGGER TRG_AD_PROV_SERV_BI
  BEFORE INSERT ON AD_PROVEEDOR_SERVICIO
  FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := SEQ_AD_PROV_SERV.NEXTVAL;
END;
/

-- ============================================================
-- AD_SERVICIO_PARAMETROS_TMP
-- Alimenta: sql/business-lines/oracle/services.sql
-- ============================================================
CREATE SEQUENCE SEQ_AD_SERV_PARAM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE AD_SERVICIO_PARAMETROS_TMP (
  ID                   NUMBER        NOT NULL,
  CHAIN                VARCHAR2(10),
  STORE                VARCHAR2(10),
  STORE_NAME           VARCHAR2(100),
  POS                  VARCHAR2(10),
  CHANNEL_POS          VARCHAR2(20)  NOT NULL,
  CATEGORY_CODE        VARCHAR2(10)  NOT NULL,
  SUBCATEGORY_CODE     VARCHAR2(10)  NOT NULL,
  SERVICE_PROVIDER_CODE VARCHAR2(10) NOT NULL,
  RMS_ITEM_CODE        VARCHAR2(20)  NOT NULL,
  DESCRIPTION          VARCHAR2(200),
  IS_ACTIVE            NUMBER(1)     DEFAULT 1 NOT NULL,
  JDE_CODE             VARCHAR2(20),
  MOVEMENT_TYPE        VARCHAR2(20),
  IS_MIXED_PAYMENT     NUMBER(1)     DEFAULT 0,
  FLG_ITEM             VARCHAR2(10),
  IS_REFUND            NUMBER(1)     DEFAULT 0,
  MIN_AMOUNT           VARCHAR2(20),
  MAX_AMOUNT           VARCHAR2(20),
  TIMEOUT_WS_MAX       VARCHAR2(10),
  RETRIES_WS_MAX       VARCHAR2(10),
  NUM_TICKETS          VARCHAR2(10)  DEFAULT '3',
  REQUIRES_CONSENT     NUMBER(1)     DEFAULT 0,
  CONSENT_TEXT         CLOB,
  CONSTRAINT AD_SERV_PARAM_PK PRIMARY KEY (ID),
  CONSTRAINT AD_SERV_PARAM_UK UNIQUE (CHANNEL_POS, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE)
);

CREATE OR REPLACE TRIGGER TRG_AD_SERV_PARAM_BI
  BEFORE INSERT ON AD_SERVICIO_PARAMETROS_TMP
  FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := SEQ_AD_SERV_PARAM.NEXTVAL;
END;
/

-- ============================================================
-- AD_CAP_SERVICIO
-- Alimenta: sql/business-lines/oracle/capabilities.sql
-- ============================================================
CREATE SEQUENCE SEQ_AD_CAP_SERV START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE AD_CAP_SERVICIO (
  ID                   NUMBER        NOT NULL,
  CHAIN                VARCHAR2(10),
  STORE                VARCHAR2(10),
  STORE_NAME           VARCHAR2(100),
  POS                  VARCHAR2(10),
  CHANNEL_POS          VARCHAR2(20)  NOT NULL,
  CATEGORY_CODE        VARCHAR2(10)  NOT NULL,
  SUBCATEGORY_CODE     VARCHAR2(10)  NOT NULL,
  SERVICE_PROVIDER_CODE VARCHAR2(10) NOT NULL,
  RMS_ITEM_CODE        VARCHAR2(20)  NOT NULL,
  CAPABILITY_CODE      VARCHAR2(30)  NOT NULL,
  CONSTRAINT AD_CAP_SERV_PK PRIMARY KEY (ID),
  CONSTRAINT AD_CAP_SERV_UK UNIQUE (CHANNEL_POS, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE, CAPABILITY_CODE)
);

CREATE OR REPLACE TRIGGER TRG_AD_CAP_SERV_BI
  BEFORE INSERT ON AD_CAP_SERVICIO
  FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := SEQ_AD_CAP_SERV.NEXTVAL;
END;
/

-- ============================================================
-- AD_ITEM_SERVICIO_TMP
-- Alimenta: sql/business-lines/oracle/input-fields.sql
-- ============================================================
CREATE SEQUENCE SEQ_AD_ITEM_SERV START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE AD_ITEM_SERVICIO_TMP (
  ID                   NUMBER        NOT NULL,
  CHAIN                VARCHAR2(10),
  STORE                VARCHAR2(10),
  STORE_NAME           VARCHAR2(100),
  POS                  VARCHAR2(10),
  CHANNEL_POS          VARCHAR2(20)  NOT NULL,
  CATEGORY_CODE        VARCHAR2(10)  NOT NULL,
  SUBCATEGORY_CODE     VARCHAR2(10)  NOT NULL,
  SERVICE_PROVIDER_CODE VARCHAR2(10) NOT NULL,
  RMS_ITEM_CODE        VARCHAR2(20)  NOT NULL,
  INPUT_FIELD_ID       VARCHAR2(50)  NOT NULL,
  LABEL                VARCHAR2(100),
  FIELD_TYPE           VARCHAR2(20),
  CAPABILITY_CODE      VARCHAR2(30),
  IS_REQUIRED          NUMBER(1)     DEFAULT 0,
  FIELD_GROUP          VARCHAR2(50),
  CONDITIONAL_OPERATOR VARCHAR2(10),
  CONSTRAINT AD_ITEM_SERV_PK PRIMARY KEY (ID)
);

CREATE OR REPLACE TRIGGER TRG_AD_ITEM_SERV_BI
  BEFORE INSERT ON AD_ITEM_SERVICIO_TMP
  FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := SEQ_AD_ITEM_SERV.NEXTVAL;
END;
/

-- ============================================================
-- AD_COM_FORMPAG_SERVICIO
-- Alimenta: sql/business-lines/oracle/payment-methods.sql
-- ============================================================
CREATE SEQUENCE SEQ_AD_COM_FORMPAG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE AD_COM_FORMPAG_SERVICIO (
  ID                      NUMBER        NOT NULL,
  CHAIN                   VARCHAR2(10),
  STORE                   VARCHAR2(10),
  STORE_NAME              VARCHAR2(100),
  POS                     VARCHAR2(10),
  CHANNEL_POS             VARCHAR2(20)  NOT NULL,
  CATEGORY_CODE           VARCHAR2(10)  NOT NULL,
  SUBCATEGORY_CODE        VARCHAR2(10)  NOT NULL,
  SERVICE_PROVIDER_CODE   VARCHAR2(10)  NOT NULL,
  RMS_ITEM_CODE           VARCHAR2(20)  NOT NULL,
  SERVICE_PAYMENT_METHOD_ID NUMBER       NOT NULL,
  PAYMENT_METHOD_CODE     VARCHAR2(30),
  IS_ACTIVE               NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT AD_COM_FORMPAG_PK PRIMARY KEY (ID),
  CONSTRAINT AD_COM_FORMPAG_UK UNIQUE (CHANNEL_POS, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE, SERVICE_PAYMENT_METHOD_ID)
);

CREATE OR REPLACE TRIGGER TRG_AD_COM_FORMPAG_BI
  BEFORE INSERT ON AD_COM_FORMPAG_SERVICIO
  FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := SEQ_AD_COM_FORMPAG.NEXTVAL;
END;
/

COMMIT;
