/* ============================================================
   ESQUEMA : TUKUNAFUNC
   SERVIDOR: gpfvmcluts2.gfybeca.int:1521 / PRS6.UIO  (HPROD)
   PROYECTO : OmniStack
   OBJETIVO : Crear tablas de configuracion de proveedores y
              trazabilidad de transacciones.

   PREFIJO  : IN_OMNI_  (evita colision con tablas IN_ del proyecto
              anterior que comparten el mismo esquema TUKUNAFUNC)

   TABLAS CREADAS
   ---------------------------------------------------------------
   IN_OMNI_PROVEEDOR_WS       catalogo de endpoints por proveedor
   IN_OMNI_PROVEEDOR_HEADERS  headers HTTP por proveedor
   IN_OMNI_PROVEEDOR_WS_DEFS  valores por defecto por WS
   IN_OMNI_LOGS_APP           log de nivel aplicacion OmniStack
   IN_OMNI_LOGS_WS_EXT        log de llamadas a WS externos
   IN_OMNI_REGISTRO_TRX       registro de transacciones completadas
   ============================================================ */

---------------------------------------------------------------
-- 1) TABLA: IN_OMNI_PROVEEDOR_WS
--    Catalogo de endpoints por proveedor. Reemplaza la config
--    app.integration.providers.<key>.services.*.* en
--    application.properties.
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS (
  ID_WS             NUMBER(12)     NOT NULL,
  PROVEEDOR_KEY     VARCHAR2(50)   NOT NULL, -- ecuabet | loteria | pega3 | tradicional | claro
  WS_KEY            VARCHAR2(120)  NOT NULL, -- PRECHECK.CASHIN | EXECUTE.CASHOUT | LOGIN ...
  ENABLED           CHAR(1)        DEFAULT 'S' NOT NULL,
  TIPO_CONEXION     VARCHAR2(30)   NOT NULL, -- REST | SOAP
  METODO_HTTP       VARCHAR2(10)   NOT NULL, -- GET | POST | PUT | DELETE
  TIPO_REQUEST      VARCHAR2(30)   NOT NULL, -- JSON | XML | FORM
  URL               VARCHAR2(500)  NOT NULL, -- URL completa (base_url + path)
  NOMBRE_OPERACION  VARCHAR2(200),           -- nombre logico de la operacion
  USR_CREACION      VARCHAR2(100)  DEFAULT USER    NOT NULL,
  FEC_CREACION      DATE           DEFAULT SYSDATE NOT NULL,
  USR_MODIFICACION  VARCHAR2(100),
  FEC_MODIFICACION  DATE,

  CONSTRAINT PK_IN_OMNI_PROVEEDOR_WS
    PRIMARY KEY (ID_WS),
  CONSTRAINT CK_IN_OMNI_PROVEEDOR_WS_ENA
    CHECK (ENABLED IN ('S','N')),
  CONSTRAINT CK_IN_OMNI_PROVEEDOR_WS_MET
    CHECK (UPPER(METODO_HTTP) IN ('GET','POST','PUT','PATCH','DELETE'))
);

CREATE UNIQUE INDEX TUKUNAFUNC.UX_IN_OMNI_PROVEEDOR_WS_01
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS (PROVEEDOR_KEY, WS_KEY);

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_PROVEEDOR_WS_01
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS (PROVEEDOR_KEY);

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_PROVEEDOR_WS_02
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS (ENABLED, PROVEEDOR_KEY);

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS IS 'Catalogo de endpoints (WS) por proveedor OmniStack.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS.PROVEEDOR_KEY    IS 'Clave interna del proveedor: ecuabet, loteria, pega3, tradicional, claro.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS.WS_KEY           IS 'Clave de la operacion: PRECHECK.CASHIN, EXECUTE.CASHOUT, LOGIN, etc.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS.URL              IS 'URL completa del WS (base_url concatenado con path).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS.NOMBRE_OPERACION IS 'Nombre logico de la operacion (ej: DEPOSITO, RECARGA593, validateRechargeRetail).';

---------------------------------------------------------------
-- 2) TABLA: IN_OMNI_PROVEEDOR_HEADERS
--    Headers HTTP por proveedor. Aplican a todos los WS del
--    mismo proveedor.
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (
  ID_HEADER         NUMBER(12)     NOT NULL,
  PROVEEDOR_KEY     VARCHAR2(50)   NOT NULL,
  HEADER_NOMBRE     VARCHAR2(200)  NOT NULL,
  HEADER_VALOR      VARCHAR2(2000) NOT NULL,
  USR_CREACION      VARCHAR2(100)  DEFAULT USER    NOT NULL,
  FEC_CREACION      DATE           DEFAULT SYSDATE NOT NULL,
  USR_MODIFICACION  VARCHAR2(100),
  FEC_MODIFICACION  DATE,

  CONSTRAINT PK_IN_OMNI_PROVEEDOR_HEADERS
    PRIMARY KEY (ID_HEADER)
);

CREATE UNIQUE INDEX TUKUNAFUNC.UX_IN_OMNI_PROVEEDOR_HEADERS_01
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (PROVEEDOR_KEY, HEADER_NOMBRE);

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_PROVEEDOR_HEADERS_01
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (PROVEEDOR_KEY);

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS IS 'Headers HTTP por proveedor (aplican a todos sus WS).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS.PROVEEDOR_KEY IS 'Clave interna del proveedor.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS.HEADER_NOMBRE IS 'Nombre del header HTTP.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS.HEADER_VALOR  IS 'Valor del header HTTP.';

---------------------------------------------------------------
-- 3) TABLA: IN_OMNI_PROVEEDOR_WS_DEFS
--    Valores por defecto configurables por WS. Permite
--    parametrizar constantes especificas de cada operacion.
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (
  ID_DEFAULT         NUMBER(12)     NOT NULL,
  ID_WS              NUMBER(12)     NOT NULL,
  TIPO_DEF           VARCHAR2(100),              -- TEXTO | NUMERO | FECHA | OFFERID | CONFIG
  DEFAULT_CLAVE      VARCHAR2(200)  NOT NULL,    -- ej: company_id, offer_id, medio_id
  DEFAULT_VALOR_TEXT VARCHAR2(4000),
  DEFAULT_VALOR_NUM  NUMBER(18,6),
  DEFAULT_VALOR_DATE DATE,
  USR_CREACION       VARCHAR2(100)  DEFAULT USER    NOT NULL,
  FEC_CREACION       DATE           DEFAULT SYSDATE NOT NULL,
  USR_MODIFICACION   VARCHAR2(100),
  FEC_MODIFICACION   DATE,

  CONSTRAINT PK_IN_OMNI_PROVEEDOR_WS_DEFS
    PRIMARY KEY (ID_DEFAULT),
  CONSTRAINT FK_IN_OMNI_WS_DEFS_WS
    FOREIGN KEY (ID_WS)
    REFERENCES TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS (ID_WS)
);

CREATE UNIQUE INDEX TUKUNAFUNC.UX_IN_OMNI_PROVEEDOR_WS_DEFS_01
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, DEFAULT_CLAVE);

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_PROVEEDOR_WS_DEFS_01
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS);

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS IS 'Valores por defecto configurables por WS de proveedor.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS.TIPO_DEF           IS 'Tipo de valor: TEXTO, NUMERO, FECHA, OFFERID, CONFIG.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS.DEFAULT_CLAVE      IS 'Nombre del parametro (company_id, offer_id.rmsItemCode, etc.).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS.DEFAULT_VALOR_TEXT IS 'Valor por defecto en texto.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS.DEFAULT_VALOR_NUM  IS 'Valor por defecto numerico.';

---------------------------------------------------------------
-- 4) TABLA: IN_OMNI_LOGS_APP
--    Auditoria de nivel aplicacion: una fila por llamada al
--    API de OmniStack (antes de llamar al proveedor).
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_LOGS_APP (
  CODIGO             NUMBER(18)     NOT NULL,
  UUID               VARCHAR2(200),             -- uuid de la transaccion
  REQUEST            CLOB,                      -- request recibido (JSON)
  RESPONSE           CLOB,                      -- response enviado (JSON)
  USUARIO            VARCHAR2(100),             -- usuario tecnico
  FECHA_REGISTRO     DATE,
  MENSAJE            VARCHAR2(2000),
  PROVEEDOR          VARCHAR2(100),             -- ecuabet | loteria | pega3 | etc.
  CAPABILITY         VARCHAR2(50),              -- PRECHECK | EXECUTE | VERIFY | REVERSE
  CANAL              VARCHAR2(50),              -- POS | WEB | APP | CCT
  CADENA             NUMBER(10),
  FARMACIA           NUMBER(10),
  NOMBRE_FARMACIA    VARCHAR2(200),
  POS                VARCHAR2(20),
  URL                VARCHAR2(500),
  METODO             VARCHAR2(20),
  HTTP_STATUS        NUMBER(5),
  ES_ERROR           CHAR(1),
  COD_ERROR          VARCHAR2(200),
  MSG_ERROR          VARCHAR2(2000),
  CP_VAR1            VARCHAR2(1500),
  CP_VAR2            VARCHAR2(1500),
  CP_VAR3            VARCHAR2(1500),
  CP_NUMBER1         NUMBER,
  CP_NUMBER2         NUMBER,
  CP_DATE1           DATE,
  CP_DATE2           DATE,

  CONSTRAINT PK_IN_OMNI_LOGS_APP
    PRIMARY KEY (CODIGO),
  CONSTRAINT CK_IN_OMNI_LOGS_APP_ERR
    CHECK (ES_ERROR IN ('S','N'))
);

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_LOGS_APP
  START WITH 1 INCREMENT BY 1 CACHE 500 NOCYCLE;

CREATE OR REPLACE TRIGGER TUKUNAFUNC.TRG_IN_OMNI_LOGS_APP_BI
BEFORE INSERT ON TUKUNAFUNC.IN_OMNI_LOGS_APP
FOR EACH ROW
BEGIN
  IF :NEW.CODIGO IS NULL THEN
    SELECT TUKUNAFUNC.SEQ_IN_OMNI_LOGS_APP.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
  END IF;
  IF :NEW.FECHA_REGISTRO IS NULL THEN
    :NEW.FECHA_REGISTRO := SYSDATE;
  END IF;
END;
/

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_APP_UUID       ON TUKUNAFUNC.IN_OMNI_LOGS_APP (UUID);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_APP_FECHA      ON TUKUNAFUNC.IN_OMNI_LOGS_APP (FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_APP_PROV_FECHA ON TUKUNAFUNC.IN_OMNI_LOGS_APP (PROVEEDOR, FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_APP_CAP_FECHA  ON TUKUNAFUNC.IN_OMNI_LOGS_APP (CAPABILITY, FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_APP_CAD_FAR    ON TUKUNAFUNC.IN_OMNI_LOGS_APP (CADENA, FARMACIA, POS, FECHA_REGISTRO);

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_LOGS_APP IS 'Auditoria de llamadas al API OmniStack (nivel aplicacion).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_LOGS_APP.UUID       IS 'Identificador de transaccion propagado a todos los proveedores.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_LOGS_APP.CAPABILITY IS 'Capacidad ejecutada: PRECHECK, EXECUTE, VERIFY, REVERSE, CREATE_TICKET.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_LOGS_APP.ES_ERROR   IS 'S=error en la transaccion, N=exito.';

---------------------------------------------------------------
-- 5) TABLA: IN_OMNI_LOGS_WS_EXT
--    Log de llamadas HTTP salientes a WS de proveedores.
--    Una fila por request a un proveedor externo.
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT (
  CODIGO             NUMBER(18)     NOT NULL,
  UUID               VARCHAR2(200),
  REQUEST            CLOB,
  RESPONSE           CLOB,
  USUARIO            VARCHAR2(100),
  FECHA_REGISTRO     DATE,
  MENSAJE            VARCHAR2(2000),
  PROVEEDOR          VARCHAR2(100),
  WS_KEY             VARCHAR2(120),             -- clave del WS llamado
  CANAL              VARCHAR2(50),
  CADENA             NUMBER(10),
  FARMACIA           NUMBER(10),
  POS                VARCHAR2(20),
  URL                VARCHAR2(500),
  METODO             VARCHAR2(20),
  HTTP_STATUS        NUMBER(5),                 -- codigo HTTP de respuesta
  DURACION_MS        NUMBER(10),                -- duracion de la llamada en ms
  ES_ERROR           CHAR(1),
  CP_VAR1            VARCHAR2(1500),
  CP_VAR2            VARCHAR2(1500),
  CP_DATE1           DATE,

  CONSTRAINT PK_IN_OMNI_LOGS_WS_EXT
    PRIMARY KEY (CODIGO),
  CONSTRAINT CK_IN_OMNI_LOGS_WS_EXT_ERR
    CHECK (ES_ERROR IN ('S','N'))
);

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_LOGS_WS_EXT
  START WITH 1 INCREMENT BY 1 CACHE 500 NOCYCLE;

CREATE OR REPLACE TRIGGER TUKUNAFUNC.TRG_IN_OMNI_LOGS_WS_EXT_BI
BEFORE INSERT ON TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT
FOR EACH ROW
BEGIN
  IF :NEW.CODIGO IS NULL THEN
    SELECT TUKUNAFUNC.SEQ_IN_OMNI_LOGS_WS_EXT.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
  END IF;
  IF :NEW.FECHA_REGISTRO IS NULL THEN
    :NEW.FECHA_REGISTRO := SYSDATE;
  END IF;
END;
/

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_WS_EXT_UUID       ON TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT (UUID);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_WS_EXT_FECHA      ON TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT (FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_WS_EXT_PROV_FECHA ON TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT (PROVEEDOR, FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_WS_EXT_WS_FECHA   ON TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT (WS_KEY, FECHA_REGISTRO);

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT IS 'Log de llamadas HTTP salientes a WS de proveedores externos.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT.WS_KEY      IS 'Clave del WS llamado (PRECHECK.CASHIN, EXECUTE.CASHOUT, etc.).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT.HTTP_STATUS IS 'Codigo HTTP de respuesta del proveedor.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT.DURACION_MS IS 'Duracion de la llamada al proveedor en milisegundos.';

---------------------------------------------------------------
-- 6) TABLA: IN_OMNI_REGISTRO_TRX
--    Registro de transacciones OmniStack para conciliacion
--    y reporteria. Una fila por EXECUTE (transaccion cobrada).
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (
  CODIGO                    NUMBER(18)     NOT NULL,
  UUID                      VARCHAR2(200),
  CADENA                    NUMBER(10),
  FARMACIA                  NUMBER(10),
  NOMBRE_FARMACIA           VARCHAR2(200),
  POS                       VARCHAR2(20),
  FECHA_REGISTRO            DATE,
  FECHA_AUTORIZACION_PROV   DATE,
  CANAL                     VARCHAR2(50),
  PROVEEDOR                 VARCHAR2(100),
  CATEGORY_CODE             VARCHAR2(20),
  SUBCATEGORY_CODE          VARCHAR2(20),
  SERVICE_PROVIDER_CODE     VARCHAR2(20),
  RMS_ITEM_CODE             VARCHAR2(100),
  CAPABILITY                VARCHAR2(50),
  ID_EXTERNO                VARCHAR2(200),  -- ID del proveedor (recargaid, transactionId, etc.)
  AUTHORIZATION             VARCHAR2(200),  -- campo authorization del response OmniStack
  MONTO                     NUMBER(18,2),
  MONEDA                    VARCHAR2(10)   DEFAULT 'USD',
  COD_ESTADO                VARCHAR2(20),  -- OK | ERROR | PENDIENTE | REVERTIDO
  ES_ERROR                  CHAR(1),
  COD_ERROR                 VARCHAR2(200),
  MSG_ERROR                 VARCHAR2(2000),
  CP_VAR1                   VARCHAR2(1500),
  CP_VAR2                   VARCHAR2(1500),
  CP_VAR3                   VARCHAR2(1500),
  CP_NUMBER1                NUMBER,
  CP_DATE1                  DATE,

  CONSTRAINT PK_IN_OMNI_REGISTRO_TRX
    PRIMARY KEY (CODIGO),
  CONSTRAINT CK_IN_OMNI_REGISTRO_TRX_ERR
    CHECK (ES_ERROR IN ('S','N')),
  CONSTRAINT CK_IN_OMNI_REGISTRO_TRX_MON
    CHECK (MONEDA IS NULL OR LENGTH(MONEDA) <= 10)
);

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_REGISTRO_TRX
  START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;

CREATE OR REPLACE TRIGGER TUKUNAFUNC.TRG_IN_OMNI_REGISTRO_TRX_BI
BEFORE INSERT ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX
FOR EACH ROW
BEGIN
  IF :NEW.CODIGO IS NULL THEN
    SELECT TUKUNAFUNC.SEQ_IN_OMNI_REGISTRO_TRX.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
  END IF;
  IF :NEW.FECHA_REGISTRO IS NULL THEN
    :NEW.FECHA_REGISTRO := SYSDATE;
  END IF;
  IF :NEW.MONEDA IS NULL THEN
    :NEW.MONEDA := 'USD';
  END IF;
END;
/

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_REGISTRO_TRX_UUID    ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (UUID);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_REGISTRO_TRX_FECHA   ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_REGISTRO_TRX_IDEXT   ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (ID_EXTERNO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_REGISTRO_TRX_AUTH    ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (AUTHORIZATION);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_REGISTRO_TRX_PROV    ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (PROVEEDOR, CAPABILITY, FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_REGISTRO_TRX_CAD_FAR ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (CADENA, FARMACIA, POS, FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_REGISTRO_TRX_ESTADO  ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (COD_ESTADO, FECHA_REGISTRO);

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_REGISTRO_TRX IS 'Registro de transacciones OmniStack para conciliacion y reporteria.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_REGISTRO_TRX.UUID          IS 'Identificador unico de transaccion (propagado al proveedor).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_REGISTRO_TRX.ID_EXTERNO    IS 'ID del proveedor externo (recargaid, transactionId, gameTicketNumber, etc.).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_REGISTRO_TRX.AUTHORIZATION IS 'Campo authorization del response OmniStack.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_REGISTRO_TRX.COD_ESTADO    IS 'Estado: OK | ERROR | PENDIENTE | REVERTIDO.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_REGISTRO_TRX.CAPABILITY    IS 'Capacidad ejecutada: PRECHECK, EXECUTE, VERIFY, REVERSE, CREATE_TICKET.';

---------------------------------------------------------------
-- 7) SECUENCIAS para tablas de configuracion (llenadas por DML)
---------------------------------------------------------------
CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_HEADERS
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

---------------------------------------------------------------
-- 8) TRIGGERS para tablas de configuracion
---------------------------------------------------------------
CREATE OR REPLACE TRIGGER TUKUNAFUNC.TRG_IN_OMNI_PROVEEDOR_WS_BI
BEFORE INSERT ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
FOR EACH ROW
BEGIN
  IF :NEW.ID_WS IS NULL THEN
    SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO :NEW.ID_WS FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TUKUNAFUNC.TRG_IN_OMNI_PROVEEDOR_HEADERS_BI
BEFORE INSERT ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS
FOR EACH ROW
BEGIN
  IF :NEW.ID_HEADER IS NULL THEN
    SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL INTO :NEW.ID_HEADER FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TUKUNAFUNC.TRG_IN_OMNI_PROVEEDOR_WS_DEFS_BI
BEFORE INSERT ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS
FOR EACH ROW
BEGIN
  IF :NEW.ID_DEFAULT IS NULL THEN
    SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO :NEW.ID_DEFAULT FROM DUAL;
  END IF;
END;
/

---------------------------------------------------------------
-- 9) TABLA: IN_OMNI_PROVEEDOR_CONFIG
--    Configuracion funcional a nivel proveedor: credenciales,
--    canal, routing codes, geolocalizacion.
--    Reemplaza app.integration.providers.* en
--    application.properties eliminando env vars por proveedor.
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (
  ID_CONFIG        NUMBER(12)     NOT NULL,
  PROVEEDOR_KEY    VARCHAR2(50)   NOT NULL,  -- ecuabet | loteria | pega3 | tradicional | claro
  CONFIG_KEY       VARCHAR2(200)  NOT NULL,  -- token | auth_username | canal | category_code | etc.
  TIPO_CONFIG      VARCHAR2(50),             -- TEXTO | NUMERO | CREDENCIAL | FLAG
  CONFIG_VALOR     VARCHAR2(4000),           -- valor siempre como texto; NUMERO se convierte en runtime
  USR_CREACION     VARCHAR2(100)  DEFAULT USER    NOT NULL,
  FEC_CREACION     DATE           DEFAULT SYSDATE NOT NULL,
  USR_MODIFICACION VARCHAR2(100),
  FEC_MODIFICACION DATE,

  CONSTRAINT PK_IN_OMNI_PROVEEDOR_CONFIG
    PRIMARY KEY (ID_CONFIG),
  CONSTRAINT UX_IN_OMNI_PROVEEDOR_CONFIG_01
    UNIQUE (PROVEEDOR_KEY, CONFIG_KEY)
);

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_PROVEEDOR_CONFIG_01
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (PROVEEDOR_KEY);

CREATE OR REPLACE TRIGGER TUKUNAFUNC.TRG_IN_OMNI_PROVEEDOR_CONFIG_BI
BEFORE INSERT ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG
FOR EACH ROW
BEGIN
  IF :NEW.ID_CONFIG IS NULL THEN
    SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO :NEW.ID_CONFIG FROM DUAL;
  END IF;
END;
/

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG IS 'Configuracion funcional por proveedor: credenciales, canal, routing codes. Reemplaza app.integration.providers.* en application.properties.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG.PROVEEDOR_KEY IS 'Clave interna del proveedor: ecuabet, loteria, pega3, tradicional, claro.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG.CONFIG_KEY    IS 'Nombre del parametro: token, auth_username, auth_password, canal, category_code, etc.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG.TIPO_CONFIG   IS 'Tipo de valor: TEXTO, NUMERO, CREDENCIAL (dato sensible), FLAG (booleano texto true/false).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG.CONFIG_VALOR  IS 'Valor del parametro como texto. Para NUMERO se parsea en runtime.';
