/* ============================================================
   ESQUEMA : TUKUNAFUNC
   PROYECTO : OmniStack
   OBJETIVO : Crear tablas de configuracion de proveedores y
              trazabilidad de transacciones.

   PREFIJO  : IN_OMNI_  (evita colision con tablas IN_ del proyecto
              anterior que comparten el mismo esquema TUKUNAFUNC)

   TABLAS CREADAS
   ---------------------------------------------------------------
   IN_OMNI_PROVEEDOR_CONFIG   configuracion funcional por proveedor
   IN_OMNI_PROVEEDOR_WS       catalogo de endpoints por proveedor
   IN_OMNI_PROVEEDOR_HEADERS  headers HTTP por proveedor
   IN_OMNI_PROVEEDOR_WS_DEFS  valores por defecto por WS
   IN_OMNI_LOGS_APP           log de nivel aplicacion OmniStack
   IN_OMNI_LOGS_WS_EXT        log de llamadas a WS externos
   IN_OMNI_REGISTRO_TRX       registro de transacciones completadas

   NOTAS
   ---------------------------------------------------------------
   No se usan triggers. Todos los IDs/CODIGOs se insertan
   explicitamente via SEQ_XXX.NEXTVAL desde el DML o desde Java.
   ============================================================ */

---------------------------------------------------------------
-- 1) TABLA: IN_OMNI_PROVEEDOR_WS
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS (
  ID_WS             NUMBER(12)     NOT NULL,
  PROVEEDOR_KEY     VARCHAR2(50)   NOT NULL,
  WS_KEY            VARCHAR2(120)  NOT NULL,
  ENABLED           CHAR(1)        DEFAULT 'S' NOT NULL,
  TIPO_CONEXION     VARCHAR2(30)   NOT NULL,
  METODO_HTTP       VARCHAR2(10)   NOT NULL,
  TIPO_REQUEST      VARCHAR2(30)   NOT NULL,
  URL               VARCHAR2(500)  NOT NULL,
  NOMBRE_OPERACION  VARCHAR2(200),
  USR_CREACION      VARCHAR2(100)  DEFAULT USER    NOT NULL,
  FEC_CREACION      DATE           DEFAULT SYSDATE NOT NULL,
  USR_MODIFICACION  VARCHAR2(100),
  FEC_MODIFICACION  DATE,

  CONSTRAINT PK_IN_OMNI_PROVEEDOR_WS
    PRIMARY KEY (ID_WS),
  CONSTRAINT CK_IN_OMNI_PROVEEDOR_WS_ENA
    CHECK (ENABLED IN ('S','N')),
  CONSTRAINT CK_IN_OMNI_PROVEEDOR_WS_MET
    CHECK (UPPER(METODO_HTTP) IN ('GET','POST','PUT','PATCH','DELETE'))
);

CREATE UNIQUE INDEX TUKUNAFUNC.UX_IN_OMNI_PROVEEDOR_WS_01
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS (PROVEEDOR_KEY, WS_KEY);

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_PROVEEDOR_WS_01
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS (PROVEEDOR_KEY);

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_PROVEEDOR_WS_02
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS (ENABLED, PROVEEDOR_KEY);

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS IS 'Catalogo de endpoints (WS) por proveedor OmniStack.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS.PROVEEDOR_KEY    IS 'Clave interna del proveedor: ecuabet, loteria, pega3, tradicional, claro.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS.WS_KEY           IS 'Clave de la operacion: PRECHECK.CASHIN, EXECUTE.CASHOUT, LOGIN, etc.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS.URL              IS 'URL completa del WS (base_url concatenado con path).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS.NOMBRE_OPERACION IS 'Nombre logico de la operacion (ej: DEPOSITO, RECARGA593, validateRechargeRetail).';

---------------------------------------------------------------
-- 2) TABLA: IN_OMNI_PROVEEDOR_HEADERS
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (
  ID_HEADER         NUMBER(12)     NOT NULL,
  PROVEEDOR_KEY     VARCHAR2(50)   NOT NULL,
  HEADER_NOMBRE     VARCHAR2(200)  NOT NULL,
  HEADER_VALOR      VARCHAR2(2000) NOT NULL,
  USR_CREACION      VARCHAR2(100)  DEFAULT USER    NOT NULL,
  FEC_CREACION      DATE           DEFAULT SYSDATE NOT NULL,
  USR_MODIFICACION  VARCHAR2(100),
  FEC_MODIFICACION  DATE,

  CONSTRAINT PK_IN_OMNI_PROVEEDOR_HEADERS
    PRIMARY KEY (ID_HEADER)
);

CREATE UNIQUE INDEX TUKUNAFUNC.UX_IN_OMNI_PROVEEDOR_HEADERS_01
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (PROVEEDOR_KEY, HEADER_NOMBRE);

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_PROVEEDOR_HEADERS_01
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (PROVEEDOR_KEY);

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_HEADERS
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS IS 'Headers HTTP por proveedor (aplican a todos sus WS).';

---------------------------------------------------------------
-- 3) TABLA: IN_OMNI_PROVEEDOR_WS_DEFS
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (
  ID_DEFAULT         NUMBER(12)     NOT NULL,
  ID_WS              NUMBER(12)     NOT NULL,
  TIPO_DEF           VARCHAR2(100),
  DEFAULT_CLAVE      VARCHAR2(200)  NOT NULL,
  DEFAULT_VALOR_TEXT VARCHAR2(4000),
  DEFAULT_VALOR_NUM  NUMBER(18,6),
  DEFAULT_VALOR_DATE DATE,
  USR_CREACION       VARCHAR2(100)  DEFAULT USER    NOT NULL,
  FEC_CREACION       DATE           DEFAULT SYSDATE NOT NULL,
  USR_MODIFICACION   VARCHAR2(100),
  FEC_MODIFICACION   DATE,

  CONSTRAINT PK_IN_OMNI_PROVEEDOR_WS_DEFS
    PRIMARY KEY (ID_DEFAULT),
  CONSTRAINT FK_IN_OMNI_WS_DEFS_WS
    FOREIGN KEY (ID_WS)
    REFERENCES TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS (ID_WS)
);

CREATE UNIQUE INDEX TUKUNAFUNC.UX_IN_OMNI_PROVEEDOR_WS_DEFS_01
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, DEFAULT_CLAVE);

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_PROVEEDOR_WS_DEFS_01
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS);

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS IS 'Valores por defecto configurables por WS de proveedor.';

---------------------------------------------------------------
-- 4) TABLA: IN_OMNI_PROVEEDOR_CONFIG
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (
  ID_CONFIG        NUMBER(12)     NOT NULL,
  PROVEEDOR_KEY    VARCHAR2(50)   NOT NULL,
  CONFIG_KEY       VARCHAR2(200)  NOT NULL,
  TIPO_CONFIG      VARCHAR2(50),
  CONFIG_VALOR     VARCHAR2(4000),
  USR_CREACION     VARCHAR2(100)  DEFAULT USER    NOT NULL,
  FEC_CREACION     DATE           DEFAULT SYSDATE NOT NULL,
  USR_MODIFICACION VARCHAR2(100),
  FEC_MODIFICACION DATE,

  CONSTRAINT PK_IN_OMNI_PROVEEDOR_CONFIG
    PRIMARY KEY (ID_CONFIG),
  CONSTRAINT UX_IN_OMNI_PROVEEDOR_CONFIG_01
    UNIQUE (PROVEEDOR_KEY, CONFIG_KEY)
);

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_PROVEEDOR_CONFIG_01
  ON TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (PROVEEDOR_KEY);

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG IS 'Configuracion funcional por proveedor: credenciales, canal, routing codes.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG.CONFIG_KEY   IS 'Nombre del parametro: token, auth_username, auth_password, canal, category_code, etc.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG.TIPO_CONFIG  IS 'Tipo de valor: TEXTO, NUMERO, CREDENCIAL, FLAG.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG.CONFIG_VALOR IS 'Valor como texto; para NUMERO se parsea en runtime.';

---------------------------------------------------------------
-- 5) TABLA: IN_OMNI_LOGS_APP
--    CODIGO se inserta via SEQ_IN_OMNI_LOGS_APP.NEXTVAL desde Java.
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_LOGS_APP (
  CODIGO             NUMBER(18)     NOT NULL,
  UUID               VARCHAR2(200),
  REQUEST            CLOB,
  RESPONSE           CLOB,
  USUARIO            VARCHAR2(100),
  FECHA_REGISTRO     DATE           DEFAULT SYSDATE,
  MENSAJE            VARCHAR2(2000),
  PROVEEDOR          VARCHAR2(100),
  CAPABILITY         VARCHAR2(50),
  CANAL              VARCHAR2(50),
  CADENA             NUMBER(10),
  FARMACIA           NUMBER(10),
  NOMBRE_FARMACIA    VARCHAR2(200),
  POS                VARCHAR2(20),
  URL                VARCHAR2(500),
  METODO             VARCHAR2(20),
  HTTP_STATUS        NUMBER(5),
  ES_ERROR           CHAR(1),
  COD_ERROR          VARCHAR2(200),
  MSG_ERROR          VARCHAR2(2000),
  CP_VAR1            VARCHAR2(1500),
  CP_VAR2            VARCHAR2(1500),
  CP_VAR3            VARCHAR2(1500),
  CP_NUMBER1         NUMBER,
  CP_NUMBER2         NUMBER,
  CP_DATE1           DATE,
  CP_DATE2           DATE,

  CONSTRAINT PK_IN_OMNI_LOGS_APP
    PRIMARY KEY (CODIGO),
  CONSTRAINT CK_IN_OMNI_LOGS_APP_ERR
    CHECK (ES_ERROR IN ('S','N'))
);

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_LOGS_APP
  START WITH 1 INCREMENT BY 1 CACHE 500 NOCYCLE;

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_APP_UUID       ON TUKUNAFUNC.IN_OMNI_LOGS_APP (UUID);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_APP_FECHA      ON TUKUNAFUNC.IN_OMNI_LOGS_APP (FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_APP_PROV_FECHA ON TUKUNAFUNC.IN_OMNI_LOGS_APP (PROVEEDOR, FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_APP_CAP_FECHA  ON TUKUNAFUNC.IN_OMNI_LOGS_APP (CAPABILITY, FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_APP_CAD_FAR    ON TUKUNAFUNC.IN_OMNI_LOGS_APP (CADENA, FARMACIA, POS, FECHA_REGISTRO);

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_LOGS_APP IS 'Auditoria de llamadas al API OmniStack (nivel aplicacion).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_LOGS_APP.UUID       IS 'Identificador de transaccion propagado a todos los proveedores.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_LOGS_APP.CAPABILITY IS 'Capacidad ejecutada: PRECHECK, EXECUTE, VERIFY, REVERSE, CREATE_TICKET.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_LOGS_APP.ES_ERROR   IS 'S=error en la transaccion, N=exito.';

---------------------------------------------------------------
-- 6) TABLA: IN_OMNI_LOGS_WS_EXT
--    CODIGO se inserta via SEQ_IN_OMNI_LOGS_WS_EXT.NEXTVAL desde Java.
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT (
  CODIGO             NUMBER(18)     NOT NULL,
  UUID               VARCHAR2(200),
  REQUEST            CLOB,
  RESPONSE           CLOB,
  USUARIO            VARCHAR2(100),
  FECHA_REGISTRO     DATE           DEFAULT SYSDATE,
  MENSAJE            VARCHAR2(2000),
  PROVEEDOR          VARCHAR2(100),
  WS_KEY             VARCHAR2(120),
  CANAL              VARCHAR2(50),
  CADENA             NUMBER(10),
  FARMACIA           NUMBER(10),
  POS                VARCHAR2(20),
  URL                VARCHAR2(500),
  METODO             VARCHAR2(20),
  HTTP_STATUS        NUMBER(5),
  DURACION_MS        NUMBER(10),
  ES_ERROR           CHAR(1),
  CP_VAR1            VARCHAR2(1500),
  CP_VAR2            VARCHAR2(1500),
  CP_DATE1           DATE,

  CONSTRAINT PK_IN_OMNI_LOGS_WS_EXT
    PRIMARY KEY (CODIGO),
  CONSTRAINT CK_IN_OMNI_LOGS_WS_EXT_ERR
    CHECK (ES_ERROR IN ('S','N'))
);

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_LOGS_WS_EXT
  START WITH 1 INCREMENT BY 1 CACHE 500 NOCYCLE;

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_WS_EXT_UUID       ON TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT (UUID);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_WS_EXT_FECHA      ON TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT (FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_WS_EXT_PROV_FECHA ON TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT (PROVEEDOR, FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_LOGS_WS_EXT_WS_FECHA   ON TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT (WS_KEY, FECHA_REGISTRO);

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT IS 'Log de llamadas HTTP salientes a WS de proveedores externos.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT.WS_KEY      IS 'Clave del WS llamado (PRECHECK.CASHIN, EXECUTE.CASHOUT, etc.).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_LOGS_WS_EXT.DURACION_MS IS 'Duracion de la llamada al proveedor en milisegundos.';

---------------------------------------------------------------
-- 7) TABLA: IN_OMNI_REGISTRO_TRX
--    CODIGO se inserta via SEQ_IN_OMNI_REGISTRO_TRX.NEXTVAL desde Java.
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (
  CODIGO                    NUMBER(18)     NOT NULL,
  UUID                      VARCHAR2(200),
  CADENA                    NUMBER(10),
  FARMACIA                  NUMBER(10),
  NOMBRE_FARMACIA           VARCHAR2(200),
  POS                       VARCHAR2(20),
  FECHA_REGISTRO            DATE           DEFAULT SYSDATE,
  FECHA_AUTORIZACION_PROV   DATE,
  CANAL                     VARCHAR2(50),
  PROVEEDOR                 VARCHAR2(100),
  CATEGORY_CODE             VARCHAR2(20),
  SUBCATEGORY_CODE          VARCHAR2(20),
  SERVICE_PROVIDER_CODE     VARCHAR2(20),
  RMS_ITEM_CODE             VARCHAR2(100),
  CAPABILITY                VARCHAR2(50),
  ID_EXTERNO                VARCHAR2(200),
  AUTHORIZATION             VARCHAR2(200),
  MONTO                     NUMBER(18,2),
  MONEDA                    VARCHAR2(10)   DEFAULT 'USD',
  COD_ESTADO                VARCHAR2(20),
  ES_ERROR                  CHAR(1),
  COD_ERROR                 VARCHAR2(200),
  MSG_ERROR                 VARCHAR2(2000),
  CP_VAR1                   VARCHAR2(1500),
  CP_VAR2                   VARCHAR2(1500),
  CP_VAR3                   VARCHAR2(1500),
  CP_NUMBER1                NUMBER,
  CP_DATE1                  DATE,

  CONSTRAINT PK_IN_OMNI_REGISTRO_TRX
    PRIMARY KEY (CODIGO),
  CONSTRAINT CK_IN_OMNI_REGISTRO_TRX_ERR
    CHECK (ES_ERROR IN ('S','N')),
  CONSTRAINT CK_IN_OMNI_REGISTRO_TRX_MON
    CHECK (MONEDA IS NULL OR LENGTH(MONEDA) <= 10)
);

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_REGISTRO_TRX
  START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_REGISTRO_TRX_UUID    ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (UUID);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_REGISTRO_TRX_FECHA   ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_REGISTRO_TRX_IDEXT   ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (ID_EXTERNO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_REGISTRO_TRX_AUTH    ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (AUTHORIZATION);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_REGISTRO_TRX_PROV    ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (PROVEEDOR, CAPABILITY, FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_REGISTRO_TRX_CAD_FAR ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (CADENA, FARMACIA, POS, FECHA_REGISTRO);
CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_REGISTRO_TRX_ESTADO  ON TUKUNAFUNC.IN_OMNI_REGISTRO_TRX (COD_ESTADO, FECHA_REGISTRO);

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_REGISTRO_TRX IS 'Registro de transacciones OmniStack para conciliacion y reporteria.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_REGISTRO_TRX.ID_EXTERNO    IS 'ID del proveedor externo (recargaid, transactionId, gameTicketNumber, etc.).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_REGISTRO_TRX.AUTHORIZATION IS 'Campo authorization del response OmniStack.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_REGISTRO_TRX.COD_ESTADO    IS 'Estado: OK | ERROR | PENDIENTE | REVERTIDO.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_REGISTRO_TRX.CAPABILITY    IS 'Capacidad ejecutada: PRECHECK, EXECUTE, VERIFY, REVERSE, CREATE_TICKET.';
