/* ============================================================
   ESQUEMA : TUKUNAFUNC
   PROYECTO : OmniStack
   OBJETIVO : Poblar tablas de configuracion de proveedores.

   PROVEEDORES
   ---------------------------------------------------------------
   ecuabet     ECUABET (apuestas)                   provider_code=1
   loteria     LN BET593 (recarga/retiro online)    provider_code=2
   pega3       LN Pega3  (loteria instantanea)      provider_code=2
   tradicional LN Tradicionales (loteria clasica)   provider_code=2
   claro       Claro (recargas telefonicas)          provider_code=7

   NOTA: Las URLs corresponden al entorno DEV/UAT.
   Para produccion, actualizar la columna URL de IN_OMNI_PROVEEDOR_WS.
   ============================================================ */

/* ============================================================
   SECCION 1: IN_OMNI_PROVEEDOR_WS
   (catalogo de endpoints, uno por capability+movement)
   ============================================================ */

-- ---- ECUABET ------------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('ecuabet','PRECHECK.CASHIN','S','REST','POST','JSON',
   'https://apidev.virtualsoft.tech/operatorapi-new/user/search','BUSCAR_USUARIO');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('ecuabet','PRECHECK.CASHOUT','S','REST','POST','JSON',
   'https://apidev.virtualsoft.tech/operatorapi-new/user/searchwithdraw','BUSCAR_NOTA_RETIRO');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('ecuabet','EXECUTE.CASHIN','S','REST','POST','JSON',
   'https://apidev.virtualsoft.tech/operatorapi-new/user/deposit','DEPOSITO');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('ecuabet','EXECUTE.CASHOUT','S','REST','POST','JSON',
   'https://apidev.virtualsoft.tech/operatorapi-new/user/withdraw','EJECUCION_NOTA_RETIRO');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('ecuabet','REVERSE.CASHIN','S','REST','POST','JSON',
   'https://apidev.virtualsoft.tech/operatorapi-new/rollback/deposit','REVERSO_DEPOSITO');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('ecuabet','REVERSE.CASHOUT','S','REST','POST','JSON',
   'https://apidev.virtualsoft.tech/operatorapi-new/rollback/withdraw','REVERSO_NOTA_RETIRO');

-- ---- LN BET593 ---------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('loteria','LOGIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/Login','LOGIN_BET593');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('loteria','PRECHECK.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecargarBet593','RECARGA593');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('loteria','EXECUTE.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ConfirmarBet593','CONFIRMAR593');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('loteria','VERIFY.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ValidarBet593','VALIDAR593');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('loteria','REVERSE.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ReversarBet593','REVERSAR593');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('loteria','PRECHECK.CASHOUT','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ConsultarRetiroBet593','CONSULTAR_RETIRO');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('loteria','EXECUTE.CASHOUT','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RetirarBet593','RETIRO593');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('loteria','VERIFY.CASHOUT','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ConsultarRetiroBet593','CON_RETIRO593');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('loteria','REVERSE.CASHOUT','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ReversarRetiroBet593','REV_RETIRO593');

-- ---- LN PEGA3 ----------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('pega3','LOGIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/Login','LOGIN_PEGA3');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('pega3','PRECHECK.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/VentaProductos','VENTA_PRODUCTOS_PEGA3');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('pega3','PRECHECK_SORTEO.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ObtieneSorteosActivo','SORTEOS_ACTIVO_PEGA3');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('pega3','CREATE_TICKET.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/CrearTicket','CREAR_TICKET_PEGA3');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('pega3','EXECUTE.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/PagarTicket','PAGAR_TICKET_PEGA3');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('pega3','VERIFY.CASHIN','S','REST','GET','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ConsultarTicket','CONSULTAR_TICKET_PEGA3');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('pega3','REVERSE.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/CancelarTicket','CANCELAR_TICKET_PEGA3');

-- ---- LN TRADICIONALES --------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('tradicional','LOGIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/Login','LOGIN_TRAD');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('tradicional','PRECHECK.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecuperarJuegosPorMedio','RECUPERAR_JUEGOS_TRAD');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('tradicional','PRECHECK_SORTEOS.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecuperarSorteosDisponibles','SORTEOS_TRAD');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('tradicional','PRECHECK_FIGURAS.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecuperarFigurasPorJuego','FIGURAS_TRAD');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('tradicional','PRECHECK_NUMEROS.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecuperarNumerosDisponiblesPorCombinacion','NUMEROS_TRAD');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('tradicional','EXECUTE.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/VentaBoletos','VENTA_BOLETOS_TRAD');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('tradicional','VERIFY.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/GenerarComprobanteVenta','COMPROBANTE_TRAD');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('tradicional','REVERSE.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/AnularVentaBoletos','ANULAR_VENTA_TRAD');

-- ---- CLARO -------------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('claro','PRECHECK.CASHIN','S','SOAP','POST','XML',
   'http://192.168.37.40:50004/sprXslt/SprXslt','validateRechargeRetail');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  ('claro','EXECUTE.CASHIN','S','SOAP','POST','XML',
   'http://192.168.37.40:50004/sprXslt/SprXslt','processRechargeRetail');

/* ============================================================
   SECCION 2: IN_OMNI_PROVEEDOR_HEADERS
   (headers HTTP por proveedor, aplican a todos sus WS)
   ============================================================ */

-- ECUABET
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES ('ecuabet', 'Content-Type', 'application/json');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES ('ecuabet', 'Accept', 'application/json');

-- LN BET593
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES ('loteria', 'Content-Type', 'application/json');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES ('loteria', 'Accept', 'application/json');

-- LN PEGA3
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES ('pega3', 'Content-Type', 'application/json');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES ('pega3', 'Accept', 'application/json');

-- LN TRADICIONALES
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES ('tradicional', 'Content-Type', 'application/json');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES ('tradicional', 'Accept', 'application/json');

-- CLARO: XML
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES ('claro', 'Content-Type', 'application/xml;charset=UTF-8');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES ('claro', 'Accept', 'application/xml');

/* ============================================================
   SECCION 3: IN_OMNI_PROVEEDOR_WS_DEFS
   (valores por defecto especificos de cada WS)
   ============================================================ */

-- ECUABET PRECHECK.CASHIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'shop_id', '998739'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT w.ID_WS, 'NUMERO', 'country', 66
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'PRECHECK.CASHIN';

-- ECUABET EXECUTE.CASHIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'shop_id', '998739'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'EXECUTE.CASHIN';

-- LN BET593 LOGIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT w.ID_WS, 'NUMERO', 'medio_id', 23
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'loteria' AND w.WS_KEY = 'LOGIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT w.ID_WS, 'NUMERO', 'cliente_id', 58542
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'loteria' AND w.WS_KEY = 'LOGIN';

-- LN PEGA3 LOGIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT w.ID_WS, 'NUMERO', 'medio_id', 23
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'LOGIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT w.ID_WS, 'NUMERO', 'cliente_id', 58542
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'LOGIN';

-- LN TRADICIONALES LOGIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT w.ID_WS, 'NUMERO', 'medio_id', 23
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'LOGIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT w.ID_WS, 'NUMERO', 'cliente_id', 58542
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'LOGIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'canal', 'BMV'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'LOGIN';

-- CLARO PRECHECK.CASHIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'company_id', '2'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'consumer_id', 'FYBECA_001'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'channel_id', 'CAJA'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'media_id', 'RETA'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'media_detail_id', 'RETA_FYBECA'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'cod_caja', 'DA00004'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'cod_site', '10000004'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'external_operation', 'RECARGA_DATOS'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'subscriber_type', '2'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'subscription_type', 'EVENTUAL'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'OFFERID', 'offer_id.12004565834', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'OFFERID', 'offer_id.12001565829', '132'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

-- CLARO EXECUTE.CASHIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'company_id', '2'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'consumer_id', 'FYBECA_001'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'cod_caja', 'DA00004'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'TEXTO', 'cod_site', '10000004'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'OFFERID', 'offer_id.12004565834', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT w.ID_WS, 'OFFERID', 'offer_id.12001565829', '132'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

COMMIT;
