/* ============================================================
   ESQUEMA : TUKUNAFUNC
   PROYECTO : OmniStack
   OBJETIVO : Poblar tablas de configuracion de proveedores.

   PROVEEDORES
   ---------------------------------------------------------------
   ecuabet     ECUABET (apuestas)                   provider_code=1
   loteria     LN BET593 (recarga/retiro online)    provider_code=2
   pega3       LN Pega3  (loteria instantanea)      provider_code=2
   tradicional LN Tradicionales (loteria clasica)   provider_code=2
   claro       Claro (recargas telefonicas)          provider_code=7

   NOTA: Las URLs corresponden al entorno DEV/UAT.
   Para produccion, actualizar la columna URL de IN_OMNI_PROVEEDOR_WS.
   ============================================================ */

/* ============================================================
   SECCION 1: IN_OMNI_PROVEEDOR_WS
   (catalogo de endpoints, uno por capability+movement)
   ============================================================ */

-- ---- ECUABET ------------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'ecuabet','PRECHECK.CASHIN','S','REST','POST','JSON',
   'https://apidev.virtualsoft.tech/operatorapi-new/user/search','BUSCAR_USUARIO');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'ecuabet','PRECHECK.CASHOUT','S','REST','POST','JSON',
   'https://apidev.virtualsoft.tech/operatorapi-new/user/searchwithdraw','BUSCAR_NOTA_RETIRO');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'ecuabet','EXECUTE.CASHIN','S','REST','POST','JSON',
   'https://apidev.virtualsoft.tech/operatorapi-new/user/deposit','DEPOSITO');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'ecuabet','EXECUTE.CASHOUT','S','REST','POST','JSON',
   'https://apidev.virtualsoft.tech/operatorapi-new/user/withdraw','EJECUCION_NOTA_RETIRO');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'ecuabet','REVERSE.CASHIN','S','REST','POST','JSON',
   'https://apidev.virtualsoft.tech/operatorapi-new/rollback/deposit','REVERSO_DEPOSITO');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'ecuabet','REVERSE.CASHOUT','S','REST','POST','JSON',
   'https://apidev.virtualsoft.tech/operatorapi-new/rollback/withdraw','REVERSO_NOTA_RETIRO');

-- ---- LN BET593 ---------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'loteria','LOGIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/Login','LOGIN_BET593');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'loteria','PRECHECK.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecargarBet593','RECARGA593');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'loteria','EXECUTE.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ConfirmarBet593','CONFIRMAR593');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'loteria','VERIFY.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ValidarBet593','VALIDAR593');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'loteria','REVERSE.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ReversarBet593','REVERSAR593');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'loteria','PRECHECK.CASHOUT','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ConsultarRetiroBet593','CONSULTAR_RETIRO');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'loteria','EXECUTE.CASHOUT','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RetirarBet593','RETIRO593');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'loteria','VERIFY.CASHOUT','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ConsultarRetiroBet593','CON_RETIRO593');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'loteria','REVERSE.CASHOUT','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ReversarRetiroBet593','REV_RETIRO593');

-- ---- LN PEGA3 ----------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'pega3','LOGIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/Login','LOGIN_PEGA3');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'pega3','PRECHECK.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/VentaProductos','VENTA_PRODUCTOS_PEGA3');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'pega3','PRECHECK_SORTEO.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ObtieneSorteosActivo','SORTEOS_ACTIVO_PEGA3');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'pega3','CREATE_TICKET.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/CrearTicket','CREAR_TICKET_PEGA3');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'pega3','EXECUTE.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/PagarTicket','PAGAR_TICKET_PEGA3');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'pega3','VERIFY.CASHIN','S','REST','GET','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ConsultarTicket','CONSULTAR_TICKET_PEGA3');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'pega3','REVERSE.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/CancelarTicket','CANCELAR_TICKET_PEGA3');

-- ---- LN TRADICIONALES --------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'tradicional','LOGIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/Login','LOGIN_TRAD');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'tradicional','PRECHECK.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecuperarJuegosPorMedio','RECUPERAR_JUEGOS_TRAD');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'tradicional','PRECHECK_SORTEOS.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecuperarSorteosDisponibles','SORTEOS_TRAD');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'tradicional','PRECHECK_FIGURAS.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecuperarFigurasPorJuego','FIGURAS_TRAD');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'tradicional','PRECHECK_NUMEROS.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecuperarNumerosDisponiblesPorCombinacion','NUMEROS_TRAD');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'tradicional','EXECUTE.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/VentaBoletos','VENTA_BOLETOS_TRAD');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'tradicional','VERIFY.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/GenerarComprobanteVenta','COMPROBANTE_TRAD');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'tradicional','REVERSE.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/AnularVentaBoletos','ANULAR_VENTA_TRAD');

-- ---- CLARO -------------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'claro','PRECHECK.CASHIN','S','SOAP','POST','XML',
   'http://192.168.37.40:50004/sprXslt/SprXslt','validateRechargeRetail');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'claro','EXECUTE.CASHIN','S','SOAP','POST','XML',
   'http://192.168.37.40:50004/sprXslt/SprXslt','processRechargeRetail');

/* ============================================================
   SECCION 2: IN_OMNI_PROVEEDOR_HEADERS
   (headers HTTP por proveedor, aplican a todos sus WS)
   ============================================================ */

-- ECUABET
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES (SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL, 'ecuabet', 'Content-Type', 'application/json');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES (SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL, 'ecuabet', 'Accept', 'application/json');

-- LN BET593
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES (SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL, 'loteria', 'Content-Type', 'application/json');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES (SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL, 'loteria', 'Accept', 'application/json');

-- LN PEGA3
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES (SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL, 'pega3', 'Content-Type', 'application/json');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES (SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL, 'pega3', 'Accept', 'application/json');

-- LN TRADICIONALES
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES (SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL, 'tradicional', 'Content-Type', 'application/json');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES (SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL, 'tradicional', 'Accept', 'application/json');

-- CLARO: XML
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES (SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL, 'claro', 'Content-Type', 'application/xml;charset=UTF-8');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
VALUES (SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL, 'claro', 'Accept', 'application/xml');

/* ============================================================
   SECCION 3: IN_OMNI_PROVEEDOR_WS_DEFS
   (valores por defecto especificos de cada WS)
   ============================================================ */

-- ECUABET PRECHECK.CASHIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'shop_id', '998739'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'NUMERO', 'country', 66
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'PRECHECK.CASHIN';

-- ECUABET EXECUTE.CASHIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'shop_id', '998739'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'EXECUTE.CASHIN';

-- LN BET593 LOGIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'NUMERO', 'medio_id', 23
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'loteria' AND w.WS_KEY = 'LOGIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'NUMERO', 'cliente_id', 58542
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'loteria' AND w.WS_KEY = 'LOGIN';

-- LN PEGA3 LOGIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'NUMERO', 'medio_id', 23
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'LOGIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'NUMERO', 'cliente_id', 58542
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'LOGIN';

-- LN TRADICIONALES LOGIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'NUMERO', 'medio_id', 23
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'LOGIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'NUMERO', 'cliente_id', 58542
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'LOGIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'canal', 'BMV'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'LOGIN';

-- CLARO PRECHECK.CASHIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'company_id', '2'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'consumer_id', 'FYBECA_001'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'channel_id', 'CAJA'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'media_id', 'RETA'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'media_detail_id', 'RETA_FYBECA'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'cod_caja', 'DA00004'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'cod_site', '10000004'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'external_operation', 'RECARGA_DATOS'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'subscriber_type', '2'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'subscription_type', 'EVENTUAL'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.12004565834', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.12001565829', '132'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

-- CLARO EXECUTE.CASHIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'company_id', '2'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'consumer_id', 'FYBECA_001'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'cod_caja', 'DA00004'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'cod_site', '10000004'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.12004565834', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.12001565829', '132'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

/* ============================================================
   SECCION 3b: IN_OMNI_PROVEEDOR_WS_DEFS — complemento
   Entradas faltantes: shop_id/country para operaciones CASHOUT
   y REVERSE de Ecuabet, y campo "item" (rms_item_code) para
   que hasConfiguredOperation() valide routing desde DB.
   ============================================================ */

-- ---- ECUABET: shop_id + country para operaciones faltantes ----

-- PRECHECK.CASHOUT
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'shop_id', '998739'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'PRECHECK.CASHOUT';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'NUMERO', 'country', 66
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'PRECHECK.CASHOUT';

-- EXECUTE.CASHOUT
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'shop_id', '998739'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'EXECUTE.CASHOUT';

-- REVERSE.CASHIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'shop_id', '998739'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'REVERSE.CASHIN';

-- REVERSE.CASHOUT
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'TEXTO', 'shop_id', '998739'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'REVERSE.CASHOUT';

-- ---- ITEM (rms_item_code) por WS_KEY — todos los proveedores ----
-- Permite validar routing desde DB en AbstractProviderStrategy.hasConfiguredOperation()

-- ECUABET
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '100713841' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '100708846' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'PRECHECK.CASHOUT';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '100713841' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '100708846' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'EXECUTE.CASHOUT';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '100713841' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'REVERSE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '100708846' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'ecuabet' AND w.WS_KEY = 'REVERSE.CASHOUT';

-- LN BET593 (PROVEEDOR_KEY = 'loteria')
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '100708850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'loteria' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '100708850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'loteria' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '100708850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'loteria' AND w.WS_KEY = 'VERIFY.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '100708850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'loteria' AND w.WS_KEY = 'REVERSE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '100708848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'loteria' AND w.WS_KEY = 'EXECUTE.CASHOUT';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '100708848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'loteria' AND w.WS_KEY = 'VERIFY.CASHOUT';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '100708848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'loteria' AND w.WS_KEY = 'REVERSE.CASHOUT';

-- LN PEGA3
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '20001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '20001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'CREATE_TICKET.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '20001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '20001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'VERIFY.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '20001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'REVERSE.CASHIN';

-- LN TRADICIONALES
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '10001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '10001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '10001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'VERIFY.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item', '10001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'REVERSE.CASHIN';

-- CLARO: usa offer_id.{rmsItemCode} para routing, no necesita campo 'item'

/* ============================================================
   SECCION 3c: IN_OMNI_PROVEEDOR_WS_DEFS — items QA/MOMDEV
   Formato item.{rmsItemCode} para soportar multiples items por
   proveedor en QA. Las entradas legacy 'item' de la seccion 3b
   siguen siendo validas para local dev (compatibilidad doble).

   PEGA3 QA:        100708852 (Pega3), 100713848 (Pega4), 100713850 (Pega2)
   TRADICIONALES QA: 100713842 (Loteria), 100713844 (Lotto), 100713846 (Pozzo)

   CASH_OUT (PREMIOS) excluidos: strategies no implementadas aun.
   ============================================================ */

-- ---- PEGA3 — PRECHECK.CASHIN ----
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708852', '100708852' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'PRECHECK.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713848', '100713848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'PRECHECK.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713850', '100713850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'PRECHECK.CASHIN';

-- ---- PEGA3 — CREATE_TICKET.CASHIN ----
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708852', '100708852' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'CREATE_TICKET.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713848', '100713848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'CREATE_TICKET.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713850', '100713850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'CREATE_TICKET.CASHIN';

-- ---- PEGA3 — EXECUTE.CASHIN ----
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708852', '100708852' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'EXECUTE.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713848', '100713848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'EXECUTE.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713850', '100713850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'EXECUTE.CASHIN';

-- ---- PEGA3 — VERIFY.CASHIN ----
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708852', '100708852' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'VERIFY.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713848', '100713848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'VERIFY.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713850', '100713850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'VERIFY.CASHIN';

-- ---- PEGA3 — REVERSE.CASHIN ----
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708852', '100708852' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'REVERSE.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713848', '100713848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'REVERSE.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713850', '100713850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'REVERSE.CASHIN';

-- ---- TRADICIONALES — PRECHECK.CASHIN ----
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713842', '100713842' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'PRECHECK.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713844', '100713844' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'PRECHECK.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713846', '100713846' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'PRECHECK.CASHIN';

-- ---- TRADICIONALES — EXECUTE.CASHIN ----
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713842', '100713842' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'EXECUTE.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713844', '100713844' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'EXECUTE.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713846', '100713846' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'EXECUTE.CASHIN';

-- ---- TRADICIONALES — VERIFY.CASHIN ----
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713842', '100713842' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'VERIFY.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713844', '100713844' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'VERIFY.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713846', '100713846' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'VERIFY.CASHIN';

-- ---- TRADICIONALES — REVERSE.CASHIN ----
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713842', '100713842' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'REVERSE.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713844', '100713844' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'REVERSE.CASHIN';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713846', '100713846' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'REVERSE.CASHIN';

/* ============================================================
   SECCION 4: IN_OMNI_PROVEEDOR_CONFIG
   Configuracion funcional por proveedor: credenciales, canal,
   routing codes, geolocalizacion.
   Reemplaza app.integration.providers.* en application.properties.
   ============================================================ */

-- ---- ECUABET ------------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'ecuabet', 'technical_user',       'TEXTO',      'system');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'ecuabet', 'provider_name',        'TEXTO',      'ECUABET');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'ecuabet', 'category_code',        'TEXTO',      '1');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'ecuabet', 'subcategory_code',     'TEXTO',      '1');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'ecuabet', 'service_provider_code','TEXTO',      '407925');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'ecuabet', 'shop_ip',              'TEXTO',      '');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'ecuabet', 'shop_id',              'TEXTO',      '998739');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'ecuabet', 'country',              'NUMERO',     '66');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'ecuabet', 'token',                'CREDENCIAL', 'OEpXWWREQVFPSGl1Qi90Sko2RVJsbFM4bVNDRFljNGdzTUcyd2haTERWaz0=');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'ecuabet', 'auth_mode',            'TEXTO',      'STATIC');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'ecuabet', 'auth_ttl_hours',       'NUMERO',     '24');

-- ---- LN BET593 (loteria) ------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'technical_user',          'TEXTO',      'system');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'provider_name',           'TEXTO',      'LOTERIA NACIONAL');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'category_code',           'TEXTO',      '1');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'subcategory_code',        'TEXTO',      '1');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'service_provider_code',   'TEXTO',      '407925');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'canal',                   'TEXTO',      'BMV');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'punto_operacion_id',      'NUMERO',     '52132');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'shop_ip',                 'TEXTO',      '192.168.3.230');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'auth_mode',               'TEXTO',      'LOGIN');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'auth_ttl_hours',          'NUMERO',     '24');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'auth_refresh_on_startup', 'FLAG',       'true');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'auth_username',           'CREDENCIAL', 'USRFEMSAPREP');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'auth_password',           'CREDENCIAL', 'F3m993sA.');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'auth_product_to_sell',    'TEXTO',      'Bet593');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'medio_id',                'NUMERO',     '23');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'loteria', 'cliente_id',              'NUMERO',     '58542');

-- ---- LN PEGA3 -----------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'pega3', 'technical_user',          'TEXTO',      'system');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'pega3', 'provider_name',           'TEXTO',      'Pega3');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'pega3', 'category_code',           'TEXTO',      '1');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'pega3', 'subcategory_code',        'TEXTO',      '2');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'pega3', 'service_provider_code',   'TEXTO',      '407827');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'pega3', 'canal',                   'TEXTO',      'Terminal');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'pega3', 'shop_id',                 'TEXTO',      '52132');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'pega3', 'auth_mode',               'TEXTO',      'LOGIN');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'pega3', 'auth_ttl_hours',          'NUMERO',     '24');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'pega3', 'auth_refresh_on_startup', 'FLAG',       'true');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'pega3', 'auth_username',           'CREDENCIAL', 'USRFEMSAPREP');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'pega3', 'auth_password',           'CREDENCIAL', 'F3m993sA.');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'pega3', 'auth_product_to_sell',    'TEXTO',      'Pega3');

-- ---- LN TRADICIONALES ---------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'technical_user',          'TEXTO',      'system');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'provider_name',           'TEXTO',      'Tradicionales');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'category_code',           'TEXTO',      '1');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'subcategory_code',        'TEXTO',      '2');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'service_provider_code',   'TEXTO',      '407827');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'shop_id',                 'TEXTO',      '52132');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'punto_operacion_id',      'NUMERO',     '52132');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'auth_mode',               'TEXTO',      'LOGIN');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'auth_ttl_hours',          'NUMERO',     '24');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'auth_refresh_on_startup', 'FLAG',       'true');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'auth_username',           'CREDENCIAL', 'USRFEMSAPREP');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'auth_password',           'CREDENCIAL', 'F3m993sA.');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'auth_product_to_sell',    'TEXTO',      'Tradicionales');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'canal',                   'TEXTO',      'BMV');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'medio_id',                'NUMERO',     '23');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'tradicional', 'cliente_id',              'NUMERO',     '58542');

-- ---- CLARO --------------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'claro', 'category_code',           'TEXTO',      '5');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'claro', 'subcategory_code',        'TEXTO',      '9');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'claro', 'service_provider_code',   'TEXTO',      '7');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'claro', 'token',                   'CREDENCIAL', 'FYBECA');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'claro', 'shop_ip',                 'TEXTO',      '10.35.2.78');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'claro', 'auth_mode',               'TEXTO',      'STATIC');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'claro', 'auth_username',           'CREDENCIAL', 'PRUEBAREC');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'claro', 'auth_password',           'CREDENCIAL', '5566');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'claro', 'latitude',                'TEXTO',      '2 13 07.878S');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'claro', 'longitude',               'TEXTO',      '80 57 17.965W');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'claro', 'canton',                  'TEXTO',      '0901');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'claro', 'province',                'TEXTO',      '09');
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG, PROVEEDOR_KEY, CONFIG_KEY, TIPO_CONFIG, CONFIG_VALOR) VALUES (SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL, 'claro', 'parish',                  'TEXTO',      '090112');

COMMIT;
