/* ============================================================
   ESQUEMA : TUKUNAFUNC
   PROYECTO : OmniStack
   OBJETIVO : Poblar tablas de configuracion de proveedores.

   NOTA: IDs generados con secuencias (SEQ_IN_OMNI_PROVEEDOR_WS,
         SEQ_IN_OMNI_PROVEEDOR_HEADERS, SEQ_IN_OMNI_PROVEEDOR_WS_DEFS,
         SEQ_IN_OMNI_PROVEEDOR_CONFIG). Las secuencias deben existir
         previamente (ver ALL_SEQUENCES.sql).
   ============================================================ */

DECLARE
  v_id_ws      NUMBER;
  v_id_header  NUMBER;
  v_id_default NUMBER;
  v_id_config  NUMBER;

BEGIN

  /* ==========================================================
     SECCION 1: IN_OMNI_PROVEEDOR_WS
     ========================================================== */

  -- ---- ECUABET -----------------------------------------------
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'ecuabet','PRECHECK.CASHIN','S','REST','POST','JSON',
    'https://apidev.virtualsoft.tech/operatorapi-new/user/search','BUSCAR_USUARIO');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'ecuabet','PRECHECK.CASHOUT','S','REST','POST','JSON',
    'https://apidev.virtualsoft.tech/operatorapi-new/user/searchwithdraw','BUSCAR_NOTA_RETIRO');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'ecuabet','EXECUTE.CASHIN','S','REST','POST','JSON',
    'https://apidev.virtualsoft.tech/operatorapi-new/user/deposit','DEPOSITO');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'ecuabet','EXECUTE.CASHOUT','S','REST','POST','JSON',
    'https://apidev.virtualsoft.tech/operatorapi-new/user/withdraw','EJECUCION_NOTA_RETIRO');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'ecuabet','REVERSE.CASHIN','S','REST','POST','JSON',
    'https://apidev.virtualsoft.tech/operatorapi-new/rollback/deposit','REVERSO_DEPOSITO');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'ecuabet','REVERSE.CASHOUT','S','REST','POST','JSON',
    'https://apidev.virtualsoft.tech/operatorapi-new/rollback/withdraw','REVERSO_NOTA_RETIRO');

  -- ---- LN BET593 ---------------------------------------------
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'loteria','LOGIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/Login','LOGIN_BET593');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'loteria','PRECHECK.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecargarBet593','RECARGA593');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'loteria','EXECUTE.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ConfirmarBet593','CONFIRMAR593');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'loteria','VERIFY.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ValidarBet593','VALIDAR593');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'loteria','REVERSE.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ReversarBet593','REVERSAR593');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'loteria','PRECHECK.CASHOUT','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ConsultarRetiroBet593','CONSULTAR_RETIRO');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'loteria','EXECUTE.CASHOUT','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RetirarBet593','RETIRO593');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'loteria','VERIFY.CASHOUT','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ConsultarRetiroBet593','CON_RETIRO593');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'loteria','REVERSE.CASHOUT','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ReversarRetiroBet593','REV_RETIRO593');

  -- ---- LN PEGA3 ----------------------------------------------
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'pega3','LOGIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/Login','LOGIN_PEGA3');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'pega3','PRECHECK.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/VentaProductos','VENTA_PRODUCTOS_PEGA3');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'pega3','PRECHECK_SORTEO.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ObtieneSorteosActivo','SORTEOS_ACTIVO_PEGA3');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'pega3','CREATE_TICKET.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/CrearTicket','CREAR_TICKET_PEGA3');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'pega3','EXECUTE.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/PagarTicket','PAGAR_TICKET_PEGA3');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'pega3','VERIFY.CASHIN','S','REST','GET','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ConsultarTicket','CONSULTAR_TICKET_PEGA3');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'pega3','REVERSE.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/CancelarTicket','CANCELAR_TICKET_PEGA3');

  -- ---- LN TRADICIONALES --------------------------------------
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'tradicional','LOGIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/Login','LOGIN_TRAD');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'tradicional','PRECHECK.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecuperarJuegosPorMedio','RECUPERAR_JUEGOS_TRAD');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'tradicional','PRECHECK_SORTEOS.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecuperarSorteosDisponibles','SORTEOS_TRAD');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'tradicional','PRECHECK_FIGURAS.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecuperarFigurasPorJuego','FIGURAS_TRAD');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'tradicional','PRECHECK_NUMEROS.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecuperarNumerosDisponiblesPorCombinacion','NUMEROS_TRAD');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'tradicional','EXECUTE.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/VentaBoletos','VENTA_BOLETOS_TRAD');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'tradicional','VERIFY.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/GenerarComprobanteVenta','COMPROBANTE_TRAD');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'tradicional','REVERSE.CASHIN','S','REST','POST','JSON',
    'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/AnularVentaBoletos','ANULAR_VENTA_TRAD');

  -- ---- CLARO -------------------------------------------------
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'claro','PRECHECK.CASHIN','S','SOAP','POST','XML',
    'http://192.168.37.40:50004/sprXslt/SprXslt','validateRechargeRetail');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL INTO v_id_ws FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
    (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
  VALUES (v_id_ws, 'claro','EXECUTE.CASHIN','S','SOAP','POST','XML',
    'http://192.168.37.40:50004/sprXslt/SprXslt','processRechargeRetail');


  /* ==========================================================
     SECCION 2: IN_OMNI_PROVEEDOR_HEADERS
     ========================================================== */

  -- ECUABET
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL INTO v_id_header FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
  VALUES (v_id_header, 'ecuabet', 'Content-Type', 'application/json');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL INTO v_id_header FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
  VALUES (v_id_header, 'ecuabet', 'Accept', 'application/json');

  -- LN BET593
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL INTO v_id_header FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
  VALUES (v_id_header, 'loteria', 'Content-Type', 'application/json');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL INTO v_id_header FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
  VALUES (v_id_header, 'loteria', 'Accept', 'application/json');

  -- LN PEGA3
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL INTO v_id_header FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
  VALUES (v_id_header, 'pega3', 'Content-Type', 'application/json');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL INTO v_id_header FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
  VALUES (v_id_header, 'pega3', 'Accept', 'application/json');

  -- LN TRADICIONALES
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL INTO v_id_header FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
  VALUES (v_id_header, 'tradicional', 'Content-Type', 'application/json');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL INTO v_id_header FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
  VALUES (v_id_header, 'tradicional', 'Accept', 'application/json');

  -- CLARO
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL INTO v_id_header FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
  VALUES (v_id_header, 'claro', 'Content-Type', 'application/xml;charset=UTF-8');

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_HEADERS.NEXTVAL INTO v_id_header FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_HEADERS (ID_HEADER, PROVEEDOR_KEY, HEADER_NOMBRE, HEADER_VALOR)
  VALUES (v_id_header, 'claro', 'Accept', 'application/xml');


  /* ==========================================================
     SECCION 3: IN_OMNI_PROVEEDOR_WS_DEFS
     NOTA: ID_WS se resuelve con subconsulta inline al INSERT
           (la tabla ya tiene los WS commiteados en la misma sesion)
     ========================================================== */

  -- ECUABET PRECHECK.CASHIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'shop_id', '998739'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='ecuabet' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
  SELECT v_id_default, w.ID_WS, 'NUMERO', 'country', 66
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='ecuabet' AND w.WS_KEY='PRECHECK.CASHIN';

  -- ECUABET EXECUTE.CASHIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'shop_id', '998739'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='ecuabet' AND w.WS_KEY='EXECUTE.CASHIN';

  -- LN BET593 LOGIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
  SELECT v_id_default, w.ID_WS, 'NUMERO', 'medio_id', 23
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='loteria' AND w.WS_KEY='LOGIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
  SELECT v_id_default, w.ID_WS, 'NUMERO', 'cliente_id', 58542
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='loteria' AND w.WS_KEY='LOGIN';

  -- LN PEGA3 LOGIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
  SELECT v_id_default, w.ID_WS, 'NUMERO', 'medio_id', 23
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='LOGIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
  SELECT v_id_default, w.ID_WS, 'NUMERO', 'cliente_id', 58542
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='LOGIN';

  -- LN TRADICIONALES LOGIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
  SELECT v_id_default, w.ID_WS, 'NUMERO', 'medio_id', 23
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='LOGIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
  SELECT v_id_default, w.ID_WS, 'NUMERO', 'cliente_id', 58542
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='LOGIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'canal', 'BMV'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='LOGIN';

  -- CLARO PRECHECK.CASHIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'company_id', '2'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'consumer_id', 'FYBECA_001'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'channel_id', 'CAJA'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'media_id', 'RETA'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'media_detail_id', 'RETA_FYBECA'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'cod_caja', 'DA00004'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'cod_site', '10000004'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'external_operation', 'RECARGA_DATOS'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'subscriber_type', '2'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'subscription_type', 'EVENTUAL'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'OFFERID', 'offer_id.12004565834', '150'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'OFFERID', 'offer_id.12001565829', '132'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='PRECHECK.CASHIN';

  -- CLARO EXECUTE.CASHIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'company_id', '2'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='EXECUTE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'consumer_id', 'FYBECA_001'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='EXECUTE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'cod_caja', 'DA00004'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='EXECUTE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'cod_site', '10000004'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='EXECUTE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'OFFERID', 'offer_id.12004565834', '150'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='EXECUTE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'OFFERID', 'offer_id.12001565829', '132'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='claro' AND w.WS_KEY='EXECUTE.CASHIN';

  /* -- SECCION 3b: Complemento ECUABET shop_id/country faltantes -- */

  -- PRECHECK.CASHOUT
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'shop_id', '998739'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='ecuabet' AND w.WS_KEY='PRECHECK.CASHOUT';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_NUM)
  SELECT v_id_default, w.ID_WS, 'NUMERO', 'country', 66
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='ecuabet' AND w.WS_KEY='PRECHECK.CASHOUT';

  -- EXECUTE.CASHOUT
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'shop_id', '998739'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='ecuabet' AND w.WS_KEY='EXECUTE.CASHOUT';

  -- REVERSE.CASHIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'shop_id', '998739'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='ecuabet' AND w.WS_KEY='REVERSE.CASHIN';

  -- REVERSE.CASHOUT
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
  SELECT v_id_default, w.ID_WS, 'TEXTO', 'shop_id', '998739'
  FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='ecuabet' AND w.WS_KEY='REVERSE.CASHOUT';

  /* -- ITEM (rms_item_code) por WS_KEY -- */

  -- ECUABET
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','100713841' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='ecuabet' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','100708846' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='ecuabet' AND w.WS_KEY='PRECHECK.CASHOUT';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','100713841' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='ecuabet' AND w.WS_KEY='EXECUTE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','100708846' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='ecuabet' AND w.WS_KEY='EXECUTE.CASHOUT';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','100713841' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='ecuabet' AND w.WS_KEY='REVERSE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','100708846' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='ecuabet' AND w.WS_KEY='REVERSE.CASHOUT';

  -- LN BET593
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','100708850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='loteria' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','100708850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='loteria' AND w.WS_KEY='EXECUTE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','100708850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='loteria' AND w.WS_KEY='VERIFY.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','100708850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='loteria' AND w.WS_KEY='REVERSE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','100708848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='loteria' AND w.WS_KEY='EXECUTE.CASHOUT';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','100708848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='loteria' AND w.WS_KEY='VERIFY.CASHOUT';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','100708848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='loteria' AND w.WS_KEY='REVERSE.CASHOUT';

  -- LN PEGA3
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','20001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','20001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='CREATE_TICKET.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','20001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='EXECUTE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','20001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='VERIFY.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','20001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='REVERSE.CASHIN';

  -- LN TRADICIONALES
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','10001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','10001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='EXECUTE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','10001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='VERIFY.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item','10001565830' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='REVERSE.CASHIN';

  /* -- SECCION 3c: items QA/MOMDEV (item.{rmsItemCode}) -- */

  -- PEGA3 PRECHECK.CASHIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100708852','100708852' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713848','100713848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713850','100713850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='PRECHECK.CASHIN';

  -- PEGA3 CREATE_TICKET.CASHIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100708852','100708852' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='CREATE_TICKET.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713848','100713848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='CREATE_TICKET.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713850','100713850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='CREATE_TICKET.CASHIN';

  -- PEGA3 EXECUTE.CASHIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100708852','100708852' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='EXECUTE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713848','100713848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='EXECUTE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713850','100713850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='EXECUTE.CASHIN';

  -- PEGA3 VERIFY.CASHIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100708852','100708852' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='VERIFY.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713848','100713848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='VERIFY.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713850','100713850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='VERIFY.CASHIN';

  -- PEGA3 REVERSE.CASHIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100708852','100708852' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='REVERSE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713848','100713848' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='REVERSE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713850','100713850' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='pega3' AND w.WS_KEY='REVERSE.CASHIN';

  -- TRADICIONALES PRECHECK.CASHIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713842','100713842' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713844','100713844' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='PRECHECK.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713846','100713846' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='PRECHECK.CASHIN';

  -- TRADICIONALES EXECUTE.CASHIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713842','100713842' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='EXECUTE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713844','100713844' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='EXECUTE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713846','100713846' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='EXECUTE.CASHIN';

  -- TRADICIONALES VERIFY.CASHIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713842','100713842' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='VERIFY.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713844','100713844' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='VERIFY.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713846','100713846' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='VERIFY.CASHIN';

  -- TRADICIONALES REVERSE.CASHIN
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713842','100713842' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='REVERSE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713844','100713844' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='REVERSE.CASHIN';

  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL INTO v_id_default FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT,ID_WS,TIPO_DEF,DEFAULT_CLAVE,DEFAULT_VALOR_TEXT)
  SELECT v_id_default,w.ID_WS,'CONFIG','item.100713846','100713846' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY='tradicional' AND w.WS_KEY='REVERSE.CASHIN';


  /* ==========================================================
     SECCION 4: IN_OMNI_PROVEEDOR_CONFIG
     ========================================================== */

  -- ---- ECUABET -----------------------------------------------
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'ecuabet','technical_user','TEXTO','system');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'ecuabet','provider_name','TEXTO','ECUABET');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'ecuabet','category_code','TEXTO','1');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'ecuabet','subcategory_code','TEXTO','1');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'ecuabet','service_provider_code','TEXTO','407925');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'ecuabet','shop_ip','TEXTO','');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'ecuabet','shop_id','TEXTO','998739');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'ecuabet','country','NUMERO','66');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'ecuabet','token','CREDENCIAL','OEpXWWREQVFPSGl1Qi90Sko2RVJsbFM4bVNDRFljNGdzTUcyd2haTERWaz0=');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'ecuabet','auth_mode','TEXTO','STATIC');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'ecuabet','auth_ttl_hours','NUMERO','24');

  -- ---- LN BET593 (loteria) ------------------------------------
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','technical_user','TEXTO','system');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','provider_name','TEXTO','LOTERIA NACIONAL');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','category_code','TEXTO','1');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','subcategory_code','TEXTO','1');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','service_provider_code','TEXTO','407925');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','canal','TEXTO','BMV');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','punto_operacion_id','NUMERO','52132');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','shop_ip','TEXTO','192.168.3.230');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','auth_mode','TEXTO','LOGIN');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','auth_ttl_hours','NUMERO','24');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','auth_refresh_on_startup','FLAG','true');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','auth_username','CREDENCIAL','USRFEMSAPREP');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','auth_password','CREDENCIAL','F3m993sA.');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','auth_product_to_sell','TEXTO','Bet593');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','medio_id','NUMERO','23');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'loteria','cliente_id','NUMERO','58542');

  -- ---- LN PEGA3 -----------------------------------------------
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'pega3','technical_user','TEXTO','system');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'pega3','provider_name','TEXTO','Pega3');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'pega3','category_code','TEXTO','1');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'pega3','subcategory_code','TEXTO','2');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'pega3','service_provider_code','TEXTO','407827');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'pega3','canal','TEXTO','Terminal');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'pega3','shop_id','TEXTO','52132');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'pega3','auth_mode','TEXTO','LOGIN');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'pega3','auth_ttl_hours','NUMERO','24');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'pega3','auth_refresh_on_startup','FLAG','true');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'pega3','auth_username','CREDENCIAL','USRFEMSAPREP');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'pega3','auth_password','CREDENCIAL','F3m993sA.');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'pega3','auth_product_to_sell','TEXTO','Pega3');

  -- ---- LN TRADICIONALES ---------------------------------------
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','technical_user','TEXTO','system');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','provider_name','TEXTO','Tradicionales');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','category_code','TEXTO','1');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','subcategory_code','TEXTO','2');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','service_provider_code','TEXTO','407827');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','shop_id','TEXTO','52132');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','punto_operacion_id','NUMERO','52132');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','auth_mode','TEXTO','LOGIN');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','auth_ttl_hours','NUMERO','24');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','auth_refresh_on_startup','FLAG','true');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','auth_username','CREDENCIAL','USRFEMSAPREP');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','auth_password','CREDENCIAL','F3m993sA.');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','auth_product_to_sell','TEXTO','Tradicionales');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','canal','TEXTO','BMV');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','medio_id','NUMERO','23');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'tradicional','cliente_id','NUMERO','58542');

  -- ---- CLARO --------------------------------------------------
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'claro','category_code','TEXTO','5');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'claro','subcategory_code','TEXTO','9');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'claro','service_provider_code','TEXTO','7');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'claro','token','CREDENCIAL','FYBECA');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'claro','shop_ip','TEXTO','10.35.2.78');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'claro','auth_mode','TEXTO','STATIC');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'claro','auth_username','CREDENCIAL','PRUEBAREC');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'claro','auth_password','CREDENCIAL','5566');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'claro','latitude','TEXTO','2 13 07.878S');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'claro','longitude','TEXTO','80 57 17.965W');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'claro','canton','TEXTO','0901');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'claro','province','TEXTO','09');
  SELECT TUKUNAFUNC.SEQ_IN_OMNI_PROVEEDOR_CONFIG.NEXTVAL INTO v_id_config FROM DUAL;
  INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG (ID_CONFIG,PROVEEDOR_KEY,CONFIG_KEY,TIPO_CONFIG,CONFIG_VALOR) VALUES (v_id_config,'claro','parish','TEXTO','090112');

  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
