/* ============================================================
   SCRIPT : Crear tablas de trazabilidad OmniStack
   SCHEMA : GPF_OMNISTACK
   TABLAS :
     IN_OMNI_LOGS_APP       - Auditoria de peticiones al API
     IN_OMNI_LOGS_WS_EXT    - Log de llamadas a proveedores externos
     IN_OMNI_REGISTRO_TRX   - Registro de transacciones completadas

   EJECUTAR conectado como GPF_OMNISTACK (o con DBA)
   ============================================================ */

-- ============================================================
-- 1) IN_OMNI_LOGS_APP
-- ============================================================
CREATE TABLE GPF_OMNISTACK.IN_OMNI_LOGS_APP (
  CODIGO             NUMBER(18)     NOT NULL,
  UUID               VARCHAR2(200),
  REQUEST            CLOB,
  RESPONSE           CLOB,
  USUARIO            VARCHAR2(100),
  FECHA_REGISTRO     DATE,
  MENSAJE            VARCHAR2(2000),
  PROVEEDOR          VARCHAR2(100),
  CAPABILITY         VARCHAR2(50),
  CANAL              VARCHAR2(50),
  CADENA             NUMBER(10),
  FARMACIA           NUMBER(10),
  NOMBRE_FARMACIA    VARCHAR2(200),
  POS                VARCHAR2(20),
  URL                VARCHAR2(500),
  METODO             VARCHAR2(20),
  HTTP_STATUS        NUMBER(5),
  ES_ERROR           CHAR(1),
  COD_ERROR          VARCHAR2(200),
  MSG_ERROR          VARCHAR2(2000),
  CP_VAR1            VARCHAR2(1500),
  CP_VAR2            VARCHAR2(1500),
  CP_VAR3            VARCHAR2(1500),
  CP_NUMBER1         NUMBER,
  CP_NUMBER2         NUMBER,
  CP_DATE1           DATE,
  CP_DATE2           DATE,
  CONSTRAINT PK_IN_OMNI_LOGS_APP   PRIMARY KEY (CODIGO),
  CONSTRAINT CK_IN_OMNI_LOGS_APP_ERR CHECK (ES_ERROR IN ('S','N'))
);

CREATE SEQUENCE GPF_OMNISTACK.SEQ_IN_OMNI_LOGS_APP
  START WITH 1 INCREMENT BY 1 CACHE 500 NOCYCLE;

CREATE OR REPLACE TRIGGER GPF_OMNISTACK.TRG_IN_OMNI_LOGS_APP_BI
BEFORE INSERT ON GPF_OMNISTACK.IN_OMNI_LOGS_APP
FOR EACH ROW
BEGIN
  IF :NEW.CODIGO IS NULL THEN
    SELECT GPF_OMNISTACK.SEQ_IN_OMNI_LOGS_APP.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
  END IF;
  IF :NEW.FECHA_REGISTRO IS NULL THEN
    :NEW.FECHA_REGISTRO := SYSDATE;
  END IF;
END;
/

CREATE INDEX GPF_OMNISTACK.IX_IN_OMNI_LOGS_APP_UUID  ON GPF_OMNISTACK.IN_OMNI_LOGS_APP (UUID);
CREATE INDEX GPF_OMNISTACK.IX_IN_OMNI_LOGS_APP_FECHA ON GPF_OMNISTACK.IN_OMNI_LOGS_APP (FECHA_REGISTRO);
CREATE INDEX GPF_OMNISTACK.IX_IN_OMNI_LOGS_APP_PROV  ON GPF_OMNISTACK.IN_OMNI_LOGS_APP (PROVEEDOR, FECHA_REGISTRO);
CREATE INDEX GPF_OMNISTACK.IX_IN_OMNI_LOGS_APP_CAP   ON GPF_OMNISTACK.IN_OMNI_LOGS_APP (CAPABILITY, FECHA_REGISTRO);

-- ============================================================
-- 2) IN_OMNI_LOGS_WS_EXT
-- ============================================================
CREATE TABLE GPF_OMNISTACK.IN_OMNI_LOGS_WS_EXT (
  CODIGO             NUMBER(18)     NOT NULL,
  UUID               VARCHAR2(200),
  REQUEST            CLOB,
  RESPONSE           CLOB,
  USUARIO            VARCHAR2(100),
  FECHA_REGISTRO     DATE,
  MENSAJE            VARCHAR2(2000),
  PROVEEDOR          VARCHAR2(100),
  WS_KEY             VARCHAR2(120),
  CANAL              VARCHAR2(50),
  CADENA             NUMBER(10),
  FARMACIA           NUMBER(10),
  POS                VARCHAR2(20),
  URL                VARCHAR2(500),
  METODO             VARCHAR2(20),
  HTTP_STATUS        NUMBER(5),
  DURACION_MS        NUMBER(10),
  ES_ERROR           CHAR(1),
  CP_VAR1            VARCHAR2(1500),
  CP_VAR2            VARCHAR2(1500),
  CP_DATE1           DATE,
  CONSTRAINT PK_IN_OMNI_LOGS_WS_EXT    PRIMARY KEY (CODIGO),
  CONSTRAINT CK_IN_OMNI_LOGS_WS_EXT_ERR CHECK (ES_ERROR IN ('S','N'))
);

CREATE SEQUENCE GPF_OMNISTACK.SEQ_IN_OMNI_LOGS_WS_EXT
  START WITH 1 INCREMENT BY 1 CACHE 500 NOCYCLE;

CREATE OR REPLACE TRIGGER GPF_OMNISTACK.TRG_IN_OMNI_LOGS_WS_EXT_BI
BEFORE INSERT ON GPF_OMNISTACK.IN_OMNI_LOGS_WS_EXT
FOR EACH ROW
BEGIN
  IF :NEW.CODIGO IS NULL THEN
    SELECT GPF_OMNISTACK.SEQ_IN_OMNI_LOGS_WS_EXT.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
  END IF;
  IF :NEW.FECHA_REGISTRO IS NULL THEN
    :NEW.FECHA_REGISTRO := SYSDATE;
  END IF;
END;
/

CREATE INDEX GPF_OMNISTACK.IX_IN_OMNI_LOGS_WS_EXT_UUID  ON GPF_OMNISTACK.IN_OMNI_LOGS_WS_EXT (UUID);
CREATE INDEX GPF_OMNISTACK.IX_IN_OMNI_LOGS_WS_EXT_FECHA ON GPF_OMNISTACK.IN_OMNI_LOGS_WS_EXT (FECHA_REGISTRO);
CREATE INDEX GPF_OMNISTACK.IX_IN_OMNI_LOGS_WS_EXT_PROV  ON GPF_OMNISTACK.IN_OMNI_LOGS_WS_EXT (PROVEEDOR, FECHA_REGISTRO);
CREATE INDEX GPF_OMNISTACK.IX_IN_OMNI_LOGS_WS_EXT_WS    ON GPF_OMNISTACK.IN_OMNI_LOGS_WS_EXT (WS_KEY, FECHA_REGISTRO);

-- ============================================================
-- 3) IN_OMNI_REGISTRO_TRX
-- ============================================================
CREATE TABLE GPF_OMNISTACK.IN_OMNI_REGISTRO_TRX (
  CODIGO                    NUMBER(18)     NOT NULL,
  UUID                      VARCHAR2(200),
  CADENA                    NUMBER(10),
  FARMACIA                  NUMBER(10),
  NOMBRE_FARMACIA           VARCHAR2(200),
  POS                       VARCHAR2(20),
  FECHA_REGISTRO            DATE,
  FECHA_AUTORIZACION_PROV   DATE,
  CANAL                     VARCHAR2(50),
  PROVEEDOR                 VARCHAR2(100),
  CATEGORY_CODE             VARCHAR2(20),
  SUBCATEGORY_CODE          VARCHAR2(20),
  SERVICE_PROVIDER_CODE     VARCHAR2(20),
  RMS_ITEM_CODE             VARCHAR2(100),
  CAPABILITY                VARCHAR2(50),
  ID_EXTERNO                VARCHAR2(200),
  AUTHORIZATION             VARCHAR2(200),
  MONTO                     NUMBER(18,2),
  MONEDA                    VARCHAR2(10)   DEFAULT 'USD',
  COD_ESTADO                VARCHAR2(20),
  ES_ERROR                  CHAR(1),
  COD_ERROR                 VARCHAR2(200),
  MSG_ERROR                 VARCHAR2(2000),
  CP_VAR1                   VARCHAR2(1500),
  CP_VAR2                   VARCHAR2(1500),
  CP_VAR3                   VARCHAR2(1500),
  CP_NUMBER1                NUMBER,
  CP_DATE1                  DATE,
  CONSTRAINT PK_IN_OMNI_REGISTRO_TRX     PRIMARY KEY (CODIGO),
  CONSTRAINT CK_IN_OMNI_REGISTRO_TRX_ERR CHECK (ES_ERROR IN ('S','N')),
  CONSTRAINT CK_IN_OMNI_REGISTRO_TRX_MON CHECK (MONEDA IS NULL OR LENGTH(MONEDA) <= 10)
);

CREATE SEQUENCE GPF_OMNISTACK.SEQ_IN_OMNI_REGISTRO_TRX
  START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;

CREATE OR REPLACE TRIGGER GPF_OMNISTACK.TRG_IN_OMNI_REGISTRO_TRX_BI
BEFORE INSERT ON GPF_OMNISTACK.IN_OMNI_REGISTRO_TRX
FOR EACH ROW
BEGIN
  IF :NEW.CODIGO IS NULL THEN
    SELECT GPF_OMNISTACK.SEQ_IN_OMNI_REGISTRO_TRX.NEXTVAL INTO :NEW.CODIGO FROM DUAL;
  END IF;
  IF :NEW.FECHA_REGISTRO IS NULL THEN
    :NEW.FECHA_REGISTRO := SYSDATE;
  END IF;
  IF :NEW.MONEDA IS NULL THEN
    :NEW.MONEDA := 'USD';
  END IF;
END;
/

CREATE INDEX GPF_OMNISTACK.IX_IN_OMNI_REGISTRO_TRX_UUID  ON GPF_OMNISTACK.IN_OMNI_REGISTRO_TRX (UUID);
CREATE INDEX GPF_OMNISTACK.IX_IN_OMNI_REGISTRO_TRX_FECHA ON GPF_OMNISTACK.IN_OMNI_REGISTRO_TRX (FECHA_REGISTRO);
CREATE INDEX GPF_OMNISTACK.IX_IN_OMNI_REGISTRO_TRX_AUTH  ON GPF_OMNISTACK.IN_OMNI_REGISTRO_TRX (AUTHORIZATION);
CREATE INDEX GPF_OMNISTACK.IX_IN_OMNI_REGISTRO_TRX_PROV  ON GPF_OMNISTACK.IN_OMNI_REGISTRO_TRX (PROVEEDOR, CAPABILITY, FECHA_REGISTRO);
CREATE INDEX GPF_OMNISTACK.IX_IN_OMNI_REGISTRO_TRX_ESTADO ON GPF_OMNISTACK.IN_OMNI_REGISTRO_TRX (COD_ESTADO, FECHA_REGISTRO);

COMMIT;
