/* ============================================================
   ESQUEMA : TUKUNAFUNC
   PROYECTO : OmniStack
   OBJETIVO : Crear tabla IN_OMNI_INPUT_FIELDS para almacenar
              los campos de entrada que el POS debe recolectar
              por servicio y operacion.
              Responsabilidad del equipo OmniStack — no del negocio.
   ============================================================ */

---------------------------------------------------------------
-- TABLA: IN_OMNI_INPUT_FIELDS
---------------------------------------------------------------
CREATE TABLE TUKUNAFUNC.IN_OMNI_INPUT_FIELDS (
  ID_FIELD              NUMBER(12)     NOT NULL,
  CATEGORY_CODE         VARCHAR2(20)   NOT NULL,
  SUBCATEGORY_CODE      VARCHAR2(20)   NOT NULL,
  SERVICE_PROVIDER_CODE VARCHAR2(50)   NOT NULL,
  RMS_ITEM_CODE         VARCHAR2(50)   NOT NULL,
  FIELD_ID              VARCHAR2(100)  NOT NULL,
  LABEL                 VARCHAR2(200)  NOT NULL,
  FIELD_TYPE            VARCHAR2(20)   NOT NULL,
  CAPABILITY            VARCHAR2(50)   NOT NULL,
  IS_REQUIRED           NUMBER(1)      DEFAULT 1 NOT NULL,
  FIELD_GROUP           VARCHAR2(50),
  CONDITIONAL_OPERATOR  VARCHAR2(200),
  FIELD_ORDER           NUMBER(3)      DEFAULT 0 NOT NULL,
  ENABLED               CHAR(1)        DEFAULT 'S' NOT NULL,
  USR_CREACION          VARCHAR2(100)  DEFAULT USER    NOT NULL,
  FEC_CREACION          DATE           DEFAULT SYSDATE NOT NULL,
  USR_MODIFICACION      VARCHAR2(100),
  FEC_MODIFICACION      DATE,

  CONSTRAINT PK_IN_OMNI_INPUT_FIELDS
    PRIMARY KEY (ID_FIELD),
  CONSTRAINT CK_IN_OMNI_INPUT_FIELDS_ENA
    CHECK (ENABLED IN ('S','N')),
  CONSTRAINT CK_IN_OMNI_INPUT_FIELDS_REQ
    CHECK (IS_REQUIRED IN (0, 1)),
  CONSTRAINT CK_IN_OMNI_INPUT_FIELDS_TYPE
    CHECK (FIELD_TYPE IN ('STRING','DOUBLE','INTEGER','BOOLEAN')),
  CONSTRAINT CK_IN_OMNI_INPUT_FIELDS_CAP
    CHECK (CAPABILITY IN ('PRECHECK','CREATE_TICKET','EXECUTE','VERIFY','REVERSE'))
);

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_INPUT_FIELDS_ITEM
  ON TUKUNAFUNC.IN_OMNI_INPUT_FIELDS (RMS_ITEM_CODE, ENABLED);

CREATE INDEX TUKUNAFUNC.IX_IN_OMNI_INPUT_FIELDS_SPC
  ON TUKUNAFUNC.IN_OMNI_INPUT_FIELDS (SERVICE_PROVIDER_CODE, CAPABILITY);

CREATE SEQUENCE TUKUNAFUNC.SEQ_IN_OMNI_INPUT_FIELDS
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE  TUKUNAFUNC.IN_OMNI_INPUT_FIELDS IS 'Campos de entrada del formulario POS por servicio y operacion OmniStack.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_INPUT_FIELDS.CATEGORY_CODE         IS 'Codigo de categoria (CLASS de RMS).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_INPUT_FIELDS.SUBCATEGORY_CODE      IS 'Codigo de subcategoria (SUBCLASS de RMS).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_INPUT_FIELDS.SERVICE_PROVIDER_CODE IS 'Codigo del proveedor (TERCERO de AD_SERVICIO_PARAMETROS).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_INPUT_FIELDS.RMS_ITEM_CODE         IS 'Codigo de item RMS (CODIGO_ITEM_RMS de AD_SERVICIO_PARAMETROS).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_INPUT_FIELDS.FIELD_ID              IS 'Identificador del campo (camelCase, coincide con campo del request).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_INPUT_FIELDS.LABEL                 IS 'Etiqueta para mostrar en el POS.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_INPUT_FIELDS.FIELD_TYPE            IS 'Tipo de dato: STRING, DOUBLE, INTEGER, BOOLEAN.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_INPUT_FIELDS.CAPABILITY            IS 'Operacion para la que se requiere el campo.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_INPUT_FIELDS.IS_REQUIRED           IS '1=obligatorio, 0=opcional.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_INPUT_FIELDS.FIELD_GROUP           IS 'Agrupacion visual en el POS: ID, PHONE, AMOUNT, PASS, etc.';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_INPUT_FIELDS.CONDITIONAL_OPERATOR  IS 'Condicion para mostrar el campo (null = siempre visible).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_INPUT_FIELDS.FIELD_ORDER           IS 'Orden de presentacion en el formulario (ascendente).';
COMMENT ON COLUMN TUKUNAFUNC.IN_OMNI_INPUT_FIELDS.ENABLED               IS 'S=activo, N=inactivo.';
