-- ============================================================
-- Parche QA — agrega NOMBRE_PROVEEDOR y RUC_PROVEEDOR a
-- AD_SERVICIO_PARAMETROS para eliminar dependencia de rms.SUPS.
-- Ejecutar como GPF_OMNISTACK en MOMDEV_MOMDVPDB (QA).
-- ============================================================

-- Paso 1: DDL — agregar columnas (ignorar error si ya existen)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE GPF_OMNISTACK.AD_SERVICIO_PARAMETROS ADD (NOMBRE_PROVEEDOR VARCHAR2(200), RUC_PROVEEDOR VARCHAR2(20))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -01430 THEN NULL; -- ORA-01430: column already exists
        ELSE RAISE;
        END IF;
END;
/

-- Paso 2: DML — poblar según mapeo TERCERO → proveedor en QA
UPDATE GPF_OMNISTACK.AD_SERVICIO_PARAMETROS SET NOMBRE_PROVEEDOR = 'ECUABET',                 RUC_PROVEEDOR = '1790016919001' WHERE TERCERO = 123456;
UPDATE GPF_OMNISTACK.AD_SERVICIO_PARAMETROS SET NOMBRE_PROVEEDOR = 'ECUABET',                 RUC_PROVEEDOR = '1790016919001' WHERE TERCERO = 654321;
UPDATE GPF_OMNISTACK.AD_SERVICIO_PARAMETROS SET NOMBRE_PROVEEDOR = 'LOTERIA NACIONAL BET593', RUC_PROVEEDOR = '1791765061001' WHERE TERCERO = 987654;
UPDATE GPF_OMNISTACK.AD_SERVICIO_PARAMETROS SET NOMBRE_PROVEEDOR = 'LOTERIA NACIONAL BET593', RUC_PROVEEDOR = '1791765061001' WHERE TERCERO = 458712;
UPDATE GPF_OMNISTACK.AD_SERVICIO_PARAMETROS SET NOMBRE_PROVEEDOR = 'LOTERIA NACIONAL',        RUC_PROVEEDOR = '1791765061001' WHERE TERCERO = 2;

COMMIT;

-- Verificacion
SELECT TERCERO, NOMBRE_PROVEEDOR, RUC_PROVEEDOR, COUNT(*) AS items
FROM GPF_OMNISTACK.AD_SERVICIO_PARAMETROS
GROUP BY TERCERO, NOMBRE_PROVEEDOR, RUC_PROVEEDOR
ORDER BY TERCERO;
