-- ============================================================
-- Ejecutar como: TUKUNAFUNC (después de 06_DDL_INPUT_FIELDS.sql)
-- Inserta input_fields para LN PEGA3, LN TRADICIONALES y CLARO en QA.
--
-- ANÁLISIS DE CAMPOS POR PROVEEDOR
-- ─────────────────────────────────────────────────────────────
-- REGLA: input_fields = SOLO lo que el cajero escribe en pantalla.
-- Los campos que fluyen entre fases (authorization, serialnumber,
-- gameTicketNumber, ventaId) son persistidos por el POS y reenviados
-- automáticamente — NO se listan en input_fields.
-- Los campos parametrizables (token, medioId, shopId, offerId, etc.)
-- vienen de PROVEEDOR_CONFIG/WS_DEFS — NUNCA del front.
-- ─────────────────────────────────────────────────────────────
--
-- CAMPOS PARAMETRIZABLES POR PROVEEDOR (origen: PROVEEDOR_CONFIG/WS_DEFS)
-- =========================================================================
-- PEGA3:
--   auth_username / auth_password → LOGIN (nunca expuestos al front)
--   medio_id=23, cliente_id=58542 → WS_DEFS
--   shop_id='52132'               → PROVEEDOR_CONFIG
--   productToSell='Pega3'         → PROVEEDOR_CONFIG
--   (Pega2/Pega4 usan el mismo proveedor_key pero distinto rms_item_code)
--
-- TRADICIONALES:
--   auth_username / auth_password → LOGIN (nunca expuestos al front)
--   medio_id=23, cliente_id=58542 → WS_DEFS / PROVEEDOR_CONFIG
--   canal='BMV'                   → PROVEEDOR_CONFIG (formaCobro)
--   punto_operacion_id=52132      → PROVEEDOR_CONFIG
--
-- CLARO:
--   token='FYBECA', auth_username='PRUEBAREC', auth_password='5566' → PROVEEDOR_CONFIG
--   company_id, consumer_id, channel_id, media_id, media_detail_id  → WS_DEFS
--   cod_caja, cod_site, external_operation                          → WS_DEFS
--   subscriber_type, subscription_type                              → WS_DEFS
--   offer_id (150 o 132 resuelto por rms_item_code)                → WS_DEFS
--   latitude, longitude, canton, province, parish                   → PROVEEDOR_CONFIG
-- =========================================================================
--
-- FLUJO DE CAMPOS POR PROVEEDOR
-- ─────────────────────────────────────────────────────────────
-- PEGA3 CASH_IN:
--   PRECHECK       → sin user input (devuelve game_data + active_draw)
--   CREATE_TICKET  → ticket_data (objeto complejo construido por POS, no simple input)
--                    POS persiste: authorization (gameTicketNumber)
--   EXECUTE        → authorization del CREATE_TICKET (POS lo reenvía), amount del CREATE_TICKET
--   VERIFY         → authorization del CREATE_TICKET (POS lo reenvía)
--   REVERSE        → motivo (cajero escribe) + authorization del CREATE_TICKET (POS lo reenvía)
--
-- TRADICIONALES CASH_IN:
--   PRECHECK       → sin user input requerido (devuelve games/draws/figures/números)
--                    POS puede enviar game_id/draw_id para filtrar (params de navegación)
--   EXECUTE        → document (cédula) + username (nombre) + phone (celular comprador) + boleto_data (POS lo construye)
--   VERIFY         → authorization del EXECUTE (POS lo reenvía = ventaId)
--   REVERSE        → motivo (cajero escribe) + authorization del EXECUTE (POS lo reenvía)
--
-- CLARO CASH_IN:
--   PRECHECK       → phone (celular a recargar) + amount
--                    POS persiste: authorization (=AUTHORIZATIONNUMBER)
--   EXECUTE        → phone + amount rereenviados del PRECHECK (POS los lleva)
--                    authorization del PRECHECK (POS lo reenvía, no lo digita el cajero)
-- ─────────────────────────────────────────────────────────────
--
-- VALORES QA DE CATEGORY/SUBCATEGORY/SVC_PROVIDER:
--   PEGA3/TRAD: category='1', subcategory='2', svc='407827' (PROVEEDOR_CONFIG base)
--               ⚠ CONFIRMAR vs AD_SERVICIO_PARAMETROS en QA si difieren.
--   CLARO:      category='5', subcategory='9', svc='7' (PROVEEDOR_CONFIG)
--   NOTA: input-fields.sql filtra SOLO por RMS_ITEM_CODE — los demás campos
--         son metadata informativa, no afectan el resultado del query.
-- ─────────────────────────────────────────────────────────────
--
-- RMS_ITEM_CODES (fuente: MapeoCampos_v8.xlsx + IN_OMNI_PROVEEDOR_WS_DEFS):
--   PEGA3:        100708852 (Pega3) | 100713848 (Pega4) | 100713850 (Pega2)
--   TRADICIONALES: 100713842 (Lotería) | 100713844 (Lotto) | 100713846 (Pozo Millonario)
--   CLARO:        10001565791..10001565807 (17 productos — MapeoCampos_v8.xlsx sheet9)
--                 ⚠ offerId en WS_DEFS son valores de desarrollo. Confirmar con CLARO en prod.
-- ============================================================


-- ============================================================
-- PEGA3 — REVERSE (único capability con input del cajero)
-- rms_item_codes: 100708852 (Pega3) | 100713848 (Pega4) | 100713850 (Pega2)
--
-- PRECHECK:      NINGUNO — devuelve game_data y active_draw, POS lo usa para
--                          armar ticket_data. No hay pantalla de input.
-- CREATE_TICKET: NINGUNO — ticket_data es objeto complejo; el POS lo construye
--                          desde la selección del cajero en UI propia.
--                          Persiste: authorization=gameTicketNumber
-- EXECUTE:       NINGUNO — authorization viene de CREATE_TICKET (POS lo reenvía)
--                          amount viene del CREATE_TICKET (POS lo reutiliza)
-- VERIFY:        NINGUNO — authorization viene de CREATE_TICKET (POS lo reenvía)
-- REVERSE:       motivo (requerido por @NotBlank en ReverseRequest)
--                authorization del CREATE_TICKET (POS lo reenvía, no lo digita cajero)
-- ============================================================

-- PEGA3 Pega3 (100708852)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100708852',
    'motivo', 'Motivo del reverso', 'STRING', 'REVERSE', 1, 'DETAIL', NULL, 1);

-- PEGA3 Pega4 (100713848)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100713848',
    'motivo', 'Motivo del reverso', 'STRING', 'REVERSE', 1, 'DETAIL', NULL, 1);

-- PEGA3 Pega2 (100713850)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100713850',
    'motivo', 'Motivo del reverso', 'STRING', 'REVERSE', 1, 'DETAIL', NULL, 1);


-- ============================================================
-- TRADICIONALES — EXECUTE (document + username) y REVERSE (motivo)
-- rms_item_codes: 100713842 (Lotería) | 100713844 (Lotto) | 100713846 (Pozo)
--
-- PRECHECK:      NINGUNO — devuelve catálogo de juegos/sorteos/figuras/números.
--                          game_id y draw_id son parámetros de navegación
--                          opcionales que el POS puede enviar para filtrar,
--                          pero NO son campos digitados por el cajero.
-- EXECUTE:       document  → cédula del comprador (cajero la digita)
--                username  → nombre del comprador (cajero lo digita)
--                phone     → celular del comprador (cajero lo digita)
--                boleto_data, amount → construidos/calculados por POS desde
--                            la selección en PRECHECK, no son input del cajero.
--                            (amount = precio sorteo * cantidad_boletos, auto)
--                Persiste:  authorization = ventaId del EXECUTE response
-- VERIFY:        NINGUNO — authorization del EXECUTE (POS lo reenvía)
-- REVERSE:       motivo (requerido por @NotBlank en ReverseRequest)
--                authorization del EXECUTE (POS lo reenvía como ventaId)
-- ============================================================

-- TRADICIONALES Lotería (100713842)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100713842',
    'document', 'Cédula del comprador', 'STRING', 'EXECUTE', 1, 'IDENTIFICATION', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100713842',
    'username', 'Nombre del comprador', 'STRING', 'EXECUTE', 1, 'DETAIL', NULL, 2);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100713842',
    'phone', 'Celular del comprador', 'STRING', 'EXECUTE', 0, 'PHONE', NULL, 3);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100713842',
    'motivo', 'Motivo del reverso', 'STRING', 'REVERSE', 1, 'DETAIL', NULL, 1);

-- TRADICIONALES Lotto (100713844)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100713844',
    'document', 'Cédula del comprador', 'STRING', 'EXECUTE', 1, 'IDENTIFICATION', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100713844',
    'username', 'Nombre del comprador', 'STRING', 'EXECUTE', 1, 'DETAIL', NULL, 2);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100713844',
    'phone', 'Celular del comprador', 'STRING', 'EXECUTE', 0, 'PHONE', NULL, 3);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100713844',
    'motivo', 'Motivo del reverso', 'STRING', 'REVERSE', 1, 'DETAIL', NULL, 1);

-- TRADICIONALES Pozo Millonario (100713846)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100713846',
    'document', 'Cédula del comprador', 'STRING', 'EXECUTE', 1, 'IDENTIFICATION', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100713846',
    'username', 'Nombre del comprador', 'STRING', 'EXECUTE', 1, 'DETAIL', NULL, 2);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100713846',
    'phone', 'Celular del comprador', 'STRING', 'EXECUTE', 0, 'PHONE', NULL, 3);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100713846',
    'motivo', 'Motivo del reverso', 'STRING', 'REVERSE', 1, 'DETAIL', NULL, 1);


-- ============================================================
-- CLARO — PRECHECK (phone + amount) — 17 productos del catálogo
-- Fuente: MapeoCampos_v8.xlsx sheet9 (AD_ITEM_SERVICIO_CLARO)
--         + PDF Claro "CONTRATO SERVICIO WEB RECARGAS VIRTUALES RETAILS V.2"
--
-- Del PDF CLARO (validateRechargeRetail / processRechargeRetail):
--   INPUT del cajero en PRECHECK:
--     SUBSCRIBERID  = phone    → teléfono en 12 dígitos (ej: 593993154323)
--     QUANTITY      = amount   → monto de la recarga
--     OFFERID       = INTERNO  → de IN_OMNI_PROVEEDOR_WS_DEFS por rmsItemCode
--   INTERNOS (de PROVEEDOR_CONFIG):
--     COMPANYID=2, USERNAME=PRUEBAREC, PASSWORD=5566, MEDIAID=RETA,
--     TERMINAL=10.35.2.78, CODCAJA=DA00004, CODSITE=10000004,
--     EXTERNALTRANSACTIONDATE, EXTERNALTRANSACTIONID=uuid
--   EXECUTE: mismos params + AUTHORIZATIONNUMBER del PRECHECK response
--     (POS lo persiste y reenvía — no es input del cajero)
--     Nuevos internos EXECUTE: CONSUMERID=FYBECA_001, CHANNELID=WEB,
--     MEDIADETAILID=RETA_FYBECA, TOKEN=FYBECA, SUBSCRIBERTYPE=2,
--     SUBSCRIPTIONTYPE=EVENTUAL, LATITUDE, LONGITUDE, CANTON, PROVINCE, PARISH
--
-- ⚠ Los offerId (132/150) son valores de desarrollo.
--   Confirmar con CLARO los offerId de producción antes del go-live.
-- ============================================================

-- CLARO RECARGA X DOLARES (10001565791)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565791',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565791',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ 15DIAS 5GB $5.15 (10001565792)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565792',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565792',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ 2DIAS 2GB $2.05 (10001565793)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565793',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565793',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ 1DIA 500MB $1.05 (10001565794)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565794',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565794',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ 3DIAS 6GB $3.10 (10001565795)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565795',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565795',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ 30DIAS 12GB $10.25 (10001565796)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565796',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565796',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ 10DIAS 4GB $4.10 (10001565797)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565797',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565797',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ 30DIAS 15GB $12.30 (10001565798)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565798',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565798',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ 30DIAS 20GB $15.50 (10001565799)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565799',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565799',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ 7DIAS 4GB $3.50 (10001565800)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565800',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565800',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ 20DIAS 6GB $7 (10001565801)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565801',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565801',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ 30DIAS 25GB $20.50 (10001565802)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565802',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565802',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ 25DIAS 7GB $8 (10001565803)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565803',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565803',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ NAVEGACION 2 HORAS (10001565804)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565804',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565804',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO ECDF PAQ 3DIAS 6GB $6 (10001565805)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565805',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565805',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ 30DIAS 10GB $10.50 (10001565806)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565806',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565806',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

-- CLARO PAQ 30DIAS 13GB $12.50 (10001565807)
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565807',
    'phone', 'Celular a recargar', 'STRING', 'PRECHECK', 1, 'PHONE', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '5', '9', '7', '10001565807',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 2);

COMMIT;

-- Verificar (esperado: 49 filas = 3 PEGA3 + 12 TRAD + 34 CLARO):
-- SELECT CATEGORY_CODE, SUBCATEGORY_CODE, RMS_ITEM_CODE, CAPABILITY,
--        FIELD_ORDER, FIELD_ID, LABEL, IS_REQUIRED, FIELD_GROUP
--   FROM TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
--  WHERE RMS_ITEM_CODE IN (
--        '100708852','100713848','100713850',     -- PEGA3
--        '100713842','100713844','100713846',     -- TRAD
--        '10001565791','10001565792','10001565793','10001565794','10001565795',
--        '10001565796','10001565797','10001565798','10001565799','10001565800',
--        '10001565801','10001565802','10001565803','10001565804','10001565805',
--        '10001565806','10001565807'              -- CLARO 17 productos
--  )
--  ORDER BY RMS_ITEM_CODE, CAPABILITY, FIELD_ORDER;
