-- ============================================================
-- Ejecutar como: TUKUNAFUNC
-- Corrige dos problemas que impiden que ClaroPrecheckStrategy.supports()
-- retorne true:
--
-- PROBLEMA A: IN_OMNI_PROVEEDOR_CONFIG tiene category_code='5' y
-- subcategory_code='9' (valores originales del script 02). El supports()
-- compara serviceDefinition.getSubcategoryCode() ('7684') con
-- provider.getSubcategoryCode() ('9') => false.
-- validateBusinessContext en process() también falla con category_code.
--
-- PROBLEMA B: IN_OMNI_PROVEEDOR_WS_DEFS tiene offer_ids con rms_item_codes
-- del Excel (12004565834, 12001565829) que no existen en QA.
-- getOfferIds('claro','PRECHECK.CASHIN').containsKey('291843') => false.
--
-- Asignacion de offerIds (fuente: PDF Claro + script 02):
--   291843 (recarga de monto libre)        → offerId = '132'  (DATOS FRACCION)
--   100733842..100733854 (paquetes fijos)  → offerId = '150'  (DATOS ENTERO)
-- ============================================================

-- ============================================================
-- PARTE A: Corregir category_code y subcategory_code en PROVEEDOR_CONFIG
-- ============================================================
UPDATE TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG
SET CONFIG_VALOR = '8050'
WHERE PROVEEDOR_KEY = 'claro'
  AND CONFIG_KEY    = 'category_code';

UPDATE TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG
SET CONFIG_VALOR = '7684'
WHERE PROVEEDOR_KEY = 'claro'
  AND CONFIG_KEY    = 'subcategory_code';

-- ============================================================
-- PARTE B: Corregir offer_ids en PROVEEDOR_WS_DEFS
-- Borrar los incorrectos (rms_item_codes del Excel) e insertar
-- los correctos (rms_item_codes reales de QA) para ambos WS_KEY.
-- ============================================================

-- Eliminar offer_ids incorrectos (PRECHECK.CASHIN y EXECUTE.CASHIN)
DELETE FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS d
WHERE d.TIPO_DEF = 'OFFERID'
  AND d.ID_WS IN (
      SELECT w.ID_WS FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w
      WHERE w.PROVEEDOR_KEY = 'claro'
        AND w.WS_KEY IN ('PRECHECK.CASHIN', 'EXECUTE.CASHIN')
  );

-- ---- PRECHECK.CASHIN: offer_ids correctos ----

-- 291843 → recarga libre → offerId 132
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.291843', '132'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

-- 100733842..100733854 → paquetes fijos → offerId 150
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733842', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733843', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733844', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733845', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733846', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733847', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733848', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733849', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733850', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733851', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733852', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733853', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733854', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'PRECHECK.CASHIN';

-- ---- EXECUTE.CASHIN: mismos offer_ids ----

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.291843', '132'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733842', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733843', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733844', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733845', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733846', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733847', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733848', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733849', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733850', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733851', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733852', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733853', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'OFFERID', 'offer_id.100733854', '150'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'claro' AND w.WS_KEY = 'EXECUTE.CASHIN';

COMMIT;

-- Verificar PARTE A (esperado: category_code='8050', subcategory_code='7684'):
-- SELECT CONFIG_KEY, CONFIG_VALOR FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG
--  WHERE PROVEEDOR_KEY = 'claro'
--    AND CONFIG_KEY IN ('category_code','subcategory_code','service_provider_code')
--  ORDER BY CONFIG_KEY;

-- Verificar PARTE B (esperado: 14 filas por WS_KEY = 28 filas total):
-- SELECT d.DEFAULT_CLAVE, d.DEFAULT_VALOR_TEXT, w.WS_KEY
--   FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS d
--   JOIN TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w ON w.ID_WS = d.ID_WS
--  WHERE w.PROVEEDOR_KEY = 'claro' AND d.TIPO_DEF = 'OFFERID'
--  ORDER BY w.WS_KEY, d.DEFAULT_CLAVE;
