-- ============================================================
-- Ejecutar como: GPF_OMNISTACK
-- Agrega los TAGs CODCAJA y CODSITE en AD_ITEM_SERVICIO
-- para los 14 items de CLARO (ID_CONFIG 5..18).
--
-- EXTERNALOPERATION ya existe para todos los items (no se toca).
-- MEDIAID es constante para todos los items → va en TUKUNAFUNC.IN_OMNI_PROVEEDOR_CONFIG
--   con config_key='media_id' (script 15).
-- COD_ITEM_SERV es la PK — se usan valores > 18 (max actual).
-- El join con AD_SERVICIO_PARAMETROS es: ai.ID_CONFIG = sp.ID_CONFIG
--
-- Valores QA (dev):
--   CODCAJA  = DA00004    (caja dev asignada por CLARO)
--   CODSITE  = 10000004   (local dev asignado por CLARO)
-- ============================================================

-- ---- CODCAJA ------------------------------------------------
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (33,  5,  'CODCAJA', 'DA00004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (34,  6,  'CODCAJA', 'DA00004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (35,  7,  'CODCAJA', 'DA00004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (36,  8,  'CODCAJA', 'DA00004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (37,  9,  'CODCAJA', 'DA00004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (38,  10, 'CODCAJA', 'DA00004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (39,  11, 'CODCAJA', 'DA00004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (40,  12, 'CODCAJA', 'DA00004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (41,  13, 'CODCAJA', 'DA00004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (42,  14, 'CODCAJA', 'DA00004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (43,  15, 'CODCAJA', 'DA00004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (44,  16, 'CODCAJA', 'DA00004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (45,  17, 'CODCAJA', 'DA00004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (46,  18, 'CODCAJA', 'DA00004');

-- ---- CODSITE ------------------------------------------------
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (47,  5,  'CODSITE', '10000004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (48,  6,  'CODSITE', '10000004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (49,  7,  'CODSITE', '10000004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (50,  8,  'CODSITE', '10000004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (51,  9,  'CODSITE', '10000004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (52,  10, 'CODSITE', '10000004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (53,  11, 'CODSITE', '10000004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (54,  12, 'CODSITE', '10000004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (55,  13, 'CODSITE', '10000004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (56,  14, 'CODSITE', '10000004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (57,  15, 'CODSITE', '10000004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (58,  16, 'CODSITE', '10000004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (59,  17, 'CODSITE', '10000004');
INSERT INTO GPF_OMNISTACK.AD_ITEM_SERVICIO (COD_ITEM_SERV, ID_CONFIG, TAG, VALOR_TAG) VALUES (60,  18, 'CODSITE', '10000004');

COMMIT;

-- Verificar (esperado: 14 EXTERNALOPERATION + 14 CODCAJA + 14 CODSITE = 42 filas):
-- SELECT ai.ID_CONFIG, sp.CODIGO_ITEM_RMS, ai.TAG, ai.VALOR_TAG
--   FROM GPF_OMNISTACK.AD_ITEM_SERVICIO ai
--   JOIN GPF_OMNISTACK.AD_SERVICIO_PARAMETROS sp ON sp.ID_CONFIG = ai.ID_CONFIG
--  WHERE ai.ID_CONFIG BETWEEN 5 AND 18
--  ORDER BY ai.ID_CONFIG, ai.TAG;
