-- ============================================================
-- Mueve RecuperarNumerosDisponiblesPorCombinacion de PRECHECK a CREATE_TICKET
-- para Tradicionales. El proveedor documenta esta operacion como "Obtener y
-- RESERVAR numeros disponibles por combinacion" (docs/LOTERIA NACIONAL.docx)
-- — tiene efecto secundario (pre-reserva boletos), por lo que no corresponde
-- a PRECHECK (prevalidacion sin efectos). Mismo patron que Pega3, donde
-- CREATE_TICKET ya reserva antes del EXECUTE.
--
-- La fila PRECHECK_NUMEROS.CASHIN (tradicional) insertada en 02_DML_PROVEEDORES.sql
-- queda sin uso (LoteriaTradicionalPrecheckStrategy ya no la consulta) — no se
-- elimina, se deja como referencia historica.
-- ============================================================

-- Misma URL real que ya usaba PRECHECK_NUMEROS.CASHIN
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'tradicional','CREATE_TICKET.CASHIN','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/RecuperarNumerosDisponiblesPorCombinacion','NUMEROS_RESERVA_TRAD');

-- ---- item.{rmsItemCode} — habilita hasConfiguredOperation/getRequiredOperationUrl ----
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713842', '100713842'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'CREATE_TICKET.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713844', '100713844'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'CREATE_TICKET.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100713846', '100713846'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'CREATE_TICKET.CASHIN';

-- ---- juego_id.{rmsItemCode} — mismo mapeo que PRECHECK.CASHIN/EXECUTE.CASHIN (script 22) ----
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'juego_id.100713842', '1'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'CREATE_TICKET.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'juego_id.100713844', '2'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'CREATE_TICKET.CASHIN';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'juego_id.100713846', '5'
FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'CREATE_TICKET.CASHIN';
