-- ============================================================
-- CASH_OUT (pago de premio) para Pega3 — items PREMIOS PEGA2/PEGA3/PEGA4.
-- Agrega PRECHECK.CASHOUT (ConsultarTicket) y EXECUTE.CASHOUT (PagarTicket),
-- reusando las mismas URLs fisicas ya usadas por VERIFY.CASHIN/EXECUTE.CASHIN
-- (ver docs/LOTERIA NACIONAL.docx, secciones ConsultarTicket y PagarTicket).
--
-- rms_item_codes: 100708858 (PREMIOS PEGA 4) | 100708860 (PREMIOS PEGA 2) | 100708862 (PREMIOS PEGA 3)
-- Catalogo AD_SERVICIO_PARAMETROS/AD_ITEM_SERVICIO para estos items ya existe
-- (administrado por el usuario funcional) — este script solo agrega la
-- parametrizacion propia de OmniStack (IN_OMNI_PROVEEDOR_WS/WS_DEFS/INPUT_FIELDS).
-- ============================================================

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'pega3','PRECHECK.CASHOUT','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ConsultarTicket','CONSULTAR_TICKET_PEGA3_CASHOUT');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'pega3','EXECUTE.CASHOUT','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/PagarTicket','PAGAR_TICKET_PEGA3_CASHOUT');

-- ---- item.{rmsItemCode} — habilita hasConfiguredOperation/getRequiredOperationUrl ----
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708858', '100708858' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'PRECHECK.CASHOUT';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708860', '100708860' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'PRECHECK.CASHOUT';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708862', '100708862' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'PRECHECK.CASHOUT';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708858', '100708858' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'EXECUTE.CASHOUT';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708860', '100708860' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'EXECUTE.CASHOUT';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708862', '100708862' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'pega3' AND w.WS_KEY = 'EXECUTE.CASHOUT';

-- ---- IN_OMNI_INPUT_FIELDS — el cajero solo escribe el numero de ticket en el PRECHECK ----
-- Mismos category_code/subcategory_code/service_provider_code que el resto de items Pega3 en QA (ver script 09).
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100708858',
    'authorization', 'Numero de ticket', 'STRING', 'PRECHECK', 1, 'IDENTIFICATION', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100708860',
    'authorization', 'Numero de ticket', 'STRING', 'PRECHECK', 1, 'IDENTIFICATION', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100708862',
    'authorization', 'Numero de ticket', 'STRING', 'PRECHECK', 1, 'IDENTIFICATION', NULL, 1);

-- NOTA: EXECUTE.CASHOUT no lleva input_fields — authorization/amount los reenvia el POS
-- tal cual los devolvio el PRECHECK (mismo patron que el resto de flujos CASH_OUT).
