-- ============================================================
-- CASH_OUT (pago de premio) para Tradicionales — items PREMIOS LOTERIA/LOTTO/POZZO.
-- Agrega PRECHECK.CASHOUT (ConsultarTicket) y EXECUTE.CASHOUT (PagoPremioTicketTradicional),
-- endpoints nuevos que hoy no tiene ninguna otra operacion de Tradicionales
-- (ver docs/LOTERIA NACIONAL.docx, secciones ConsultarTicket y PagoPremioTicketTradicional).
--
-- rms_item_codes: 100708854 (PREMIOS LOTERIA) | 100708855 (PREMIOS LOTTO) | 100708856 (PREMIOS POZZO)
-- Catalogo AD_SERVICIO_PARAMETROS/AD_ITEM_SERVICIO para estos items ya existe
-- (administrado por el usuario funcional) — este script solo agrega la
-- parametrizacion propia de OmniStack (IN_OMNI_PROVEEDOR_WS/WS_DEFS/INPUT_FIELDS).
-- ============================================================

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'tradicional','PRECHECK.CASHOUT','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/ConsultarTicket','CONSULTAR_TICKET_TRAD_CASHOUT');

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS
  (ID_WS, PROVEEDOR_KEY, WS_KEY, ENABLED, TIPO_CONEXION, METODO_HTTP, TIPO_REQUEST, URL, NOMBRE_OPERACION)
VALUES
  (SEQ_IN_OMNI_PROVEEDOR_WS.NEXTVAL, 'tradicional','EXECUTE.CASHOUT','S','REST','POST','JSON',
   'https://www8.loteria.com.ec/APIVentasLoteria/api/Ventas/PagoPremioTicketTradicional','PAGO_PREMIO_TRAD_CASHOUT');

-- ---- item.{rmsItemCode} — habilita hasConfiguredOperation/getRequiredOperationUrl ----
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708854', '100708854' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'PRECHECK.CASHOUT';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708855', '100708855' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'PRECHECK.CASHOUT';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708856', '100708856' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'PRECHECK.CASHOUT';

INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708854', '100708854' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'EXECUTE.CASHOUT';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708855', '100708855' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'EXECUTE.CASHOUT';
INSERT INTO TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS_DEFS (ID_DEFAULT, ID_WS, TIPO_DEF, DEFAULT_CLAVE, DEFAULT_VALOR_TEXT)
SELECT SEQ_IN_OMNI_PROVEEDOR_WS_DEFS.NEXTVAL, w.ID_WS, 'CONFIG', 'item.100708856', '100708856' FROM TUKUNAFUNC.IN_OMNI_PROVEEDOR_WS w WHERE w.PROVEEDOR_KEY = 'tradicional' AND w.WS_KEY = 'EXECUTE.CASHOUT';

-- ---- IN_OMNI_INPUT_FIELDS — el cajero escribe el codigo del boleto electronico (cl) y la cedula ----
-- Mismos category_code/subcategory_code/service_provider_code que el resto de items Tradicionales en QA (ver script 09).
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100708854',
    'authorization', 'Clave del boleto electronico', 'STRING', 'PRECHECK', 1, 'IDENTIFICATION', NULL, 1);
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100708854',
    'document', 'Cedula del ganador', 'STRING', 'PRECHECK', 1, 'IDENTIFICATION', NULL, 2);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100708855',
    'authorization', 'Clave del boleto electronico', 'STRING', 'PRECHECK', 1, 'IDENTIFICATION', NULL, 1);
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100708855',
    'document', 'Cedula del ganador', 'STRING', 'PRECHECK', 1, 'IDENTIFICATION', NULL, 2);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100708856',
    'authorization', 'Clave del boleto electronico', 'STRING', 'PRECHECK', 1, 'IDENTIFICATION', NULL, 1);
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '1', '2', '407827', '100708856',
    'document', 'Cedula del ganador', 'STRING', 'PRECHECK', 1, 'IDENTIFICATION', NULL, 2);

-- NOTA: EXECUTE.CASHOUT no lleva input_fields — authorization/amount/mpi los reenvia el POS
-- tal cual los devolvio el PRECHECK (mismo patron que el resto de flujos CASH_OUT).
--
-- NOTA: el control de cupo diario CASH_OUT (CashOutQuotaService) solo se activa si el POS
-- envia "amount" en el PRECHECK (ver TransactionOrchestrationService.reserveCashOutQuota, que
-- hace no-op si amount es null). En este flujo el monto del premio no se conoce hasta que
-- responde ConsultarTicket, por lo que el cupo diario NO aplica automaticamente a estos items
-- salvo que negocio decida lo contrario — pendiente de definicion de negocio, fuera de alcance
-- de este script.
